import { createHash, randomUUID, timingSafeEqual } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { DatabaseSync, type SQLOutputValue } from 'node:sqlite';
import { BackendApplicationContribution } from '@theia/core/lib/node';
import { inject, injectable } from '@theia/core/shared/inversify';
import { KoggOperationRegistry, type OperationLease, type OperationRegistryApi } from '@kogg/operations/lib/common/operations-protocol';
import { TaskAdmissionAuthority, type TaskAdmissionAuthority as AdmissionAuthority } from '@kogg/tasks/lib/common/tasks-protocol';
import { CredentialLeaseAuthority, type AdapterObservationV1, type AgentAdapterSession, type AgentMutationResult, type AgentRegistrySnapshot, type AgentSafeCode, type AttemptProjectionV1, type AttemptState, type CancelAttemptRequestV1, type CreateRoleRevisionRequestV1, type CredentialLeaseAuthority as CredentialAuthority, type KoggAgentsClient, type KoggAgentsService, type OpaqueCredentialLease, type RoleRevisionV1, type StartAttemptRequestV1, type UsageProjectionV1 } from '../common/agents-protocol';
import { AdapterRegistry, AdapterResolutionError } from './adapter-registry';

// diagnostic-coverage: agents.attempts, agents.processes, agents.recovery, agents.logging
type Row = Record<string, SQLOutputValue>;
type DeadlineClass = 'handshake' | 'first-activity' | 'idle' | 'absolute';
type Live = { session: AgentAdapterSession; operation: OperationLease; credentialLease: OpaqueCredentialLease; cancelled: boolean; timers: Map<DeadlineClass, ReturnType<typeof setTimeout>> };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const SYMBOLIC = /^[a-z0-9][a-z0-9._:-]{0,127}$/u;
const DECIMAL = /^(?:0|[1-9][0-9]*)$/u;

@injectable()
export class AgentRegistry implements KoggAgentsService, BackendApplicationContribution {
  private database: DatabaseSync | undefined;
  private readonly live = new Map<string, Live>();
  private readonly databasePath = path.join(stateRoot(), 'agents', 'registry.sqlite3');
  private admission: AgentRegistrySnapshot['admission'] = 'recovering';
  private client: KoggAgentsClient | undefined;
  constructor(@inject(TaskAdmissionAuthority) private readonly tasks: AdmissionAuthority,
    @inject(KoggOperationRegistry) private readonly operations: OperationRegistryApi,
    @inject(AdapterRegistry) private readonly adapters: AdapterRegistry,
    @inject(CredentialLeaseAuthority) private readonly credentials: CredentialAuthority) {}

  async onStart(): Promise<void> {
    console.info('[kogg:agents:recovery] recovery.started');
    try {
      await fs.mkdir(path.dirname(this.databasePath), { recursive: true, mode: 0o700 });
      this.database = new DatabaseSync(this.databasePath, { enableForeignKeyConstraints: true, enableDoubleQuotedStringLiterals: false, allowExtension: false });
      this.database.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA trusted_schema=OFF; PRAGMA busy_timeout=5000;');
      this.migrate(); this.assertIntegrity(); await fs.chmod(this.databasePath, 0o600).catch(error => { if (process.platform !== 'win32') throw error; });
      let recoveredCount = 0; let blockedCount = 0;
      for (const row of this.db().prepare("SELECT attempt_id,state,owned_resource_count FROM attempts WHERE state NOT IN ('cleaned','cleanup_failed','recovered_terminal','unverified_residual')").all() as Row[]) {
        const attemptId = str(row, 'attempt_id'); this.db().prepare('UPDATE attempt_deadlines SET active=0 WHERE attempt_id=?').run(attemptId); this.transition(attemptId, 'recovery_required', 'RECOVERY_REQUIRED'); this.transition(attemptId, 'reconciling');
        if (num(row, 'owned_resource_count') === 0) { console.warn('[kogg:agents:recovery] recovery.classified', { attemptId, recoveryClass: 'proved-absent', safeCode: 'RECOVERY_REQUIRED' }); this.transition(attemptId, 'recovered_terminal', 'RECOVERY_REQUIRED'); console.info('[kogg:agents:registry] attempt.terminal.committed', { attemptId, finalState: 'recovered_terminal', safeCode: 'RECOVERY_REQUIRED', usageStatus: (JSON.parse(str(this.attempt(attemptId), 'usage_json')) as UsageProjectionV1).status }); recoveredCount++; }
        else { console.warn('[kogg:agents:recovery] recovery.classified', { attemptId, recoveryClass: 'identity-unverified', safeCode: 'RESOURCE_IDENTITY_UNVERIFIED' }); this.transition(attemptId, 'unverified_residual', 'RESOURCE_IDENTITY_UNVERIFIED'); console.info('[kogg:agents:registry] attempt.terminal.committed', { attemptId, finalState: 'unverified_residual', safeCode: 'RESOURCE_IDENTITY_UNVERIFIED', usageStatus: (JSON.parse(str(this.attempt(attemptId), 'usage_json')) as UsageProjectionV1).status }); blockedCount++; }
      }
      this.admission = blockedCount ? 'blocked' : 'enabled';
      console.info('[kogg:agents:recovery] recovery.completed', { recoveredCount, blockedCount, admission: this.admission });
    } catch (error) { this.admission = 'blocked'; this.database?.close(); this.database = undefined; console.error('[kogg:agents:recovery] recovery.failed', { errorType: errorName(error), safeCode: codeOf(error) }); throw error; }
  }
  async onStop(): Promise<void> {
    console.info('[kogg:agents:supervision] shutdown.started', { activeCount: this.live.size });
    for (const [attemptId, live] of this.live) await this.cancelLive(attemptId, live, 'shutdown', 'CANCELLED').catch(() => undefined);
    this.database?.close(); this.database = undefined; console.info('[kogg:agents:supervision] shutdown.completed', { residualCount: this.live.size });
  }
  async snapshot(): Promise<AgentRegistrySnapshot> { return { schemaVersion: '1', registryRevision: String(this.registryRevision()), admission: this.admission, roles: await this.listRoleRevisions(), attempts: await this.listAttempts(), adapters: this.adapters.descriptors() }; }
  async subscribe(): Promise<AgentRegistrySnapshot> { return this.snapshot(); }
  setClient(client: KoggAgentsClient | undefined): void { this.client = client; }
  async listAttempts(): Promise<readonly AttemptProjectionV1[]> { return (this.db().prepare('SELECT * FROM attempts ORDER BY requested_at DESC LIMIT 100').all() as Row[]).map(row => this.projection(row)); }
  async getAttempt(attemptId: string): Promise<AttemptProjectionV1> { uuid(attemptId); return this.projection(this.attempt(attemptId)); }
  async listRoleRevisions(): Promise<readonly RoleRevisionV1[]> { return (this.db().prepare('SELECT projection FROM role_revisions ORDER BY created_at DESC LIMIT 100').all() as Row[]).map(row => JSON.parse(str(row, 'projection')) as RoleRevisionV1); }

  async createRoleRevision(request: CreateRoleRevisionRequestV1): Promise<AgentMutationResult> {
    console.debug('[kogg:agents:roles] role.revision.requested', { requestId: safe(request.requestId), roleKey: safeSymbol(request.roleKey) });
    try {
      validateRoleRequest(request); const digest = requestDigest('role', request); const prior = this.replay(request.requestId, digest); if (prior) return prior;
      if (this.registryRevision() !== Number(request.expectedRegistryRevision)) return this.conflict('REGISTRY_REVISION_CONFLICT');
      const roleId = request.roleId ?? randomUUID(); uuid(roleId); const latest = this.db().prepare('SELECT role_revision FROM role_revisions WHERE role_id=? ORDER BY role_revision DESC LIMIT 1').get(roleId) as Row | undefined;
      const roleRevision = latest ? num(latest, 'role_revision') + 1 : 1; const role: RoleRevisionV1 = { schemaVersion: '1', roleId, roleRevisionId: randomUUID(), roleRevision: String(roleRevision), roleKey: request.roleKey, displayName: request.displayName, authority: normalizedAuthority(request.authority), providerPolicy: normalizedProvider(request.providerPolicy), budgetPolicyId: request.budgetPolicyId, createdAt: new Date().toISOString() };
      this.transaction(() => { const revision = this.bumpRegistry(); this.db().prepare('INSERT INTO role_revisions VALUES(?,?,?,?,?,?,?)').run(role.roleRevisionId, role.roleId, role.roleRevision, role.roleKey, canonical(role), JSON.stringify(role), role.createdAt); this.event(undefined, 'role.revision.created', 'AGENT_OK', { roleRevisionId: role.roleRevisionId }); const result: AgentMutationResult = { kind: 'completed', code: 'AGENT_OK', registryRevision: String(revision), role }; this.record(request.requestId, digest, 'role', role.roleRevisionId, result); });
      this.publish(); console.info('[kogg:agents:roles] role.revision.completed', { requestId: request.requestId, roleRevisionId: role.roleRevisionId, roleKey: role.roleKey }); return { kind: 'completed', code: 'AGENT_OK', registryRevision: String(this.registryRevision()), role };
    } catch (error) { // observability-exempt: failed emits the single sanitized terminal failure for this mutation.
      return this.failed('role.revision', request.requestId, error); }
  }

  async startAttempt(request: StartAttemptRequestV1): Promise<AgentMutationResult> {
    console.debug('[kogg:agents:registry] attempt.requested', { requestId: safe(request.requestId) });
    let attemptId: string | undefined; let pendingOperation: OperationLease | undefined; let pendingCredentialLease: OpaqueCredentialLease | undefined; let pendingSession: AgentAdapterSession | undefined;
    try {
      validateStart(request); const digest = requestDigest('start', request); const prior = this.replay(request.requestId, digest); if (prior) return prior;
      if (this.admission !== 'enabled') return this.refused(request.requestId, digest, 'start', 'RECOVERY_REQUIRED');
      if (this.registryRevision() !== Number(request.expectedRegistryRevision)) return this.conflict('REGISTRY_REVISION_CONFLICT');
      const parent = request.parentAttemptId ? this.attempt(request.parentAttemptId) : undefined; attemptId = randomUUID(); const createdAttemptId = attemptId; const rootAttemptId = parent ? str(parent, 'root_attempt_id') : attemptId; const now = new Date().toISOString();
      this.transaction(() => { const revision = this.bumpRegistry(); this.db().prepare(`INSERT INTO attempts(attempt_id,root_attempt_id,parent_attempt_id,attempt_revision,registry_revision,task_admission_id,task_id,project_id,repository_id,specification_id,approval_id,run_id,role_revision_id,adapter_key,adapter_version,provider_id,requested_model_id,observed_model_id,state,terminal_code,activity_count,child_count,owned_resource_count,usage_json,requested_at,state_changed_at,last_observation_sequence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(createdAttemptId, rootAttemptId, request.parentAttemptId ?? null, 1, revision, request.taskAdmissionId, '', '', '', '', '', '', request.roleRevisionId, request.adapterKey, request.adapterVersion, request.providerId, request.modelId, null, 'requested', null, 0, 0, 0, JSON.stringify({ status: 'unknown', source: 'none' }), now, now, 0); this.event(createdAttemptId, 'attempt.requested', 'AGENT_OK'); const result: AgentMutationResult = { kind: 'completed', code: 'AGENT_OK', registryRevision: String(revision), attempt: this.projection(this.attempt(createdAttemptId)) }; this.record(request.requestId, digest, 'start', createdAttemptId, result); });
      const admission = await this.tasks.resolveAdmission(request.taskAdmissionId); if (!admission) { const result = this.terminalRefusal(attemptId, 'TASK_AUTHORITY_STALE'); this.updateRecordedResult(request.requestId, result); return result; }
      const role = this.role(request.roleRevisionId); requireRolePolicy(role, request); if (parent) this.requireChild(parent, role, admission);
      this.updateBindings(attemptId, admission); this.transition(attemptId, 'admitted'); console.info('[kogg:agents:registry] attempt.admitted', { requestId: request.requestId, attemptId, roleRevisionId: request.roleRevisionId, projectId: admission.projectId, taskId: admission.taskId, runId: admission.runId, safeCode: 'AGENT_OK' });
      if (parent) this.attachChild(parent, attemptId);
      const factory = this.adapters.resolveExact({ adapterKey: request.adapterKey, adapterVersion: request.adapterVersion, providerId: request.providerId, modelId: request.modelId, requiredCapabilities: role.providerPolicy.requiredAdapterCapabilities });
      this.transition(attemptId, 'adapter_resolved'); console.info('[kogg:agents:adapter] adapter.resolved', { attemptId, adapterKey: factory.descriptor.adapterKey, adapterVersion: factory.descriptor.adapterVersion, protocolId: factory.descriptor.protocolId, protocolVersion: factory.descriptor.protocolVersion, providerId: request.providerId, modelId: request.modelId });
      const operation = await this.operations.startOperation({ kind: 'agent-dispatch', correlations: { taskId: admission.taskId, runId: admission.runId, attemptId } }); pendingOperation = operation; operation.start();
      const credentialLease = await this.credentials.issue({ attemptId, providerId: request.providerId, modelId: request.modelId, adapterKey: request.adapterKey, adapterVersion: request.adapterVersion, capabilityIds: factory.descriptor.capabilityIds }); pendingCredentialLease = credentialLease;
      const session = factory.create({ attemptId, taskId: admission.taskId, providerId: request.providerId, modelId: request.modelId, operation, credentialLease, onObservation: observation => this.observe(attemptId!, observation) }); pendingSession = session;
      this.registerResource(attemptId, operation.id, session); this.transition(attemptId, 'registered'); console.info('[kogg:agents:supervision] resource.registered', { attemptId, operationId: operation.id, resourceId: session.resourceId, ownerKind: session.ownerKind, resourceKind: session.resourceKind });
      this.live.set(attemptId, { session, operation, credentialLease, cancelled: false, timers: new Map() }); const live = this.live.get(attemptId)!; this.transition(attemptId, 'starting'); this.arm(attemptId, live, 'handshake', duration('handshake'), 'HANDSHAKE_TIMEOUT'); this.arm(attemptId, live, 'absolute', duration('absolute'), 'ABSOLUTE_TIMEOUT'); pendingOperation = undefined; pendingCredentialLease = undefined; pendingSession = undefined; console.debug('[kogg:agents:adapter] adapter.start.requested', { attemptId, resourceId: session.resourceId, deadlineClass: 'handshake' }); void this.runSession(attemptId, live);
      const result: AgentMutationResult = { kind: 'completed', code: 'AGENT_OK', registryRevision: String(this.registryRevision()), attempt: await this.getAttempt(attemptId) }; this.updateRecordedResult(request.requestId, result); return result;
    } catch (error) { // observability-exempt: terminalRefusal or failed emits the classified sanitized terminal outcome below.
      const registeredLive = attemptId ? this.live.get(attemptId) : undefined; if (attemptId && registeredLive) { await this.clean(attemptId, registeredLive, codeOf(error)); const result: AgentMutationResult = { kind: 'refused', code: codeOf(error), registryRevision: String(this.registryRevision()), attempt: this.projection(this.attempt(attemptId)) }; this.updateRecordedResult(request.requestId, result); return result; }
      if (pendingSession) { const cleanup = await pendingSession.cleanup().catch(cleanupError => { console.error('[kogg:agents:supervision] cleanup.failed', { attemptId, childCount: 0, resourceCount: 1, residualCount: 1, safeCode: 'CLEANUP_FAILED', errorType: errorName(cleanupError) }); return { residualCount: 1 }; }); if (!cleanup.residualCount && attemptId) this.markResourceClean(attemptId); }
      pendingCredentialLease?.dispose(); if (pendingOperation) { pendingOperation.fail('OWNER_UNAVAILABLE', errorName(error)); await pendingOperation.cleanup(); }
      if (attemptId) { const result = this.terminalRefusal(attemptId, codeOf(error)); this.updateRecordedResult(request.requestId, result); return result; }
      return this.failed('attempt.start', request.requestId, error);
    }
  }

  async cancelAttempt(request: CancelAttemptRequestV1): Promise<AgentMutationResult> {
    console.info('[kogg:agents:supervision] cancel.requested', { requestId: safe(request.requestId), attemptId: safe(request.attemptId), reason: request.reason });
    try {
      validateCancel(request); const digest = requestDigest('cancel', request); const prior = this.replay(request.requestId, digest); if (prior) return prior;
      const current = this.attempt(request.attemptId); if (this.registryRevision() !== Number(request.expectedRegistryRevision)) return this.conflict('REGISTRY_REVISION_CONFLICT'); if (num(current, 'attempt_revision') !== Number(request.expectedAttemptRevision)) return this.conflict('ATTEMPT_REVISION_CONFLICT', request.attemptId);
      const live = this.live.get(request.attemptId); if (!live) return this.terminalRefusal(request.attemptId, 'RECOVERY_REQUIRED'); this.transition(request.attemptId, 'cancelling', 'CANCELLED'); live.cancelled = true;
      await this.cancelLive(request.attemptId, live, request.reason, 'CANCELLED'); const result: AgentMutationResult = { kind: 'completed', code: 'CANCELLED', registryRevision: String(this.registryRevision()), attempt: await this.getAttempt(request.attemptId) }; this.transaction(() => this.record(request.requestId, digest, 'cancel', request.attemptId, result)); return result;
    } catch (error) { // observability-exempt: failed emits the single sanitized terminal failure for cancellation.
      return this.failed('attempt.cancel', request.requestId, error); }
  }

  diagnostics(): { integrity: boolean; foreignKeys: boolean; eventChain: boolean; activeCount: number; residualCount: number; recoveryComplete: boolean; admission: AgentRegistrySnapshot['admission']; requestConflictCount: number } {
    const integrity = str(this.db().prepare('PRAGMA quick_check').get() as Row, 'quick_check') === 'ok'; const foreignKeys = this.db().prepare('PRAGMA foreign_key_check').all().length === 0; let previous = ''; let eventChain = true;
    for (const row of this.db().prepare('SELECT * FROM events ORDER BY sequence').all() as Row[]) { if (str(row, 'previous_digest') !== previous || eventDigest(row) !== str(row, 'event_digest')) eventChain = false; previous = str(row, 'event_digest'); }
    const activeCount = count(this.db(), "SELECT count(*) AS count FROM attempts WHERE state NOT IN ('cleaned','cleanup_failed','recovered_terminal','unverified_residual')"); const residualCount = count(this.db(), "SELECT count(*) AS count FROM attempts WHERE state IN ('cleanup_failed','unverified_residual')");
    return { integrity, foreignKeys, eventChain, activeCount, residualCount, recoveryComplete: this.admission !== 'recovering', admission: this.admission, requestConflictCount: 0 };
  }

  private async runSession(attemptId: string, live: Live): Promise<void> { try { await live.session.start(); if (this.live.has(attemptId) && !live.cancelled) { const state = str(this.attempt(attemptId), 'state') as AttemptState; if (!['completed_observed', 'failed_observed'].includes(state)) this.transition(attemptId, 'failed_observed', 'ADAPTER_HOST_EXITED'); await this.clean(attemptId, live); } } catch (error) { if (this.live.has(attemptId)) { this.transition(attemptId, 'failed_observed', codeOf(error)); console.error('[kogg:agents:adapter] attempt.failed', { attemptId, safeCode: codeOf(error), errorType: errorName(error), activityCount: num(this.attempt(attemptId), 'activity_count') }); await this.clean(attemptId, live); } } }
  private observe(attemptId: string, observation: AdapterObservationV1): void { try { decimal(observation.sequence); const row = this.attempt(attemptId); if (Number(observation.sequence) <= num(row, 'last_observation_sequence')) throw new AgentError('ADAPTER_OBSERVATION_INVALID'); symbolicOptional(observation.observedModelId); if (observation.observedModelId && observation.observedModelId !== str(row, 'requested_model_id')) throw new AgentError('MODEL_MISMATCH'); this.db().prepare('UPDATE attempts SET last_observation_sequence=? WHERE attempt_id=?').run(Number(observation.sequence), attemptId); const live = this.live.get(attemptId); if (observation.kind === 'ready') { if (live) { this.disarm(attemptId, live, 'handshake'); this.arm(attemptId, live, 'first-activity', duration('first-activity'), 'FIRST_ACTIVITY_TIMEOUT'); } this.transition(attemptId, 'ready'); live?.operation.active(); console.info('[kogg:agents:adapter] adapter.ready', { attemptId, resourceId: live?.session.resourceId }); } else if (observation.kind === 'activity') { if (live) { this.disarm(attemptId, live, 'first-activity'); this.arm(attemptId, live, 'idle', duration('idle'), 'IDLE_TIMEOUT'); } const current = str(this.attempt(attemptId), 'state'); if (current === 'ready') this.transition(attemptId, 'active'); this.incrementActivity(attemptId); console.debug('[kogg:agents:registry] attempt.activity', { attemptId, activityKind: safeSymbol(observation.activityKind ?? 'provider'), activityCount: num(this.attempt(attemptId), 'activity_count') }); } else if (observation.kind === 'usage') this.usage(attemptId, observation.usage); else if (observation.kind === 'completed') { if (live) this.clearPhaseDeadlines(attemptId, live); this.transition(attemptId, 'completed_observed', 'AGENT_OK'); console.info('[kogg:agents:registry] attempt.completion.observed', { attemptId, safeCode: 'AGENT_OK', activityCount: num(this.attempt(attemptId), 'activity_count') }); } else { if (live) this.clearPhaseDeadlines(attemptId, live); this.transition(attemptId, 'failed_observed', observation.safeCode ?? 'PROVIDER_REFUSED'); } } catch (error) { const live = this.live.get(attemptId); const code = codeOf(error); console.error('[kogg:agents:adapter] attempt.failed', { attemptId, safeCode: code, activityCount: num(this.attempt(attemptId), 'activity_count') }); this.transition(attemptId, 'failed_observed', code); if (live) { live.cancelled = true; void this.cancelLive(attemptId, live, 'policy', code); } }
  }
  private async cancelLive(attemptId: string, live: Live, reason: CancelAttemptRequestV1['reason'], finalCode: AgentSafeCode): Promise<void> { this.clearDeadlines(attemptId, live); await this.cancelChildren(attemptId); try { await live.session.cancel(reason); console.debug('[kogg:agents:supervision] cancel.acknowledged', { attemptId, reason, resourceCount: 1 }); } catch (error) { console.warn('[kogg:agents:supervision] cancel.escalated', { attemptId, reason, resourceCount: 1, deadlineClass: 'cancel-grace', errorType: errorName(error) }); } await live.operation.cancel(); await this.clean(attemptId, live, finalCode); }
  private async clean(attemptId: string, live: Live, finalCode?: AgentSafeCode): Promise<void> { if (!this.live.has(attemptId)) return; this.clearDeadlines(attemptId, live); const childCount = num(this.attempt(attemptId), 'child_count'); this.transition(attemptId, 'cleaning', finalCode); console.info('[kogg:agents:supervision] cleanup.started', { attemptId, childCount, resourceCount: 1 }); try { await this.cancelChildren(attemptId); const childrenClean = this.childrenClean(attemptId); const result = await live.session.cleanup(); live.credentialLease.dispose(); await live.operation.cleanup(); const residualCount = result.residualCount + (childrenClean ? 0 : 1); if (residualCount) { this.transition(attemptId, 'cleanup_failed', 'CLEANUP_FAILED'); this.admission = 'blocked'; console.error('[kogg:agents:supervision] cleanup.failed', { attemptId, childCount, resourceCount: 1, residualCount, safeCode: 'CLEANUP_FAILED' }); } else { const prior = finalCode ?? ((str(this.attempt(attemptId), 'terminal_code') as AgentSafeCode | '') || 'AGENT_OK'); this.markResourceClean(attemptId); this.transition(attemptId, 'cleaned', prior); console.info('[kogg:agents:supervision] cleanup.completed', { attemptId, childCount, resourceCount: 1, residualCount: 0 }); console.info('[kogg:agents:registry] attempt.terminal.committed', { attemptId, finalState: 'cleaned', safeCode: prior, usageStatus: (JSON.parse(str(this.attempt(attemptId), 'usage_json')) as UsageProjectionV1).status }); } } catch (error) { live.credentialLease.dispose(); this.transition(attemptId, 'cleanup_failed', 'CLEANUP_FAILED'); this.admission = 'blocked'; console.error('[kogg:agents:supervision] cleanup.failed', { attemptId, childCount, resourceCount: 1, residualCount: 1, safeCode: 'CLEANUP_FAILED', errorType: errorName(error) }); } finally { this.live.delete(attemptId); } }

  private async cancelChildren(parentAttemptId: string): Promise<void> { for (const row of this.db().prepare('SELECT child_attempt_id FROM attempt_children WHERE parent_attempt_id=?').all(parentAttemptId) as Row[]) { const childId = str(row, 'child_attempt_id'); const child = this.attempt(childId); if (terminal(str(child, 'state') as AttemptState)) continue; const live = this.live.get(childId); if (!live) throw new AgentError('RECOVERY_REQUIRED'); if (str(child, 'state') !== 'cancelling') this.transition(childId, 'cancelling', 'CANCELLED'); live.cancelled = true; await this.cancelLive(childId, live, 'parent', 'CANCELLED'); } }
  private childrenClean(parentAttemptId: string): boolean { return (this.db().prepare('SELECT child_attempt_id FROM attempt_children WHERE parent_attempt_id=?').all(parentAttemptId) as Row[]).every(row => ['cleaned', 'recovered_terminal'].includes(str(this.attempt(str(row, 'child_attempt_id')), 'state'))); }

  private arm(attemptId: string, live: Live, deadlineClass: DeadlineClass, configuredMs: number, code: AgentSafeCode): void { this.disarm(attemptId, live, deadlineClass); const prior = this.db().prepare('SELECT generation FROM attempt_deadlines WHERE attempt_id=? AND deadline_class=?').get(attemptId, deadlineClass) as Row | undefined; const generation = prior ? num(prior, 'generation') + 1 : 1; const startsAt = Date.now(); this.db().prepare('INSERT OR REPLACE INTO attempt_deadlines VALUES(?,?,?,?,?,1)').run(attemptId, deadlineClass, generation, new Date(startsAt).toISOString(), new Date(startsAt + configuredMs).toISOString()); const timer = setTimeout(() => { const current = this.db().prepare('SELECT generation,active FROM attempt_deadlines WHERE attempt_id=? AND deadline_class=?').get(attemptId, deadlineClass) as Row | undefined; if (!current || num(current, 'generation') !== generation || num(current, 'active') !== 1 || !this.live.has(attemptId)) return; this.db().prepare('UPDATE attempt_deadlines SET active=0 WHERE attempt_id=? AND deadline_class=?').run(attemptId, deadlineClass); console.warn('[kogg:agents:supervision] timeout.expired', { attemptId, deadlineClass, generation, configuredMs }); this.transition(attemptId, 'timed_out', code); live.cancelled = true; void this.cancelLive(attemptId, live, 'policy', code); }, configuredMs); timer.unref(); live.timers.set(deadlineClass, timer); }
  private disarm(attemptId: string, live: Live, deadlineClass: DeadlineClass): void { const timer = live.timers.get(deadlineClass); if (timer) clearTimeout(timer); live.timers.delete(deadlineClass); if (this.database) this.db().prepare('UPDATE attempt_deadlines SET active=0 WHERE attempt_id=? AND deadline_class=?').run(attemptId, deadlineClass); }
  private clearPhaseDeadlines(attemptId: string, live: Live): void { for (const deadline of ['handshake', 'first-activity', 'idle'] as const) this.disarm(attemptId, live, deadline); }
  private clearDeadlines(attemptId: string, live: Live): void { for (const deadline of [...live.timers.keys()]) this.disarm(attemptId, live, deadline); }

  private terminalRefusal(attemptId: string, code: AgentSafeCode): AgentMutationResult { this.transition(attemptId, 'cleaned', code); console.warn('[kogg:agents:registry] attempt.refused', { attemptId, roleRevisionId: safe(str(this.attempt(attemptId), 'role_revision_id')), projectId: safe(str(this.attempt(attemptId), 'project_id')), taskId: safe(str(this.attempt(attemptId), 'task_id')), safeCode: code }); return { kind: 'refused', code, registryRevision: String(this.registryRevision()), attempt: this.projection(this.attempt(attemptId)) }; }
  private transition(attemptId: string, state: AttemptState, code?: AgentSafeCode): void { this.transaction(() => { const row = this.attempt(attemptId); const revision = this.bumpRegistry(); this.db().prepare('UPDATE attempts SET state=?,terminal_code=COALESCE(?,terminal_code),attempt_revision=?,registry_revision=?,state_changed_at=? WHERE attempt_id=?').run(state, code ?? null, num(row, 'attempt_revision') + 1, revision, new Date().toISOString(), attemptId); this.event(attemptId, `attempt.${state.replaceAll('_', '.')}`, code ?? 'AGENT_OK'); }); this.publish(); }
  private updateBindings(attemptId: string, admission: Awaited<ReturnType<AdmissionAuthority['resolveAdmission']>> & {}): void { this.db().prepare('UPDATE attempts SET task_id=?,project_id=?,repository_id=?,specification_id=?,approval_id=?,run_id=? WHERE attempt_id=?').run(admission.taskId, admission.projectId, admission.repositoryId, admission.specificationId, admission.approvalId, admission.runId, attemptId); }
  private registerResource(attemptId: string, operationId: string, session: AgentAdapterSession): void { this.transaction(() => { this.db().prepare('INSERT INTO resources VALUES(?,?,?,?,?,?)').run(session.resourceId, attemptId, operationId, session.ownerKind, session.resourceKind, 'registered'); this.db().prepare('UPDATE attempts SET owned_resource_count=1 WHERE attempt_id=?').run(attemptId); }); }
  private requireChild(parent: Row, childRole: RoleRevisionV1, admission: NonNullable<Awaited<ReturnType<AdmissionAuthority['resolveAdmission']>>>): void { const parentState = str(parent, 'state') as AttemptState; if (!['starting', 'ready', 'active'].includes(parentState) || str(parent, 'task_id') !== admission.taskId) throw new AgentError('TASK_AUTHORITY_STALE'); const parentRole = this.role(str(parent, 'role_revision_id')); if (!parentRole.authority.mayCreateChildren || !parentRole.authority.permittedChildRoleKeys.includes(childRole.roleKey)) throw new AgentError('CHILD_AUTHORITY_EXPANSION'); if (!subset(childRole.authority.capabilityIds, parentRole.authority.capabilityIds) || !subset(childRole.authority.toolPolicyIds, parentRole.authority.toolPolicyIds) || !subset(childRole.providerPolicy.permittedProviderIds, parentRole.providerPolicy.permittedProviderIds) || !subset(childRole.providerPolicy.permittedModelIds, parentRole.providerPolicy.permittedModelIds)) throw new AgentError('CHILD_AUTHORITY_EXPANSION'); const ancestors = this.ancestorRows(parent); const rootCount = num(this.db().prepare('SELECT count(*) AS count FROM attempts WHERE root_attempt_id=?').get(str(parent, 'root_attempt_id')) as Row, 'count'); if (ancestors.length >= Math.min(4, Number(parentRole.authority.maxChildDepth)) || num(parent, 'child_count') >= Math.min(8, Number(parentRole.authority.maxDirectChildren)) || rootCount >= 32) throw new AgentError('CHILD_LIMIT_EXCEEDED'); if (ancestors.some(row => str(row, 'role_revision_id') === childRole.roleRevisionId)) throw new AgentError('CHILD_CYCLE'); }
  private ancestorRows(start: Row): Row[] { const rows: Row[] = [start]; let current = start; while (current.parent_attempt_id != null) { current = this.attempt(str(current, 'parent_attempt_id')); if (rows.some(row => str(row, 'attempt_id') === str(current, 'attempt_id'))) throw new AgentError('CHILD_CYCLE'); rows.push(current); } return rows; }
  private attachChild(parent: Row, childAttemptId: string): void { this.transaction(() => { const parentId = str(parent, 'attempt_id'); const revision = this.bumpRegistry(); this.db().prepare('INSERT INTO attempt_children VALUES(?,?,?)').run(str(parent, 'root_attempt_id'), parentId, childAttemptId); this.db().prepare('UPDATE attempts SET child_count=child_count+1,attempt_revision=attempt_revision+1,registry_revision=? WHERE attempt_id=?').run(revision, parentId); this.event(parentId, 'child.attached', 'AGENT_OK', { childAttemptId }); }); }
  private markResourceClean(attemptId: string): void { this.db().prepare("UPDATE resources SET cleanup_state='cleaned' WHERE attempt_id=?").run(attemptId); this.db().prepare('UPDATE attempts SET owned_resource_count=0 WHERE attempt_id=?').run(attemptId); }
  private incrementActivity(attemptId: string): void { const value = num(this.attempt(attemptId), 'activity_count'); if (value >= Number.MAX_SAFE_INTEGER) throw new AgentError('USAGE_OVERFLOW'); this.db().prepare('UPDATE attempts SET activity_count=? WHERE attempt_id=?').run(value + 1, attemptId); }
  private usage(attemptId: string, usage?: UsageProjectionV1): void { const row = this.attempt(attemptId); const sequence = num(row, 'last_observation_sequence'); const prior = JSON.parse(str(row, 'usage_json')) as UsageProjectionV1; try { if (!usage || !['unknown', 'partial', 'complete', 'invalid'].includes(usage.status) || !['none', 'provider-cumulative', 'provider-delta', 'kogg-derived'].includes(usage.source)) throw new AgentError('USAGE_INVALID'); for (const value of usageValues(usage)) if (value !== undefined) decimal(value); symbolicOptional(usage.currency); if (prior.source !== 'none' && usage.source !== prior.source) throw new AgentError('USAGE_INVALID'); if (usage.totalTokens !== undefined && usage.inputTokens !== undefined && usage.outputTokens !== undefined && Number(usage.totalTokens) < Number(usage.inputTokens) + Number(usage.outputTokens)) throw new AgentError('USAGE_INVALID'); let normalized = usage; if (usage.source === 'provider-cumulative') for (const field of USAGE_FIELDS) { const before = prior[field]; const next = usage[field]; if (before !== undefined && next !== undefined && Number(next) < Number(before)) throw new AgentError('USAGE_INVALID'); } if (usage.source === 'provider-delta' && prior.source === 'provider-delta') normalized = addUsage(prior, usage); this.db().prepare('INSERT INTO attempt_usage VALUES(?,?,?,?,?)').run(attemptId, sequence, usage.source, usage.status, JSON.stringify(normalized)); this.db().prepare('UPDATE attempts SET usage_json=? WHERE attempt_id=?').run(JSON.stringify(normalized), attemptId); console.debug('[kogg:agents:registry] usage.observed', { attemptId, usageSource: usage.source, usageStatus: normalized.status }); } catch (error) { const invalid: UsageProjectionV1 = { status: 'invalid', source: prior.source === 'none' ? (usage?.source ?? 'none') : prior.source }; this.db().prepare('INSERT OR REPLACE INTO attempt_usage VALUES(?,?,?,?,?)').run(attemptId, sequence, invalid.source, invalid.status, JSON.stringify(invalid)); this.db().prepare('UPDATE attempts SET usage_json=? WHERE attempt_id=?').run(JSON.stringify(invalid), attemptId); console.warn('[kogg:agents:registry] usage.invalid', { attemptId, usageSource: invalid.source, usageStatus: 'invalid', safeCode: 'USAGE_INVALID' }); } }
  private role(id: string): RoleRevisionV1 { uuid(id); const row = this.db().prepare('SELECT projection FROM role_revisions WHERE role_revision_id=?').get(id) as Row | undefined; if (!row) throw new AgentError('ROLE_NOT_FOUND'); return JSON.parse(str(row, 'projection')) as RoleRevisionV1; }
  private attempt(id: string): Row { const row = this.db().prepare('SELECT * FROM attempts WHERE attempt_id=?').get(id) as Row | undefined; if (!row) throw new AgentError('AGENT_REGISTRY_UNAVAILABLE'); return row; }
  private projection(row: Row): AttemptProjectionV1 { const optional = (key: string): string | undefined => row[key] == null || row[key] === '' ? undefined : str(row, key); return { schemaVersion: '1', attemptId: str(row, 'attempt_id'), rootAttemptId: str(row, 'root_attempt_id'), parentAttemptId: optional('parent_attempt_id'), attemptRevision: dec(row, 'attempt_revision'), registryRevision: dec(row, 'registry_revision'), taskId: str(row, 'task_id'), projectId: str(row, 'project_id'), repositoryId: str(row, 'repository_id'), specificationId: str(row, 'specification_id'), approvalId: str(row, 'approval_id'), runId: optional('run_id'), roleRevisionId: str(row, 'role_revision_id'), adapterKey: str(row, 'adapter_key'), adapterVersion: str(row, 'adapter_version'), providerId: str(row, 'provider_id'), requestedModelId: str(row, 'requested_model_id'), observedModelId: optional('observed_model_id'), state: str(row, 'state') as AttemptState, terminalCode: optional('terminal_code') as AgentSafeCode | undefined, activityCount: dec(row, 'activity_count'), childCount: dec(row, 'child_count'), ownedResourceCount: dec(row, 'owned_resource_count'), usage: JSON.parse(str(row, 'usage_json')) as UsageProjectionV1, requestedAt: str(row, 'requested_at'), stateChangedAt: str(row, 'state_changed_at') }; }
  private migrate(): void { this.db().exec(`CREATE TABLE IF NOT EXISTS meta(singleton INTEGER PRIMARY KEY CHECK(singleton=1),schema_version INTEGER NOT NULL,registry_revision INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS role_revisions(role_revision_id TEXT PRIMARY KEY,role_id TEXT NOT NULL,role_revision INTEGER NOT NULL,role_key TEXT NOT NULL,canonical_bytes TEXT NOT NULL UNIQUE,projection TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(role_id,role_revision));
    CREATE TABLE IF NOT EXISTS attempts(attempt_id TEXT PRIMARY KEY,root_attempt_id TEXT NOT NULL,parent_attempt_id TEXT,attempt_revision INTEGER NOT NULL,registry_revision INTEGER NOT NULL,task_admission_id TEXT NOT NULL,task_id TEXT NOT NULL,project_id TEXT NOT NULL,repository_id TEXT NOT NULL,specification_id TEXT NOT NULL,approval_id TEXT NOT NULL,run_id TEXT NOT NULL,role_revision_id TEXT NOT NULL,adapter_key TEXT NOT NULL,adapter_version TEXT NOT NULL,provider_id TEXT NOT NULL,requested_model_id TEXT NOT NULL,observed_model_id TEXT,state TEXT NOT NULL,terminal_code TEXT,activity_count INTEGER NOT NULL,child_count INTEGER NOT NULL,owned_resource_count INTEGER NOT NULL,usage_json TEXT NOT NULL,requested_at TEXT NOT NULL,state_changed_at TEXT NOT NULL,last_observation_sequence INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS resources(resource_id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),operation_id TEXT NOT NULL,owner_kind TEXT NOT NULL,resource_kind TEXT NOT NULL,cleanup_state TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS attempt_deadlines(attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),deadline_class TEXT NOT NULL,generation INTEGER NOT NULL,starts_at TEXT NOT NULL,expires_at TEXT NOT NULL,active INTEGER NOT NULL,PRIMARY KEY(attempt_id,deadline_class));
    CREATE TABLE IF NOT EXISTS attempt_children(root_attempt_id TEXT NOT NULL,parent_attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),child_attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),PRIMARY KEY(parent_attempt_id,child_attempt_id));
    CREATE TABLE IF NOT EXISTS attempt_usage(attempt_id TEXT NOT NULL REFERENCES attempts(attempt_id),provider_sequence INTEGER NOT NULL,usage_source TEXT NOT NULL,usage_status TEXT NOT NULL,projection_json TEXT NOT NULL,PRIMARY KEY(attempt_id,provider_sequence));
    CREATE TABLE IF NOT EXISTS events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL UNIQUE,attempt_id TEXT,event_kind TEXT NOT NULL,safe_code TEXT NOT NULL,safe_fields_json TEXT NOT NULL,previous_digest TEXT NOT NULL,event_digest TEXT NOT NULL UNIQUE);
    CREATE TABLE IF NOT EXISTS idempotency(request_id TEXT PRIMARY KEY,request_digest TEXT NOT NULL,operation_type TEXT NOT NULL,target_id TEXT NOT NULL,result_json TEXT NOT NULL);
    CREATE TRIGGER IF NOT EXISTS agents_roles_update BEFORE UPDATE ON role_revisions BEGIN SELECT RAISE(ABORT,'immutable role'); END; CREATE TRIGGER IF NOT EXISTS agents_roles_delete BEFORE DELETE ON role_revisions BEGIN SELECT RAISE(ABORT,'immutable role'); END; CREATE TRIGGER IF NOT EXISTS agents_events_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT,'immutable event'); END; CREATE TRIGGER IF NOT EXISTS agents_events_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT,'immutable event'); END; CREATE TRIGGER IF NOT EXISTS agents_children_update BEFORE UPDATE ON attempt_children BEGIN SELECT RAISE(ABORT,'immutable child'); END; CREATE TRIGGER IF NOT EXISTS agents_children_delete BEFORE DELETE ON attempt_children BEGIN SELECT RAISE(ABORT,'immutable child'); END; CREATE TRIGGER IF NOT EXISTS agents_usage_update BEFORE UPDATE ON attempt_usage BEGIN SELECT RAISE(ABORT,'immutable usage'); END; CREATE TRIGGER IF NOT EXISTS agents_usage_delete BEFORE DELETE ON attempt_usage BEGIN SELECT RAISE(ABORT,'immutable usage'); END;`); if (!this.db().prepare('SELECT 1 FROM meta').get()) this.db().prepare('INSERT INTO meta VALUES(1,1,0)').run(); if (num(this.db().prepare('SELECT schema_version FROM meta').get() as Row, 'schema_version') !== 1) throw new AgentError('AGENT_REGISTRY_SCHEMA_UNSUPPORTED'); }
  private assertIntegrity(): void { if (str(this.db().prepare('PRAGMA quick_check').get() as Row, 'quick_check') !== 'ok' || this.db().prepare('PRAGMA foreign_key_check').all().length) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); for (const row of this.db().prepare('SELECT canonical_bytes,projection FROM role_revisions').all() as Row[]) if (str(row, 'canonical_bytes') !== canonical(JSON.parse(str(row, 'projection')))) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); let previous = ''; for (const row of this.db().prepare('SELECT * FROM events ORDER BY sequence').all() as Row[]) { if (str(row, 'previous_digest') !== previous || eventDigest(row) !== str(row, 'event_digest')) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); previous = str(row, 'event_digest'); } for (const row of this.db().prepare('SELECT * FROM attempts').all() as Row[]) { const attemptId = str(row, 'attempt_id'); const events = this.db().prepare('SELECT event_kind FROM events WHERE attempt_id=? ORDER BY sequence').all(attemptId) as Row[]; if (events.length !== num(row, 'attempt_revision')) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); const stateEvents = events.filter(event => str(event, 'event_kind').startsWith('attempt.')); if (str(stateEvents.at(-1)!, 'event_kind') !== `attempt.${str(row, 'state').replaceAll('_', '.')}`) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); const ancestors = this.ancestorRows(row); if (str(ancestors.at(-1)!, 'attempt_id') !== str(row, 'root_attempt_id')) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); } for (const row of this.db().prepare('SELECT request_digest FROM idempotency').all() as Row[]) if (!/^[0-9a-f]{64}$/u.test(str(row, 'request_digest'))) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); }
  private event(attemptId: string | undefined, kind: string, code: AgentSafeCode, safeFields: Record<string, string> = {}): void { const prior = this.db().prepare('SELECT event_digest FROM events ORDER BY sequence DESC LIMIT 1').get() as Row | undefined; const previous = prior ? str(prior, 'event_digest') : ''; const record = { eventId: randomUUID(), attemptId, kind, code, safeFields, previous }; const eventDigestValue = hash(canonical(record)); this.db().prepare('INSERT INTO events(event_id,attempt_id,event_kind,safe_code,safe_fields_json,previous_digest,event_digest) VALUES(?,?,?,?,?,?,?)').run(record.eventId, attemptId ?? null, kind, code, JSON.stringify(safeFields), previous, eventDigestValue); }
  private replay(requestId: string, digest: string): AgentMutationResult | undefined { const row = this.db().prepare('SELECT * FROM idempotency WHERE request_id=?').get(requestId) as Row | undefined; if (!row) return undefined; if (!equal(str(row, 'request_digest'), digest)) return { kind: 'refused', code: 'REQUEST_ID_REUSED', registryRevision: String(this.registryRevision()) }; const saved = JSON.parse(str(row, 'result_json')) as AgentMutationResult; const target = str(row, 'target_id'); return { ...saved, registryRevision: String(this.registryRevision()), attempt: str(row, 'operation_type') === 'start' || str(row, 'operation_type') === 'cancel' ? this.projection(this.attempt(target)) : saved.attempt, replay: true }; }
  private record(requestId: string, digest: string, operation: string, targetId: string, result: AgentMutationResult): void { this.db().prepare('INSERT INTO idempotency VALUES(?,?,?,?,?)').run(requestId, digest, operation, targetId, JSON.stringify(result)); }
  private updateRecordedResult(requestId: string, result: AgentMutationResult): void { this.transaction(() => this.db().prepare('UPDATE idempotency SET result_json=? WHERE request_id=?').run(JSON.stringify(result), requestId)); }
  private refused(requestId: string, digest: string, operation: string, code: AgentSafeCode): AgentMutationResult { const result: AgentMutationResult = { kind: 'refused', code, registryRevision: String(this.registryRevision()) }; this.transaction(() => this.record(requestId, digest, operation, '', result)); return result; }
  private conflict(code: 'REGISTRY_REVISION_CONFLICT' | 'ATTEMPT_REVISION_CONFLICT', attemptId?: string): AgentMutationResult { return { kind: 'conflict', code, registryRevision: String(this.registryRevision()), attempt: attemptId ? this.projection(this.attempt(attemptId)) : undefined }; }
  private failed(operation: string, requestId: string, error: unknown): AgentMutationResult { const code = codeOf(error); console.error('[kogg:agents:registry] mutation.failed', { operation, requestId: safe(requestId), safeCode: code, errorType: errorName(error) }); return { kind: 'failed', code, registryRevision: String(this.database ? this.registryRevision() : 0) }; }
  private transaction(run: () => void): void { this.db().exec('BEGIN IMMEDIATE'); try { run(); this.db().exec('COMMIT'); } catch (error) { try { this.db().exec('ROLLBACK'); } catch (rollbackError) { console.error('[kogg:agents:registry] mutation.rollback.failed', { errorType: errorName(rollbackError) }); } throw error; } }
  private bumpRegistry(): number { const revision = this.registryRevision() + 1; this.db().prepare('UPDATE meta SET registry_revision=?').run(revision); return revision; }
  private registryRevision(): number { return num(this.db().prepare('SELECT registry_revision FROM meta').get() as Row, 'registry_revision'); }
  private publish(): void { if (!this.client) return; void this.snapshot().then(snapshot => this.client?.changed(snapshot)).catch(error => console.warn('[kogg:agents:registry] subscription.failed', { errorType: errorName(error) })); }
  private db(): DatabaseSync { if (!this.database) throw new AgentError('AGENT_REGISTRY_UNAVAILABLE'); return this.database; }
}

class AgentError extends Error { constructor(readonly code: AgentSafeCode) { super(code); } }
function validateRoleRequest(request: CreateRoleRevisionRequestV1): void { if (request.schemaVersion !== '1') throw new AgentError('AGENT_REGISTRY_SCHEMA_UNSUPPORTED'); uuid(request.requestId); decimal(request.expectedRegistryRevision); if (request.roleId) uuid(request.roleId); symbolic(request.roleKey); symbolic(request.budgetPolicyId); const displayBytes = Buffer.byteLength(request.displayName); if (displayBytes < 1 || displayBytes > 80) throw new AgentError('POLICY_REFUSED'); const values = [...request.authority.capabilityIds, ...request.authority.toolPolicyIds, ...request.authority.permittedChildRoleKeys, ...request.providerPolicy.permittedProviderIds, ...request.providerPolicy.permittedModelIds, ...request.providerPolicy.requiredAdapterCapabilities]; values.forEach(symbolic); if (request.authority.capabilityIds.length > 64 || request.authority.toolPolicyIds.length > 64 || request.providerPolicy.permittedProviderIds.length > 32 || request.providerPolicy.permittedModelIds.length > 32 || Buffer.byteLength(canonical(request)) > 16 * 1024) throw new AgentError('POLICY_REFUSED'); decimal(request.authority.maxChildDepth); decimal(request.authority.maxDirectChildren); }
function validateStart(request: StartAttemptRequestV1): void { if (request.schemaVersion !== '1') throw new AgentError('AGENT_REGISTRY_SCHEMA_UNSUPPORTED'); [request.requestId, request.taskAdmissionId, request.roleRevisionId, request.parentAttemptId].filter(Boolean).forEach(value => uuid(value!)); decimal(request.expectedRegistryRevision); [request.providerId, request.modelId, request.adapterKey, request.deadlinePolicyId].forEach(symbolic); }
function validateCancel(request: CancelAttemptRequestV1): void { if (request.schemaVersion !== '1') throw new AgentError('AGENT_REGISTRY_SCHEMA_UNSUPPORTED'); uuid(request.requestId); uuid(request.attemptId); decimal(request.expectedRegistryRevision); decimal(request.expectedAttemptRevision); }
function requireRolePolicy(role: RoleRevisionV1, request: StartAttemptRequestV1): void { if (!role.providerPolicy.permittedProviderIds.includes(request.providerId)) throw new AgentError('POLICY_REFUSED'); if (!role.providerPolicy.permittedModelIds.includes(request.modelId)) throw new AgentError('MODEL_MISMATCH'); }
function normalizedAuthority(value: RoleRevisionV1['authority']): RoleRevisionV1['authority'] { return { ...value, capabilityIds: unique(value.capabilityIds), toolPolicyIds: unique(value.toolPolicyIds), permittedChildRoleKeys: unique(value.permittedChildRoleKeys) }; }
function normalizedProvider(value: RoleRevisionV1['providerPolicy']): RoleRevisionV1['providerPolicy'] { return { permittedProviderIds: unique(value.permittedProviderIds), permittedModelIds: unique(value.permittedModelIds), requiredAdapterCapabilities: unique(value.requiredAdapterCapabilities) }; }
function unique(values: readonly string[]): readonly string[] { return [...new Set(values)].sort(); }
function subset(values: readonly string[], grant: readonly string[]): boolean { return values.every(value => grant.includes(value)); }
function terminal(state: AttemptState): boolean { return ['cleaned', 'cleanup_failed', 'recovered_terminal', 'unverified_residual'].includes(state); }
const USAGE_FIELDS = ['inputTokens', 'outputTokens', 'cachedInputTokens', 'reasoningTokens', 'totalTokens', 'costMinorUnits'] as const;
function usageValues(usage: UsageProjectionV1): readonly (string | undefined)[] { return USAGE_FIELDS.map(field => usage[field]); }
function addUsage(prior: UsageProjectionV1, delta: UsageProjectionV1): UsageProjectionV1 { const result: Record<string, unknown> = { status: prior.status === 'complete' && delta.status === 'complete' ? 'complete' : 'partial', source: 'provider-delta' }; for (const field of USAGE_FIELDS) { const left = Number(prior[field] ?? '0'); const right = Number(delta[field] ?? '0'); const value = left + right; if (!Number.isSafeInteger(value)) throw new AgentError('USAGE_OVERFLOW'); if (prior[field] !== undefined || delta[field] !== undefined) result[field] = String(value); } if (prior.currency && delta.currency && prior.currency !== delta.currency) throw new AgentError('USAGE_INVALID'); result.currency = delta.currency ?? prior.currency; return result as unknown as UsageProjectionV1; }
function requestDigest(domain: string, value: unknown): string { return hash(`kogg.agent-attempt-request.v1:${domain}\n${canonical(value)}`); }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; return JSON.stringify(value); }
function eventDigest(row: Row): string { return hash(canonical({ eventId: str(row, 'event_id'), attemptId: row.attempt_id == null ? undefined : str(row, 'attempt_id'), kind: str(row, 'event_kind'), code: str(row, 'safe_code'), safeFields: JSON.parse(str(row, 'safe_fields_json')), previous: str(row, 'previous_digest') })); }
function hash(value: string): string { return createHash('sha256').update(value).digest('hex'); }
function equal(left: string, right: string): boolean { const a = Buffer.from(left); const b = Buffer.from(right); return a.length === b.length && timingSafeEqual(a, b); }
function uuid(value: string): void { if (!UUID.test(value)) throw new AgentError('POLICY_REFUSED'); }
function decimal(value: string): void { if (!DECIMAL.test(value) || Number(value) > Number.MAX_SAFE_INTEGER) throw new AgentError('USAGE_OVERFLOW'); }
function symbolic(value: string): void { if (!SYMBOLIC.test(value)) throw new AgentError('POLICY_REFUSED'); }
function symbolicOptional(value?: string): void { if (value !== undefined) symbolic(value); }
function safe(value: string): string { return UUID.test(value) ? value : 'invalid'; }
function safeSymbol(value: string): string { return SYMBOLIC.test(value) ? value : 'invalid'; }
function str(row: Row, key: string): string { const value = row[key]; if (typeof value !== 'string') throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); return value; }
function num(row: Row, key: string): number { const value = row[key]; if (typeof value !== 'number' || !Number.isSafeInteger(value)) throw new AgentError('AGENT_REGISTRY_INTEGRITY_FAILED'); return value; }
function dec(row: Row, key: string): string { return String(num(row, key)); }
function count(db: DatabaseSync, sql: string): number { return num(db.prepare(sql).get() as Row, 'count'); }
function codeOf(error: unknown): AgentSafeCode { if (error instanceof AgentError || error instanceof AdapterResolutionError) return error.code; if (error instanceof Error && /locked|busy/iu.test(error.message)) return 'AGENT_REGISTRY_BUSY'; if (typeof error === 'object' && error !== null && 'code' in error) { const code = String(error.code); if (['EACCES', 'EPERM', 'EROFS'].includes(code)) return 'AGENT_REGISTRY_PERMISSION_FAILED'; if (AGENT_CODES.has(code as AgentSafeCode)) return code as AgentSafeCode; } return 'AGENT_INTERNAL_FAILURE'; }
function errorName(error: unknown): string { return error instanceof Error ? error.name : 'UnknownError'; }
function stateRoot(): string { const root = process.env.KOGG_ROOT ? path.resolve(process.env.KOGG_ROOT) : process.cwd(); return path.resolve(process.env.KOGG_STATE_DIR ?? path.join(root, '.kogg', 'state')); }
function duration(deadline: 'handshake' | 'first-activity' | 'idle' | 'absolute'): number { if (process.env.KOGG_AGENT_TEST_DEADLINES === '1') return { handshake: 100, 'first-activity': 150, idle: 200, absolute: 1_000 }[deadline]; return { handshake: 30_000, 'first-activity': 60_000, idle: 120_000, absolute: 15 * 60_000 }[deadline]; }
const AGENT_CODES = new Set<AgentSafeCode>(['AGENT_OK', 'ROLE_NOT_FOUND', 'ROLE_REVISION_STALE', 'ROLE_REVOKED', 'TASK_AUTHORITY_STALE', 'PROJECT_BINDING_CHANGED', 'WORKSPACE_UNTRUSTED', 'POLICY_REFUSED', 'BUDGET_REFUSED', 'ADAPTER_UNAVAILABLE', 'ADAPTER_RESOLUTION_AMBIGUOUS', 'ADAPTER_DISABLED', 'PROTOCOL_UNSUPPORTED', 'CAPABILITY_MISMATCH', 'PROVIDER_MISMATCH', 'MODEL_MISMATCH', 'CREDENTIAL_LEASE_REFUSED', 'CHILD_AUTHORITY_EXPANSION', 'CHILD_LIMIT_EXCEEDED', 'CHILD_CYCLE', 'HANDSHAKE_TIMEOUT', 'FIRST_ACTIVITY_TIMEOUT', 'IDLE_TIMEOUT', 'PROVIDER_REQUEST_TIMEOUT', 'ABSOLUTE_TIMEOUT', 'CANCELLED', 'CANCEL_GRACE_EXPIRED', 'PROVIDER_AUTH_REFUSED', 'PROVIDER_RATE_LIMITED', 'PROVIDER_REFUSED', 'TRANSPORT_LOST', 'ADAPTER_HOST_EXITED', 'ADAPTER_OBSERVATION_INVALID', 'USAGE_INVALID', 'USAGE_OVERFLOW', 'RESOURCE_HIDDEN', 'RESOURCE_IDENTITY_UNVERIFIED', 'CLEANUP_FAILED', 'RECOVERY_REQUIRED', 'RECOVERY_FAILED', 'REQUEST_ID_REUSED', 'REGISTRY_REVISION_CONFLICT', 'ATTEMPT_REVISION_CONFLICT', 'AGENT_REGISTRY_UNAVAILABLE', 'AGENT_REGISTRY_BUSY', 'AGENT_REGISTRY_PERMISSION_FAILED', 'AGENT_REGISTRY_SCHEMA_UNSUPPORTED', 'AGENT_REGISTRY_INTEGRITY_FAILED', 'AGENT_INTERNAL_FAILURE']);
