import assert from 'node:assert/strict'; import test from 'node:test'; import type { ClaudePermissionDecisionV1, ClaudePermissionRequestV1, GovernedClaudeAttemptV1 } from '../common/claude-protocol'; import { ClaudePermissionFault, ClaudePermissionGate } from './claude-permission-gate';
// diagnostic-coverage: claude.authority, claude.settings, claude.protocol, claude.cleanup, claude.source-maps
const attempt = { attemptId: '40000000-0000-4000-8000-000000000001', permissionProfileDigest: 'a'.repeat(64), deadlines: { permissionDecisionMs: 60000 } } as GovernedClaudeAttemptV1;
const request = { schemaVersion: '1', requestId: '40000000-0000-4000-8000-000000000002', attemptId: attempt.attemptId, toolId: 'Edit', requestDigest: 'b'.repeat(64), input: { private: 'content' }, inputBytes: 24 } as ClaudePermissionRequestV1;
function decision(overrides: Partial<ClaudePermissionDecisionV1> = {}): ClaudePermissionDecisionV1 { return { schemaVersion: '1', requestId: request.requestId, requestDigest: request.requestDigest, permissionProfileDigest: attempt.permissionProfileDigest, decision: 'allow-once', ...overrides }; }
async function rejects(value: Promise<unknown>, code: ClaudePermissionFault['code']): Promise<void> { await assert.rejects(value, error => error instanceof ClaudePermissionFault && error.code === code); }
test('returns one exact allow-once decision and refuses replay', async () => { const gate = new ClaudePermissionGate(attempt, async () => decision()); assert.equal(await gate.decide(request), 'allow-once'); assert.deepEqual(gate.diagnostics(), { pendingCount: 0, decidedCount: 1, closed: false }); await rejects(gate.decide(request), 'CLAUDE_PERMISSION_PROTOCOL'); });
test('preserves a valid denial as a distinct visible outcome', async () => { const gate = new ClaudePermissionGate(attempt, async () => decision({ decision: 'deny' })); await rejects(gate.decide(request), 'CLAUDE_PERMISSION_DENIED'); assert.equal(gate.diagnostics().decidedCount, 1); });
test('rejects unknown tools, mismatched authority fields, and duplicate concurrent requests', async () => { await rejects(new ClaudePermissionGate(attempt, async () => decision()).decide({ ...request, toolId: 'Task' } as never), 'CLAUDE_PERMISSION_PROTOCOL'); for (const value of [decision({ requestDigest: 'c'.repeat(64) }), decision({ permissionProfileDigest: 'c'.repeat(64) }), { ...decision(), extra: true } as ClaudePermissionDecisionV1]) await rejects(new ClaudePermissionGate(attempt, async () => value).decide(request), 'CLAUDE_PERMISSION_PROTOCOL'); let resolve!: (value: ClaudePermissionDecisionV1) => void; const gate = new ClaudePermissionGate(attempt, () => new Promise(accepted => { resolve = accepted; })); const first = gate.decide(request); await rejects(gate.decide(request), 'CLAUDE_PERMISSION_PROTOCOL'); resolve(decision()); assert.equal(await first, 'allow-once'); });
test('enforces timeout and cancellation without logging private authority errors or request content', async () => { const canary = `private-permission-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values)); try { await rejects(new ClaudePermissionGate(attempt, async () => new Promise(() => undefined), 5).decide({ ...request, input: canary }), 'CLAUDE_PERMISSION_TIMEOUT'); const hostile = new ClaudePermissionGate(attempt, async () => { throw new Error(canary); }); await rejects(hostile.decide({ ...request, requestId: '40000000-0000-4000-8000-000000000003', input: canary }), 'CLAUDE_PERMISSION_PROTOCOL'); let resolve!: (value: ClaudePermissionDecisionV1) => void; const cancelled = new ClaudePermissionGate(attempt, () => new Promise(accepted => { resolve = accepted; })); const pending = cancelled.decide({ ...request, requestId: '40000000-0000-4000-8000-000000000004' }); cancelled.close(); await rejects(pending, 'CLAUDE_PERMISSION_PROTOCOL'); resolve(decision({ requestId: '40000000-0000-4000-8000-000000000004' })); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
