import assert from 'node:assert/strict'; import test from 'node:test'; import type { OpaqueCredentialLease } from '@kogg/agents/lib/common/agents-protocol'; import type { GovernedClaudeAttemptV1 } from '../common/claude-protocol'; import { ClaudeCredentialGrant, type ClaudeCredentialBrokerAuthority } from './claude-credential-grant'; import { ClaudeProcessFault, ClaudeProcessHostGate, type ClaudeProcessAuthority, type ClaudeProcessIdentityV1 } from './claude-process-host';
// diagnostic-coverage: claude.authority, claude.confinement, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
const attempt = { attemptId: '60000000-0000-4000-8000-000000000001', authorityDigest: '9'.repeat(64), artifactManifestDigest: 'a'.repeat(64), legalApprovalDigest: 'd'.repeat(64), executionProfileDigest: 'b'.repeat(64), privateRepoObjectId: '60000000-0000-4000-8000-000000000002', provider: 'anthropic', model: 'claude-sonnet-4-20250514', budgets: { inputTokens: '1000', outputTokens: '500', toolCalls: '20', bytesIn: '100000', bytesOut: '200000' }, deadlines: { spawnMs: 100, gracefulExitMs: 100, terminateMs: 100, killMs: 100, cgroupEmptyMs: 100, absoluteMs: 6000 } } as unknown as GovernedClaudeAttemptV1;
const identity: ClaudeProcessIdentityV1 = { reservationId: 'process-reservation-1', processRegistrationId: 'process-1', cgroupIdentityDigest: 'c'.repeat(64), startTimeTokenDigest: 'd'.repeat(64) };
function fixture(processOverrides: Partial<ClaudeProcessAuthority> = {}, brokerOverrides: Partial<ClaudeCredentialBrokerAuthority> = {}) { const events: string[] = []; const lease: OpaqueCredentialLease = { leaseId: 'lease-1', expiresAt: new Date(Date.now() + 60_000).toISOString(), consume: () => events.push('lease.consume'), dispose: () => events.push('lease.dispose') }; const broker: ClaudeCredentialBrokerAuthority = { reserve: async () => { events.push('broker.reserve'); return { reservationId: 'broker-reservation-1' }; }, activate: async () => { events.push('broker.activate'); }, revoke: async () => { events.push('broker.revoke'); }, ...brokerOverrides }; const credentials = new ClaudeCredentialGrant(attempt, lease, broker); const process: ClaudeProcessAuthority = { reserve: async () => { events.push('process.reserve'); return { reservationId: identity.reservationId }; }, register: async () => { events.push('process.register'); return identity; }, release: async () => { events.push('process.release'); }, signal: async (_value, signal) => { events.push(`process.${signal}`); }, inventory: async () => { events.push('process.inventory'); return { identityVerified: true, memberCount: 0 }; }, ...processOverrides }; return { events, gate: new ClaudeProcessHostGate(attempt, credentials, process), credentials }; }
async function rejects(value: Promise<unknown>, code: string): Promise<void> { await assert.rejects(value, error => error instanceof ClaudeProcessFault && error.code === code); }
test('reserves and registers before releasing one credential-bound process, then proves zero-member cleanup', async () => { const value = fixture(); assert.equal(Object.isFrozen(value.gate.binding), true); await value.gate.reserve(); await value.gate.register(); await value.gate.release(); assert.equal(value.gate.phase(), 'running'); await value.gate.cleanup(); await value.gate.cleanup(); assert.equal(value.gate.phase(), 'cleaned'); assert.deepEqual(value.events, ['process.reserve','process.register','broker.reserve','lease.consume','broker.activate','process.release','broker.revoke','lease.dispose','process.SIGTERM','process.inventory']); await rejects(value.gate.reserve(), 'CLAUDE_SPAWN_PROTOCOL'); });
test('refuses malformed registration and duplicate or out-of-order spawn transitions', async () => { const malformed = fixture({ register: async () => ({ ...identity, cgroupIdentityDigest: 'bad' }) }); await malformed.gate.reserve(); await rejects(malformed.gate.register(), 'CLAUDE_UNREGISTERED_PROCESS'); const order = fixture(); await rejects(order.gate.register(), 'CLAUDE_SPAWN_PROTOCOL'); });
test('escalates to kill and blocks cleanup when externally verified members remain', async () => { const inventories = [1, 1]; const value = fixture({ inventory: async () => ({ identityVerified: true, memberCount: inventories.shift() ?? 1 }) }); await value.gate.reserve(); await value.gate.register(); await value.gate.release(); await rejects(value.gate.cleanup(), 'CLAUDE_RESIDUAL_PROCESS'); assert.equal(value.gate.phase(), 'faulted'); assert.deepEqual(value.events.filter(event => event.startsWith('process.SIG')), ['process.SIGTERM','process.SIGKILL']); assert.equal(value.events.includes('lease.dispose'), true); });
test('normalizes hostile owner errors and still revokes credentials and inventories after release failure', async () => { const canary = `private-process-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values)); try { const value = fixture({ release: async () => { throw new Error(canary); } }); await value.gate.reserve(); await value.gate.register(); await rejects(value.gate.release(), 'CLAUDE_SPAWN_FAILED'); assert.equal(value.events.includes('broker.revoke'), true); assert.equal(value.events.includes('process.inventory'), true); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
