import type { ClaudePermissionDecisionV1, ClaudePermissionRequestV1, ClaudeSafeCode, GovernedClaudeAttemptV1 } from '../common/claude-protocol'; import { claudeLog } from './claude-logger';
// Permission content remains transient inside the qualified authority call. Logs use the closed [kogg:claude:permission] claudeLog schema only.
// diagnostic-coverage: claude.authority, claude.settings, claude.protocol, claude.cleanup, claude.source-maps
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u; const SHA256 = /^[0-9a-f]{64}$/u; const TOOLS = new Set(['Bash','Edit','Glob','Grep','Read','Write']); const MAX_INPUT_BYTES = 1024 * 1024;
export interface ClaudePermissionDiagnostics { readonly pendingCount: number; readonly decidedCount: number; readonly closed: boolean; }
export class ClaudePermissionFault extends Error { constructor(readonly code: Extract<ClaudeSafeCode, 'CLAUDE_PERMISSION_PROTOCOL' | 'CLAUDE_PERMISSION_TIMEOUT' | 'CLAUDE_PERMISSION_DENIED'>) { super(code); } }
export type ClaudePermissionAuthority = (request: ClaudePermissionRequestV1) => Promise<ClaudePermissionDecisionV1>;
export class ClaudePermissionGate {
  private readonly pending = new Map<string, (error: ClaudePermissionFault) => void>(); private readonly decided = new Set<string>(); private closed = false;
  constructor(private readonly attempt: GovernedClaudeAttemptV1, private readonly authority: ClaudePermissionAuthority, private readonly deadlineMs: number = attempt.deadlines.permissionDecisionMs) { if (deadlineMs < 1 || deadlineMs > attempt.deadlines.permissionDecisionMs) throw new Error('Invalid Claude permission deadline'); }
  diagnostics(): ClaudePermissionDiagnostics { return { pendingCount: this.pending.size, decidedCount: this.decided.size, closed: this.closed }; }
  async decide(request: ClaudePermissionRequestV1): Promise<'allow-once' | 'deny'> {
    if (this.closed || !validRequest(request, this.attempt) || this.pending.has(request.requestId) || this.decided.has(request.requestId)) return this.refuse(request?.requestId, 'CLAUDE_PERMISSION_PROTOCOL'); let cancel!: (error: ClaudePermissionFault) => void; const cancelled = new Promise<never>((_resolve, reject) => { cancel = reject; }); this.pending.set(request.requestId, cancel); claudeLog('permission.requested', { attemptId: this.attempt.attemptId, requestId: request.requestId, toolId: request.toolId });
    let timer: NodeJS.Timeout | undefined; const timeout = new Promise<never>((_resolve, reject) => { timer = setTimeout(() => reject(new ClaudePermissionFault('CLAUDE_PERMISSION_TIMEOUT')), this.deadlineMs); });
    try { let decision: ClaudePermissionDecisionV1; try { decision = await Promise.race([this.authority(request), timeout, cancelled]); } catch (error) { /* observability-exempt: only the closed permission fault classification below is logged; authority errors and request content are discarded. */ const code = error instanceof ClaudePermissionFault ? error.code : 'CLAUDE_PERMISSION_PROTOCOL'; return this.refuse(request.requestId, code); } if (!validDecision(decision, request, this.attempt)) return this.refuse(request.requestId, 'CLAUDE_PERMISSION_PROTOCOL'); this.decided.add(request.requestId); claudeLog('permission.decided', { attemptId: this.attempt.attemptId, requestId: request.requestId, decision: decision.decision }); if (decision.decision === 'deny') throw new ClaudePermissionFault('CLAUDE_PERMISSION_DENIED'); return 'allow-once'; }
    finally { if (timer) clearTimeout(timer); this.pending.delete(request.requestId); }
  }
  close(): void { if (this.closed) return; this.closed = true; for (const cancel of this.pending.values()) cancel(new ClaudePermissionFault('CLAUDE_PERMISSION_PROTOCOL')); }
  private refuse(requestId: string | undefined, code: ClaudePermissionFault['code']): never { const safeRequestId = typeof requestId === 'string' && UUID.test(requestId) ? requestId : 'invalid'; if (safeRequestId !== 'invalid') this.decided.add(safeRequestId); claudeLog('permission.failed', { attemptId: this.attempt.attemptId, requestId: safeRequestId, safeCode: code }); throw new ClaudePermissionFault(code); }
}
function validRequest(value: ClaudePermissionRequestV1, attempt: GovernedClaudeAttemptV1): boolean { return Boolean(value) && Object.keys(value).sort().join(',') === ['attemptId','input','inputBytes','requestDigest','requestId','schemaVersion','toolId'].sort().join(',') && value.schemaVersion === '1' && UUID.test(value.requestId) && value.attemptId === attempt.attemptId && TOOLS.has(value.toolId) && SHA256.test(value.requestDigest) && value.input !== undefined && Number.isSafeInteger(value.inputBytes) && value.inputBytes > 0 && value.inputBytes <= MAX_INPUT_BYTES; }
function validDecision(value: ClaudePermissionDecisionV1, request: ClaudePermissionRequestV1, attempt: GovernedClaudeAttemptV1): boolean { return Boolean(value) && Object.keys(value).sort().join(',') === ['decision','permissionProfileDigest','requestDigest','requestId','schemaVersion'].sort().join(',') && value.schemaVersion === '1' && value.requestId === request.requestId && value.requestDigest === request.requestDigest && value.permissionProfileDigest === attempt.permissionProfileDigest && ['allow-once','deny'].includes(value.decision); }
