import type { ClaudeSafeCode, GovernedClaudeAttemptV1 } from '../common/claude-protocol';
import { ClaudeCredentialGrant } from './claude-credential-grant';
import { claudeLog } from './claude-logger';

// The qualified Linux owner retains OS handles. Kogg receives only opaque identities and aggregate inventory, never PID, argv, environment, paths, stdio, or errors.
// diagnostic-coverage: claude.authority, claude.confinement, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
const ID = /^[a-z0-9][a-z0-9._:-]{0,127}$/u; const SHA256 = /^[0-9a-f]{64}$/u;
export interface ClaudeProcessReservationV1 { readonly schemaVersion: '1'; readonly attemptId: string; readonly authorityDigest: string; readonly artifactManifestDigest: string; readonly executionProfileDigest: string; readonly privateRepoObjectId: string; readonly spawnDeadlineMs: number; }
export interface ClaudeProcessIdentityV1 { readonly reservationId: string; readonly processRegistrationId: string; readonly cgroupIdentityDigest: string; readonly startTimeTokenDigest: string; }
export interface ClaudeProcessInventoryV1 { readonly identityVerified: boolean; readonly memberCount: number; }
export interface ClaudeProcessAuthority { reserve(binding: ClaudeProcessReservationV1): Promise<{ readonly reservationId: string }>; register(reservationId: string): Promise<ClaudeProcessIdentityV1>; release(identity: ClaudeProcessIdentityV1): Promise<void>; signal(identity: ClaudeProcessIdentityV1, signal: 'SIGTERM' | 'SIGKILL'): Promise<void>; inventory(identity: ClaudeProcessIdentityV1): Promise<ClaudeProcessInventoryV1>; }
export type ClaudeProcessPhase = 'unreserved' | 'reserved' | 'registered' | 'running' | 'cleaning' | 'cleaned' | 'faulted';
export class ClaudeProcessFault extends Error { constructor(readonly code: Extract<ClaudeSafeCode, 'CLAUDE_SPAWN_FAILED' | 'CLAUDE_SPAWN_PROTOCOL' | 'CLAUDE_RESIDUAL_PROCESS' | 'CLAUDE_UNREGISTERED_PROCESS'>) { super(code); } }
export class ClaudeProcessHostGate {
  private phaseValue: ClaudeProcessPhase = 'unreserved'; private reservationId: string | undefined; private identity: ClaudeProcessIdentityV1 | undefined; private cleaning: Promise<void> | undefined;
  readonly binding: ClaudeProcessReservationV1;
  constructor(private readonly attempt: GovernedClaudeAttemptV1, private readonly credentials: ClaudeCredentialGrant, private readonly authority: ClaudeProcessAuthority) { this.binding = Object.freeze({ schemaVersion: '1', attemptId: attempt.attemptId, authorityDigest: attempt.authorityDigest, artifactManifestDigest: attempt.artifactManifestDigest, executionProfileDigest: attempt.executionProfileDigest, privateRepoObjectId: attempt.privateRepoObjectId, spawnDeadlineMs: attempt.deadlines.spawnMs }); }
  phase(): ClaudeProcessPhase { return this.phaseValue; }
  async reserve(): Promise<void> { if (this.phaseValue !== 'unreserved') return this.fault('CLAUDE_SPAWN_PROTOCOL'); claudeLog('process.reserve.requested', { attemptId: this.attempt.attemptId }); try { const value = await within(this.authority.reserve(this.binding), this.attempt.deadlines.spawnMs, 'CLAUDE_SPAWN_FAILED'); if (!value || Object.keys(value).join(',') !== 'reservationId' || !ID.test(value.reservationId)) return this.fault('CLAUDE_SPAWN_PROTOCOL'); this.reservationId = value.reservationId; this.phaseValue = 'reserved'; claudeLog('process.reserve.completed', { attemptId: this.attempt.attemptId }); } catch (error) { /* observability-exempt: fault emits the closed reservation failure and discards the private owner error. */ return this.fault(error instanceof ClaudeProcessFault ? error.code : 'CLAUDE_SPAWN_FAILED'); } }
  async register(): Promise<void> { if (this.phaseValue !== 'reserved' || !this.reservationId) return this.fault('CLAUDE_SPAWN_PROTOCOL'); try { const value = await within(this.authority.register(this.reservationId), this.attempt.deadlines.spawnMs, 'CLAUDE_SPAWN_FAILED'); if (!validIdentity(value, this.reservationId)) return this.fault('CLAUDE_UNREGISTERED_PROCESS'); this.identity = Object.freeze({ ...value }); this.phaseValue = 'registered'; claudeLog('process.registered', { attemptId: this.attempt.attemptId, processId: value.processRegistrationId }); } catch (error) { /* observability-exempt: fault emits the closed registration failure and discards the private owner error. */ return this.fault(error instanceof ClaudeProcessFault ? error.code : 'CLAUDE_SPAWN_FAILED'); } }
  async release(): Promise<void> { if (this.phaseValue !== 'registered' || !this.identity) return this.fault('CLAUDE_SPAWN_PROTOCOL'); try { await this.credentials.reserve(); await this.credentials.activate(this.identity.processRegistrationId, this.identity.cgroupIdentityDigest); await within(this.authority.release(this.identity), this.attempt.deadlines.spawnMs, 'CLAUDE_SPAWN_FAILED'); this.phaseValue = 'running'; claudeLog('process.spawn.completed', { attemptId: this.attempt.attemptId, processId: this.identity.processRegistrationId }); } catch { /* observability-exempt: credential and process errors are discarded behind the closed spawn failure; cleanup below revokes and inventories. */ this.phaseValue = 'faulted'; claudeLog('process.failure', { attemptId: this.attempt.attemptId, safeCode: 'CLAUDE_SPAWN_FAILED' }); await this.cleanup(); throw new ClaudeProcessFault('CLAUDE_SPAWN_FAILED'); } }
  cleanup(): Promise<void> { return this.cleaning ??= this.cleanupOnce(); }
  private async cleanupOnce(): Promise<void> { if (this.phaseValue === 'cleaned') return; this.phaseValue = 'cleaning'; claudeLog('process.cleanup.requested', { attemptId: this.attempt.attemptId }); let failure: ClaudeProcessFault | undefined; try { await this.credentials.revoke(); } catch { /* observability-exempt: the credential gate emitted the closed revocation failure; process cleanup continues and ultimately fails closed. */ failure = new ClaudeProcessFault('CLAUDE_RESIDUAL_PROCESS'); } if (this.identity) { try { await within(this.authority.signal(this.identity, 'SIGTERM'), this.attempt.deadlines.gracefulExitMs + this.attempt.deadlines.terminateMs, 'CLAUDE_RESIDUAL_PROCESS'); claudeLog('process.signal.completed', { attemptId: this.attempt.attemptId, signalClass: 'terminate' }); let inventory = await this.inventory(); if (inventory.memberCount > 0) { await within(this.authority.signal(this.identity, 'SIGKILL'), this.attempt.deadlines.killMs, 'CLAUDE_RESIDUAL_PROCESS'); claudeLog('process.signal.completed', { attemptId: this.attempt.attemptId, signalClass: 'kill' }); inventory = await this.inventory(); } if (!inventory.identityVerified || inventory.memberCount !== 0) failure = new ClaudeProcessFault('CLAUDE_RESIDUAL_PROCESS'); } catch { /* observability-exempt: owner errors and process identities are discarded behind the aggregate cleanup failure. */ failure = new ClaudeProcessFault('CLAUDE_RESIDUAL_PROCESS'); } } this.phaseValue = failure ? 'faulted' : 'cleaned'; if (failure) { claudeLog('process.cleanup.failed', { attemptId: this.attempt.attemptId, safeCode: failure.code }); throw failure; } claudeLog('process.cleanup.completed', { attemptId: this.attempt.attemptId, residualCount: 0 }); }
  private async inventory(): Promise<ClaudeProcessInventoryV1> { const value = await within(this.authority.inventory(this.identity!), this.attempt.deadlines.cgroupEmptyMs, 'CLAUDE_RESIDUAL_PROCESS'); if (!value || Object.keys(value).sort().join(',') !== ['identityVerified','memberCount'].sort().join(',') || typeof value.identityVerified !== 'boolean' || !Number.isSafeInteger(value.memberCount) || value.memberCount < 0) throw new ClaudeProcessFault('CLAUDE_RESIDUAL_PROCESS'); return value; }
  private fault(code: ClaudeProcessFault['code']): never { this.phaseValue = 'faulted'; claudeLog('process.failure', { attemptId: this.attempt.attemptId, safeCode: code }); throw new ClaudeProcessFault(code); }
}
function validIdentity(value: ClaudeProcessIdentityV1, reservationId: string): boolean { return Boolean(value) && Object.keys(value).sort().join(',') === ['reservationId','processRegistrationId','cgroupIdentityDigest','startTimeTokenDigest'].sort().join(',') && value.reservationId === reservationId && ID.test(value.processRegistrationId) && SHA256.test(value.cgroupIdentityDigest) && SHA256.test(value.startTimeTokenDigest); }
function within<T>(promise: Promise<T>, deadlineMs: number, code: ClaudeProcessFault['code']): Promise<T> { let timer: NodeJS.Timeout | undefined; return Promise.race([promise, new Promise<never>((_resolve, reject) => { timer = setTimeout(() => reject(new ClaudeProcessFault(code)), deadlineMs); })]).finally(() => { if (timer) clearTimeout(timer); }); }
