import assert from 'node:assert/strict'; import { createHash, generateKeyPairSync, sign } from 'node:crypto'; import { mkdir, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import test from 'node:test'; import { AdapterRegistry } from '@kogg/agents/lib/node/adapter-registry'; import { ClaudeAdapterFactory } from './claude-adapter-factory'; import { ClaudeArtifactRegistry } from './claude-artifact-registry'; import { ClaudeAttemptAuthorityRegistry } from './claude-attempt-authority'; import { ClaudeDiagnosticContributor } from './claude-diagnostic-contributor'; import { claudeLog, claudeLoggingDiagnostics } from './claude-logger'; import { ClaudeRecoveryRegistry } from './claude-recovery-registry'; import { ClaudeRuntimeAuthorityRegistry } from './claude-runtime-authority';
// diagnostic-coverage: claude.artifact, claude.authority, claude.legal, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
test('keeps Claude disabled and runtime diagnostics fail closed when approval and recovery owner are absent', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-claude-absent-')); try { const registry = new ClaudeArtifactRegistry(root); const recovery = new ClaudeRecoveryRegistry(); const attempts = new ClaudeAttemptAuthorityRegistry(); const authority = new ClaudeRuntimeAuthorityRegistry(registry, attempts); await registry.onStart(); assert.deepEqual(registry.projection(), { legalApproved: false, artifactVerified: false, confinementVerified: false, credentialBrokerReady: false, sourceMapsPresent: true, safeCode: 'CLAUDE_LEGAL_APPROVAL_REQUIRED' }); assert.throws(() => registry.qualifiedApproval(), /CLAUDE_LEGAL_APPROVAL_REQUIRED/u); const adapters = new AdapterRegistry(); const factory = new ClaudeAdapterFactory(adapters, registry, recovery, authority, attempts); await factory.onStart(); assert.equal(factory.descriptor.enabled, false); assert.throws(() => factory.create({ binding: { attemptId: 'attempt-1' } } as never), /CLAUDE_RECOVERY_REQUIRED/u); const checks = await new ClaudeDiagnosticContributor(registry, recovery, authority, attempts).diagnose(); assert.equal(checks.find(check => check.id === 'claude.authority')?.status, 'fail'); assert.equal(checks.find(check => check.id === 'claude.authority')?.details?.safeCode, 'CLAUDE_ATTEMPT_INVALID'); assert.equal(checks.find(check => check.id === 'claude.processes')?.status, 'fail'); assert.equal(checks.find(check => check.id === 'claude.cleanup')?.status, 'fail'); assert.equal(checks.find(check => check.id === 'claude.recovery')?.status, 'fail'); const sourceMaps = checks.find(check => check.id === 'claude.source-maps'); assert.equal(sourceMaps?.status, 'pass'); assert.equal(sourceMaps?.details?.expectedCount, 12); assert.equal(sourceMaps?.details?.missingCount, 0); } finally { await rm(root, { recursive: true, force: true }); } });
test('accepts and retains an exact signed approval but remains disabled before artifact qualification', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-claude-signed-')); try { const { publicKey, privateKey } = generateKeyPairSync('ed25519'); const unsigned = { schema: 'kogg.claude-commercial-use-approval/v1', packageName: '@anthropic-ai/claude-agent-sdk', packageVersion: '0.3.246', npmIntegritySha512: 'FtR0HoHHNqeqJWjZN8qLUAzZVFUI9ztXYNPPwv98Ecmv9qq2QTauI8IzkY26CC0mleWAqb9RQEW2C0OtiUliug==', tarballSha1: '0009206e79ee0ae25f68ebb526584031cb5db048', approvedProduct: 'kogg', approvedUse: 'governed-agent-adapter', approverRef: 'release-authority', decidedAt: '2026-08-27T00:00:00.000Z', expiresAt: '2026-09-27T00:00:00.000Z', signingKeyId: 'kogg-claude-commercial-approval-v1' }; const approval = { ...unsigned, signature: sign(null, Buffer.from(canonical(unsigned)), privateKey).toString('base64') }; await writeFile(path.join(root, 'claude-commercial-use-approval-v1.json'), JSON.stringify(approval), { mode: 0o600 }); await writeFile(path.join(root, 'claude-commercial-approval-public-key.pem'), publicKey.export({ type: 'spki', format: 'pem' }), { mode: 0o600 }); const registry = new ClaudeArtifactRegistry(root, () => Date.parse('2026-08-28T00:00:00.000Z')); await registry.onStart(); assert.equal(registry.projection().legalApproved, true); assert.equal(registry.projection().safeCode, 'CLAUDE_ARTIFACT_MISMATCH'); assert.deepEqual(registry.qualifiedApproval(), approval); assert.equal(Object.isFrozen(registry.qualifiedApproval()), true); const attempts = new ClaudeAttemptAuthorityRegistry(); const authority = new ClaudeRuntimeAuthorityRegistry(registry, attempts); const factory = new ClaudeAdapterFactory(new AdapterRegistry(), registry, new ClaudeRecoveryRegistry(), authority, attempts); assert.equal(factory.descriptor.enabled, false); } finally { await rm(root, { recursive: true, force: true }); } });
test('refuses validly signed but noncanonical timestamps and non-Ed25519 approval keys', async () => {
  for (const kind of ['timestamp', 'rsa'] as const) { const root = await mkdtemp(path.join(os.tmpdir(), `kogg-claude-${kind}-`)); try { const keys = kind === 'rsa' ? generateKeyPairSync('rsa', { modulusLength: 2048 }) : generateKeyPairSync('ed25519'); const unsigned = { ...approvalFields(), ...(kind === 'timestamp' ? { decidedAt: '2026-08-27 00:00:00Z' } : {}) }; const approval = { ...unsigned, signature: sign(kind === 'rsa' ? 'sha256' : null, Buffer.from(canonical(unsigned)), keys.privateKey).toString('base64') }; await writeFile(path.join(root, 'claude-commercial-use-approval-v1.json'), JSON.stringify(approval), { mode: 0o600 }); await writeFile(path.join(root, 'claude-commercial-approval-public-key.pem'), keys.publicKey.export({ type: 'spki', format: 'pem' }), { mode: 0o600 }); const registry = new ClaudeArtifactRegistry(root, () => Date.parse('2026-08-28T00:00:00.000Z')); await registry.onStart(); assert.equal(registry.projection().legalApproved, false); assert.equal(registry.projection().safeCode, 'CLAUDE_LEGAL_APPROVAL_REQUIRED'); } finally { await rm(root, { recursive: true, force: true }); } }
});
test('refuses a symlinked approval before reading its target', { skip: process.platform === 'win32' }, async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-claude-symlink-')); try { const { publicKey, privateKey } = generateKeyPairSync('ed25519'); const unsigned = approvalFields(); const approval = { ...unsigned, signature: sign(null, Buffer.from(canonical(unsigned)), privateKey).toString('base64') }; await writeFile(path.join(root, 'approval-target.json'), JSON.stringify(approval), { mode: 0o600 }); await symlink('approval-target.json', path.join(root, 'claude-commercial-use-approval-v1.json')); await writeFile(path.join(root, 'claude-commercial-approval-public-key.pem'), publicKey.export({ type: 'spki', format: 'pem' }), { mode: 0o600 }); const registry = new ClaudeArtifactRegistry(root, () => Date.parse('2026-08-28T00:00:00.000Z')); await registry.onStart(); assert.equal(registry.projection().legalApproved, false); assert.equal(registry.projection().safeCode, 'CLAUDE_LEGAL_APPROVAL_REQUIRED'); } finally { await rm(root, { recursive: true, force: true }); } });
test('retains an immutable signed artifact byte attestation without claiming executable readiness', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-claude-artifact-')); const artifactRoot = path.join(root, 'claude-artifact-v1');
  try {
    const approvalKeys = generateKeyPairSync('ed25519'); const artifactKeys = generateKeyPairSync('ed25519'); const approvalUnsigned = approvalFields(); const approval = { ...approvalUnsigned, signature: sign(null, Buffer.from(canonical(approvalUnsigned)), approvalKeys.privateKey).toString('base64') };
    await writeFile(path.join(root, 'claude-commercial-use-approval-v1.json'), JSON.stringify(approval), { mode: 0o600 }); await writeFile(path.join(root, 'claude-commercial-approval-public-key.pem'), approvalKeys.publicKey.export({ type: 'spki', format: 'pem' }), { mode: 0o600 }); await writeFile(path.join(root, 'claude-artifact-public-key.pem'), artifactKeys.publicKey.export({ type: 'spki', format: 'pem' }), { mode: 0o600 });
    const files: Record<string, Buffer> = { 'yarn.lock': Buffer.from('locked\n'), 'package.tgz': Buffer.from('exact approved archive'), 'package/package.json': Buffer.from(JSON.stringify({ name: '@anthropic-ai/claude-agent-sdk', version: '0.3.246' })), 'package/sdk.d.ts': Buffer.from('export {};\n'), 'package/sdk-tools.d.ts': Buffer.from('export {};\n'), 'package/bridge.d.ts': Buffer.from('export {};\n'), 'package/manifest.json': Buffer.from('{}\n'), 'generated/type-projection.json': Buffer.from('{}\n'), 'generated/adapter-schema.json': Buffer.from('{}\n') };
    for (const [name, bytes] of Object.entries(files)) { const target = path.join(artifactRoot, ...name.split('/')); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, bytes, { mode: 0o600 }); }
    const digest = (bytes: Buffer): string => createHash('sha256').update(bytes).digest('hex'); const fileDigests = Object.fromEntries(Object.keys(files).sort().map(name => [name, digest(files[name]!) ]));
    const manifestUnsigned = { schema: 'kogg.claude-artifact/v1', packageName: '@anthropic-ai/claude-agent-sdk', packageVersion: '0.3.246', npmIntegritySha512: createHash('sha512').update(files['package.tgz']!).digest('base64'), tarballSha1: createHash('sha1').update(files['package.tgz']!).digest('hex'), fileDigests, bundledCliVersion: '2.1.0', typeProjectionSha256: fileDigests['generated/type-projection.json'], adapterSchemaSha256: fileDigests['generated/adapter-schema.json'], createdAt: '2026-08-27T00:00:00.000Z', signingKeyId: 'kogg-claude-artifact-v1' } as const;
    const exactApprovalUnsigned = { ...approvalUnsigned, npmIntegritySha512: manifestUnsigned.npmIntegritySha512, tarballSha1: manifestUnsigned.tarballSha1 }; const exactApproval = { ...exactApprovalUnsigned, signature: sign(null, Buffer.from(canonical(exactApprovalUnsigned)), approvalKeys.privateKey).toString('base64') }; await writeFile(path.join(root, 'claude-commercial-use-approval-v1.json'), JSON.stringify(exactApproval), { mode: 0o600 });
    const manifest = { ...manifestUnsigned, signature: sign(null, Buffer.from(canonical(manifestUnsigned)), artifactKeys.privateKey).toString('base64') }; await writeFile(path.join(root, 'claude-artifact-manifest-v1.json'), JSON.stringify(manifest), { mode: 0o600 });
    const identity = { npmIntegritySha512: manifestUnsigned.npmIntegritySha512, tarballSha1: manifestUnsigned.tarballSha1 }; const registry = new ClaudeArtifactRegistry(root, () => Date.parse('2026-08-28T00:00:00.000Z'), artifactRoot, identity); await registry.onStart(); const attested = registry.attestedArtifact(); assert.equal(attested.manifest.bundledCliVersion, '2.1.0'); assert.equal(Object.isFrozen(attested), true); assert.equal(Object.isFrozen(attested.manifest), true); assert.equal(Object.isFrozen(attested.manifest.fileDigests), true); assert.equal(Object.isFrozen(attested.files), true); assert.equal(registry.projection().artifactVerified, false); assert.equal(registry.projection().safeCode, 'CLAUDE_ARTIFACT_MISMATCH');
    await writeFile(path.join(artifactRoot, 'package.tgz'), 'tampered', { mode: 0o600 }); const corrupted = new ClaudeArtifactRegistry(root, () => Date.parse('2026-08-28T00:00:00.000Z'), artifactRoot, identity); await corrupted.onStart(); assert.throws(() => corrupted.attestedArtifact(), /CLAUDE_ARTIFACT_MISMATCH/u); assert.equal(corrupted.projection().artifactVerified, false);
  } finally { await rm(root, { recursive: true, force: true }); }
});
test('rejects hostile artifact log fields without echoing their values', () => { const canary = `claude-secret-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => { logs.push(JSON.stringify(values)); }; try { const before = claudeLoggingDiagnostics().violationCount; claudeLog('artifact.verify.completed', { signingKeyId: 'kogg-claude-artifact-v1', fileCount: canary, rawManifest: canary } as never); assert.equal(claudeLoggingDiagnostics().violationCount, before + 1); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
function approvalFields() { return { schema: 'kogg.claude-commercial-use-approval/v1', packageName: '@anthropic-ai/claude-agent-sdk', packageVersion: '0.3.246', npmIntegritySha512: 'FtR0HoHHNqeqJWjZN8qLUAzZVFUI9ztXYNPPwv98Ecmv9qq2QTauI8IzkY26CC0mleWAqb9RQEW2C0OtiUliug==', tarballSha1: '0009206e79ee0ae25f68ebb526584031cb5db048', approvedProduct: 'kogg', approvedUse: 'governed-agent-adapter', approverRef: 'release-authority', decidedAt: '2026-08-27T00:00:00.000Z', expiresAt: '2026-09-27T00:00:00.000Z', signingKeyId: 'kogg-claude-commercial-approval-v1' }; }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; return JSON.stringify(value); }
