import type { OpaqueCredentialLease } from '@kogg/agents/lib/common/agents-protocol';
import type { ClaudeSafeCode, GovernedClaudeAttemptV1 } from '../common/claude-protocol';
import { claudeLog } from './claude-logger';

// The shared lease and broker secret remain behind this gate. The runtime owner receives only frozen binding metadata and opaque reservation identity.
// diagnostic-coverage: claude.authority, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
const ID = /^[a-z0-9][a-z0-9._:-]{0,127}$/u; const SHA256 = /^[0-9a-f]{64}$/u; const MAX_REQUESTS = 64;
export interface ClaudeCredentialBindingV1 { readonly schemaVersion: '1'; readonly attemptId: string; readonly authorityDigest: string; readonly artifactManifestDigest: string; readonly legalApprovalDigest: string; readonly executionProfileDigest: string; readonly provider: 'anthropic'; readonly model: string; readonly requestDirection: 'anthropic-outbound'; readonly credentialLeaseId: string; readonly maximumRequestCount: number; readonly inputTokenCeiling: string; readonly outputTokenCeiling: string; readonly bytesInCeiling: string; readonly bytesOutCeiling: string; readonly expiresAt: string; }
export interface ClaudeCredentialActivationV1 { readonly reservationId: string; readonly processRegistrationId: string; readonly cgroupIdentityDigest: string; }
export interface ClaudeCredentialBrokerAuthority { reserve(binding: ClaudeCredentialBindingV1): Promise<{ readonly reservationId: string }>; activate(value: ClaudeCredentialActivationV1): Promise<void>; revoke(reservationId: string): Promise<void>; }
export interface ClaudeCredentialDiagnostics { readonly reserved: boolean; readonly active: boolean; readonly revoked: boolean; readonly failed: boolean; }
export class ClaudeCredentialFault extends Error { constructor(readonly code: Extract<ClaudeSafeCode, 'CLAUDE_CREDENTIAL_UNAVAILABLE' | 'CLAUDE_CREDENTIAL_REVOKED'>) { super(code); } }
export class ClaudeCredentialGrant {
  private reservationId: string | undefined; private reserved = false; private active = false; private revoked = false; private failed = false; private activationStarted = false; private reserving: Promise<void> | undefined; private revoking: Promise<void> | undefined; private disposed = false;
  readonly binding: ClaudeCredentialBindingV1;
  constructor(private readonly attempt: GovernedClaudeAttemptV1, private readonly lease: OpaqueCredentialLease, private readonly authority: ClaudeCredentialBrokerAuthority, private readonly now: () => number = Date.now) { try { this.binding = binding(attempt, lease, now()); } catch { /* observability-exempt: invalid opaque lease data is classified without logging its identity or contents. */ claudeLog('broker.reservation.failed', { attemptId: attempt.attemptId, safeCode: 'CLAUDE_CREDENTIAL_UNAVAILABLE' }); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE'); } }
  reserve(): Promise<void> { if (this.revoked || this.failed || this.revoking) return Promise.reject(new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE')); return this.reserving ??= this.reserveOnce(); }
  async activate(processRegistrationId: string, cgroupIdentityDigest: string): Promise<void> { if (!this.reserved || !this.reservationId || this.activationStarted || this.revoked || this.failed || !ID.test(processRegistrationId) || !SHA256.test(cgroupIdentityDigest) || Date.parse(this.binding.expiresAt) <= this.now()) return this.refuse(); this.activationStarted = true; claudeLog('broker.activation.requested', { attemptId: this.attempt.attemptId, processId: processRegistrationId }); try { this.lease.consume(); await this.authority.activate({ reservationId: this.reservationId, processRegistrationId, cgroupIdentityDigest }); this.active = true; claudeLog('broker.activation.completed', { attemptId: this.attempt.attemptId, processId: processRegistrationId }); } catch { /* observability-exempt: private lease/broker errors are discarded behind the closed refusal and revocation events. */ this.failed = true; claudeLog('broker.activation.failed', { attemptId: this.attempt.attemptId, processId: processRegistrationId, safeCode: 'CLAUDE_CREDENTIAL_UNAVAILABLE' }); await this.revokeAfterFailure(); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE'); } }
  revoke(): Promise<void> { if (this.revoked) return Promise.resolve(); return this.revoking ??= this.revokeOnce(); }
  abandon(): void { if (this.revoked || this.reserved || this.active) return; if (this.reserving) { void this.revoke().catch(() => { /* observability-exempt: revokeOnce emits the closed asynchronous revocation failure and disposes the lease. */ return; }); return; } this.revoked = true; this.dispose(); claudeLog('broker.revoked', { attemptId: this.attempt.attemptId }); }
  diagnostics(): ClaudeCredentialDiagnostics { return { reserved: this.reserved, active: this.active, revoked: this.revoked, failed: this.failed }; }
  private async reserveOnce(): Promise<void> { claudeLog('broker.reservation.requested', { attemptId: this.attempt.attemptId, provider: this.binding.provider, model: this.binding.model }); try { const result = await this.authority.reserve(this.binding); if (!result || Object.keys(result).join(',') !== 'reservationId' || !ID.test(result.reservationId)) throw new Error('invalid reservation'); this.reservationId = result.reservationId; this.reserved = true; claudeLog('broker.reservation.completed', { attemptId: this.attempt.attemptId, provider: this.binding.provider, model: this.binding.model }); } catch { /* observability-exempt: broker errors and credential material are discarded behind the closed refusal. */ this.failed = true; this.revoked = true; this.dispose(); claudeLog('broker.reservation.failed', { attemptId: this.attempt.attemptId, safeCode: 'CLAUDE_CREDENTIAL_UNAVAILABLE' }); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE'); } }
  private async revokeOnce(): Promise<void> { try { if (this.reserving) await this.reserving; if (this.reservationId) await this.authority.revoke(this.reservationId); this.revoked = true; this.active = false; claudeLog('broker.revoked', { attemptId: this.attempt.attemptId }); } catch (error) { /* observability-exempt: broker errors are normalized and the shared opaque lease is disposed in finally; an earlier reserve fault keeps its closed classification. */ if (error instanceof ClaudeCredentialFault && error.code === 'CLAUDE_CREDENTIAL_UNAVAILABLE') throw error; this.failed = true; claudeLog('broker.revoke.failed', { attemptId: this.attempt.attemptId, safeCode: 'CLAUDE_CREDENTIAL_REVOKED' }); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_REVOKED'); } finally { this.dispose(); } }
  private async refuse(): Promise<never> { this.failed = true; await this.revokeAfterFailure(); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE'); }
  private async revokeAfterFailure(): Promise<void> { try { await this.revoke(); } catch { /* observability-exempt: revocation emitted the secondary closed failure; activation refusal remains primary. */ return; } }
  private dispose(): void { if (!this.disposed) { this.disposed = true; this.lease.dispose(); } }
}
function binding(attempt: GovernedClaudeAttemptV1, lease: OpaqueCredentialLease, now: number): ClaudeCredentialBindingV1 { const leaseExpiry = Date.parse(lease.expiresAt); if (!ID.test(lease.leaseId) || !Number.isFinite(leaseExpiry) || leaseExpiry <= now || !Number.isSafeInteger(attempt.deadlines.absoluteMs) || attempt.deadlines.absoluteMs < 1) { lease.dispose(); throw new ClaudeCredentialFault('CLAUDE_CREDENTIAL_UNAVAILABLE'); } const expiresAt = new Date(Math.min(leaseExpiry, now + attempt.deadlines.absoluteMs)).toISOString(); return Object.freeze({ schemaVersion: '1', attemptId: attempt.attemptId, authorityDigest: attempt.authorityDigest, artifactManifestDigest: attempt.artifactManifestDigest, legalApprovalDigest: attempt.legalApprovalDigest, executionProfileDigest: attempt.executionProfileDigest, provider: attempt.provider, model: attempt.model, requestDirection: 'anthropic-outbound', credentialLeaseId: lease.leaseId, maximumRequestCount: MAX_REQUESTS, inputTokenCeiling: attempt.budgets.inputTokens, outputTokenCeiling: attempt.budgets.outputTokens, bytesInCeiling: attempt.budgets.bytesIn, bytesOutCeiling: attempt.budgets.bytesOut, expiresAt }); }
