import type { KoggDiagnosticCheck, KoggDiagnosticContributor } from '@kogg/contracts'; import { inject, injectable } from '@theia/core/shared/inversify'; import { ClaudeArtifactRegistry } from './claude-artifact-registry'; import { claudeLog, claudeLoggingDiagnostics } from './claude-logger'; import { ClaudeRecoveryRegistry } from './claude-recovery-registry'; import { claudeSourceMapDiagnostics } from './claude-source-map-diagnostics';
// Logs through the closed [kogg:claude:artifact] claudeLog schema.
// diagnostic-coverage: claude.artifact, claude.legal, claude.settings, claude.protocol, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
export const CLAUDE_CHECKS = ['artifact','legal','settings','protocol','credentials','processes','cleanup','recovery','source-maps'].map(value => `claude.${value}`) as readonly string[];
@injectable()
export class ClaudeDiagnosticContributor implements KoggDiagnosticContributor { readonly id = 'claude'; constructor(@inject(ClaudeArtifactRegistry) private readonly artifacts: ClaudeArtifactRegistry, @inject(ClaudeRecoveryRegistry) private readonly recovery: ClaudeRecoveryRegistry) {} async diagnose(): Promise<readonly KoggDiagnosticCheck[]> { try { await Promise.all([this.artifacts.onStart(), this.recovery.onStart()]); const value = this.artifacts.projection(); const runtime = this.recovery.projection(); const logging = claudeLoggingDiagnostics(); const sourceMaps = claudeSourceMapDiagnostics(); return [
    { id: 'claude.artifact', status: value.artifactVerified ? 'pass' : 'fail', summary: value.artifactVerified ? 'The exact signed Claude artifact is verified.' : 'No exact signed Claude artifact is verified.', details: { safeCode: value.safeCode } },
    { id: 'claude.legal', status: value.legalApproved ? 'pass' : 'fail', summary: value.legalApproved ? 'Commercial-use approval is current and exact.' : 'Commercial-use approval is absent, expired, mismatched, or invalid.', details: { safeCode: value.safeCode } },
    { id: 'claude.settings', status: 'fail', summary: 'Effective Claude settings have not been qualified.', details: { safeCode: value.safeCode } },
    { id: 'claude.protocol', status: 'fail', summary: 'The Claude SDK protocol has not been qualified.', details: { safeCode: value.safeCode } },
    { id: 'claude.credentials', status: value.credentialBrokerReady ? 'pass' : 'fail', summary: value.credentialBrokerReady ? 'The Claude credential broker is ready.' : 'The Claude credential broker is unavailable.', details: { safeCode: value.safeCode } },
    { id: 'claude.processes', status: runtime.ownerReady && runtime.residualCount === 0 ? 'pass' : 'fail', summary: runtime.ownerReady && runtime.residualCount === 0 ? 'The qualified Claude owner reports no hidden or residual process.' : 'The qualified Claude process inventory is unavailable or residual.', details: { ownerReady: runtime.ownerReady, processCount: runtime.processCount, residualCount: runtime.residualCount, safeCode: runtime.safeCode } },
    { id: 'claude.cleanup', status: runtime.ownerReady && runtime.residualCount === 0 && runtime.cleanupFailureCount === 0 ? 'pass' : 'fail', summary: runtime.ownerReady && runtime.residualCount === 0 && runtime.cleanupFailureCount === 0 ? 'Claude cleanup has zero residuals or failures.' : 'Claude cleanup authority is unavailable or reports residuals/failures.', details: { ownerReady: runtime.ownerReady, residualCount: runtime.residualCount, cleanupFailureCount: runtime.cleanupFailureCount, safeCode: runtime.safeCode } },
    { id: 'claude.recovery', status: runtime.ownerReady && runtime.recoveryComplete && runtime.recoveryBacklog === 0 && runtime.residualCount === 0 ? 'pass' : 'fail', summary: runtime.ownerReady && runtime.recoveryComplete && runtime.recoveryBacklog === 0 && runtime.residualCount === 0 ? 'Claude startup reconciliation is complete.' : 'Claude startup reconciliation is unavailable, incomplete, or blocked.', details: { ownerReady: runtime.ownerReady, recoveryBacklog: runtime.recoveryBacklog, residualCount: runtime.residualCount, safeCode: runtime.safeCode } },
    { id: 'claude.source-maps', status: value.sourceMapsPresent && sourceMaps.missingCount === 0 && logging.violationCount === 0 ? 'pass' : 'fail', summary: value.sourceMapsPresent && sourceMaps.missingCount === 0 && logging.violationCount === 0 ? 'Every Claude adapter failure boundary has a debugger source map and closed logging schema.' : 'Claude source-map or logging-schema reachability failed.', details: { ...sourceMaps, ...logging } }
  ]; } catch (error) { /* observability-exempt: claudeLog emits the sanitized diagnostics failure without sensitive error text. */ claudeLog('diagnostics.failure', { errorType: error instanceof Error ? error.name : 'UnknownError' }); return CLAUDE_CHECKS.map(id => ({ id, status: 'fail' as const, summary: 'Claude adapter diagnostics could not run.' })); } } }
