import assert from 'node:assert/strict'; import test from 'node:test';
import type { AgentAdapterFactory, AgentAdapterSession } from '@kogg/agents/lib/common/agents-protocol'; import { AdapterRegistry } from '@kogg/agents/lib/node/adapter-registry';
import type { ClaudeArtifactManifestV1, ClaudeCommercialUseApprovalV1 } from '../common/claude-protocol'; import { ClaudeAdapterFactory } from './claude-adapter-factory'; import { ClaudeArtifactRegistry, type AttestedClaudeArtifactV1 } from './claude-artifact-registry'; import { ClaudeRecoveryRegistry } from './claude-recovery-registry'; import { ClaudeRuntimeAuthorityFault, ClaudeRuntimeAuthorityRegistry, type QualifiedClaudeRuntimeAuthority } from './claude-runtime-authority';
// diagnostic-coverage: claude.artifact, claude.confinement, claude.settings, claude.protocol, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
const approval = Object.freeze({ schema: 'kogg.claude-commercial-use-approval/v1', packageName: '@anthropic-ai/claude-agent-sdk', packageVersion: '0.3.246', npmIntegritySha512: 'FtR0HoHHNqeqJWjZN8qLUAzZVFUI9ztXYNPPwv98Ecmv9qq2QTauI8IzkY26CC0mleWAqb9RQEW2C0OtiUliug==', tarballSha1: '0009206e79ee0ae25f68ebb526584031cb5db048', approvedProduct: 'kogg', approvedUse: 'governed-agent-adapter', approverRef: 'release-authority', decidedAt: '2026-08-27T00:00:00.000Z', expiresAt: '2026-09-27T00:00:00.000Z', signingKeyId: 'kogg-claude-commercial-approval-v1', signature: 'signed' } as ClaudeCommercialUseApprovalV1);
const manifest = Object.freeze({ schema: 'kogg.claude-artifact/v1', packageName: approval.packageName, packageVersion: approval.packageVersion, npmIntegritySha512: approval.npmIntegritySha512, tarballSha1: approval.tarballSha1, fileDigests: Object.freeze({ 'package.tgz': '1'.repeat(64) }), bundledCliVersion: '2.1.0', typeProjectionSha256: '2'.repeat(64), adapterSchemaSha256: '3'.repeat(64), createdAt: '2026-08-27T00:00:00.000Z', signingKeyId: 'kogg-claude-artifact-v1', signature: 'signed' } as ClaudeArtifactManifestV1);
const artifact = Object.freeze({ manifest, manifestDigest: 'a'.repeat(64), approvalDigest: 'b'.repeat(64), root: '/private/claude', files: Object.freeze({ 'package.tgz': '/private/claude/package.tgz' }) } as AttestedClaudeArtifactV1);
const artifacts = { onStart: async () => undefined, attestedArtifact: () => artifact, qualifiedApproval: () => approval, projection: () => ({ legalApproved: true, artifactVerified: false, confinementVerified: false, credentialBrokerReady: false, sourceMapsPresent: true, safeCode: 'CLAUDE_ARTIFACT_MISMATCH' }) } as ClaudeArtifactRegistry;
const input = { binding: { attemptId: 'attempt-1' } } as unknown as Parameters<AgentAdapterFactory['create']>[0]; const session: AgentAdapterSession = { resourceId: 'resource-1', resourceKind: 'provider-host', ownerKind: 'kogg', start: async () => undefined, cancel: async () => undefined, cleanup: async () => ({ residualCount: 0 }) };
function owner(overrides: Partial<QualifiedClaudeRuntimeAuthority> = {}): QualifiedClaudeRuntimeAuthority { return { qualify: async () => ({ artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: manifest.bundledCliVersion, executionProfileDigest: 'c'.repeat(64), artifactVerified: true, confinementVerified: true, credentialBrokerReady: true }), create: () => session, ...overrides }; }
test('fails closed without a qualified runtime owner after exact static attestation', async () => { const registry = new ClaudeRuntimeAuthorityRegistry(artifacts); await registry.onStart(); assert.equal(registry.projection().ownerReady, false); assert.equal(registry.projection().safeCode, 'CLAUDE_CONFINEMENT_UNAVAILABLE'); assert.throws(() => registry.create(input), error => error instanceof ClaudeRuntimeAuthorityFault && error.code === 'CLAUDE_CONFINEMENT_UNAVAILABLE'); });
test('rejects owner projections that do not bind both exact signed records', async () => { let creates = 0; const registry = new ClaudeRuntimeAuthorityRegistry(artifacts, owner({ qualify: async () => ({ artifactManifestDigest: 'd'.repeat(64), legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: manifest.bundledCliVersion, executionProfileDigest: 'c'.repeat(64), artifactVerified: true, confinementVerified: true, credentialBrokerReady: true }), create: () => { creates++; return session; } })); await registry.onStart(); assert.equal(registry.projection().ownerReady, false); assert.equal(creates, 0); assert.throws(() => registry.create(input), /CLAUDE_CONFINEMENT_UNAVAILABLE/u); });
test('retains an exact partial projection but refuses before broker readiness', async () => { const registry = new ClaudeRuntimeAuthorityRegistry(artifacts, owner({ qualify: async () => ({ artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: manifest.bundledCliVersion, executionProfileDigest: 'c'.repeat(64), artifactVerified: true, confinementVerified: true, credentialBrokerReady: false }) })); await registry.onStart(); assert.equal(registry.projection().ownerReady, true); assert.equal(registry.projection().safeCode, 'CLAUDE_CREDENTIAL_BROKER_UNAVAILABLE'); assert.throws(() => registry.create(input), /CLAUDE_CREDENTIAL_BROKER_UNAVAILABLE/u); });
test('enables the factory only after exact runtime and recovery qualification', async () => { let captured: AttestedClaudeArtifactV1 | undefined; const authority = new ClaudeRuntimeAuthorityRegistry(artifacts, owner({ create: value => { captured = value.artifact; return session; } })); const recovery = new ClaudeRecoveryRegistry({ reconcileStartup: async () => ({ processCount: 0, residualCount: 0, cleanupFailureCount: 0, recoveryBacklog: 0, recoveryComplete: true }) }); const adapters = new AdapterRegistry(); const factory = new ClaudeAdapterFactory(adapters, artifacts, recovery, authority); await Promise.all([factory.onStart(), factory.onStart()]); assert.equal(factory.descriptor.enabled, true); assert.equal(factory.create(input), session); assert.equal(captured, artifact); assert.equal(adapters.descriptors().length, 1); });
test('normalizes private session-owner failures without leaking them', async () => { const canary = `private-claude-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values)); try { const registry = new ClaudeRuntimeAuthorityRegistry(artifacts, owner({ create: () => { throw new Error(canary); } })); await registry.onStart(); assert.throws(() => registry.create(input), error => error instanceof ClaudeRuntimeAuthorityFault && error.code === 'CLAUDE_INTERNAL'); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
