import type { KoggDiagnosticCheck, KoggDiagnosticContributor } from '@kogg/contracts'; import { inject, injectable } from '@theia/core/shared/inversify'; import { ClaudeArtifactRegistry } from './claude-artifact-registry'; import { claudeLog, claudeLoggingDiagnostics } from './claude-logger'; import { claudeSourceMapDiagnostics } from './claude-source-map-diagnostics';
// Logs through the closed [kogg:claude:artifact] claudeLog schema.
// diagnostic-coverage: claude.artifact, claude.legal, claude.settings, claude.protocol, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
export const CLAUDE_CHECKS = ['artifact','legal','settings','protocol','credentials','processes','cleanup','recovery','source-maps'].map(value => `claude.${value}`) as readonly string[];
@injectable()
export class ClaudeDiagnosticContributor implements KoggDiagnosticContributor { readonly id = 'claude'; constructor(@inject(ClaudeArtifactRegistry) private readonly artifacts: ClaudeArtifactRegistry) {} async diagnose(): Promise<readonly KoggDiagnosticCheck[]> { try { await this.artifacts.onStart(); const value = this.artifacts.projection(); const logging = claudeLoggingDiagnostics(); const sourceMaps = claudeSourceMapDiagnostics(); return [
    { id: 'claude.artifact', status: value.artifactVerified ? 'pass' : 'fail', summary: value.artifactVerified ? 'The exact signed Claude artifact is verified.' : 'No exact signed Claude artifact is verified.', details: { safeCode: value.safeCode } },
    { id: 'claude.legal', status: value.legalApproved ? 'pass' : 'fail', summary: value.legalApproved ? 'Commercial-use approval is current and exact.' : 'Commercial-use approval is absent, expired, mismatched, or invalid.', details: { safeCode: value.safeCode } },
    { id: 'claude.settings', status: 'fail', summary: 'Effective Claude settings have not been qualified.', details: { safeCode: value.safeCode } },
    { id: 'claude.protocol', status: 'fail', summary: 'The Claude SDK protocol has not been qualified.', details: { safeCode: value.safeCode } },
    { id: 'claude.credentials', status: value.credentialBrokerReady ? 'pass' : 'fail', summary: value.credentialBrokerReady ? 'The Claude credential broker is ready.' : 'The Claude credential broker is unavailable.', details: { safeCode: value.safeCode } },
    { id: 'claude.processes', status: value.processCount === 0 && value.residualCount === 0 ? 'pass' : 'fail', summary: value.processCount === 0 && value.residualCount === 0 ? 'No hidden or residual Claude process exists.' : 'A Claude process is hidden or residual.', details: { processCount: value.processCount, residualCount: value.residualCount } },
    { id: 'claude.cleanup', status: value.residualCount === 0 ? 'pass' : 'fail', summary: value.residualCount === 0 ? 'Claude cleanup has zero residuals.' : 'Claude cleanup has residuals.', details: { residualCount: value.residualCount } },
    { id: 'claude.recovery', status: value.recoveryComplete && value.residualCount === 0 ? 'pass' : 'fail', summary: value.recoveryComplete && value.residualCount === 0 ? 'Claude recovery is complete.' : 'Claude recovery is incomplete.', details: { residualCount: value.residualCount } },
    { id: 'claude.source-maps', status: value.sourceMapsPresent && sourceMaps.missingCount === 0 && logging.violationCount === 0 ? 'pass' : 'fail', summary: value.sourceMapsPresent && sourceMaps.missingCount === 0 && logging.violationCount === 0 ? 'Every Claude adapter failure boundary has a debugger source map and closed logging schema.' : 'Claude source-map or logging-schema reachability failed.', details: { ...sourceMaps, ...logging } }
  ]; } catch (error) { /* observability-exempt: claudeLog emits the sanitized diagnostics failure without sensitive error text. */ claudeLog('diagnostics.failure', { errorType: error instanceof Error ? error.name : 'UnknownError' }); return CLAUDE_CHECKS.map(id => ({ id, status: 'fail' as const, summary: 'Claude adapter diagnostics could not run.' })); } } }
