import { BackendApplicationContribution } from '@theia/core/lib/node';
import { inject, injectable, optional } from '@theia/core/shared/inversify';
import type { AgentAdapterFactory, AgentAdapterSession } from '@kogg/agents/lib/common/agents-protocol';
import type { ClaudeCommercialUseApprovalV1, ClaudePermissionDecisionV1, ClaudePermissionRequestV1, ClaudeSafeCode, GovernedClaudeAttemptV1 } from '../common/claude-protocol';
import { ClaudeArtifactRegistry, type AttestedClaudeArtifactV1 } from './claude-artifact-registry';
import { ClaudeAttemptAuthorityRegistry } from './claude-attempt-authority';
import { ClaudeCredentialGrant, type ClaudeCredentialActivationV1, type ClaudeCredentialBindingV1 } from './claude-credential-grant';
import { claudeLog } from './claude-logger';
import { ClaudePermissionGate } from './claude-permission-gate';
import { ClaudeProcessHostGate, type ClaudeProcessAuthority, type ClaudeProcessIdentityV1, type ClaudeProcessInventoryV1, type ClaudeProcessReservationV1 } from './claude-process-host';
import { ClaudeSdkProtocolGate, type ClaudeContentDelivery } from './claude-sdk-protocol';

// The optional owner is the only boundary allowed to probe or execute the attested commercial runtime. Its projection contains identities and booleans only.
// diagnostic-coverage: claude.artifact, claude.authority, claude.confinement, claude.settings, claude.protocol, claude.credentials, claude.processes, claude.cleanup, claude.recovery, claude.source-maps
export const QualifiedClaudeRuntimeAuthority = Symbol('QualifiedClaudeRuntimeAuthority');
export interface QualifiedClaudeRuntimeProjection { readonly artifactManifestDigest: string; readonly legalApprovalDigest: string; readonly bundledCliVersion: string; readonly executionProfileDigest: string; readonly artifactVerified: boolean; readonly confinementVerified: boolean; readonly credentialBrokerReady: boolean; readonly settingsVerified: boolean; readonly protocolVerified: boolean; }
export interface QualifiedClaudeRuntimeAuthority {
  qualify(input: { readonly artifact: AttestedClaudeArtifactV1; readonly approval: ClaudeCommercialUseApprovalV1 }): Promise<QualifiedClaudeRuntimeProjection>;
  deliverContent(input: { readonly attempt: GovernedClaudeAttemptV1; readonly delivery: ClaudeContentDelivery }): Promise<void>;
  decidePermission(input: { readonly attempt: GovernedClaudeAttemptV1; readonly request: ClaudePermissionRequestV1 }): Promise<ClaudePermissionDecisionV1>;
  reserveCredentials(input: { readonly attempt: GovernedClaudeAttemptV1; readonly binding: ClaudeCredentialBindingV1 }): Promise<{ readonly reservationId: string }>;
  activateCredentials(input: { readonly attempt: GovernedClaudeAttemptV1; readonly activation: ClaudeCredentialActivationV1 }): Promise<void>;
  revokeCredentials(input: { readonly attempt: GovernedClaudeAttemptV1; readonly reservationId: string }): Promise<void>;
  reserveProcess(input: { readonly attempt: GovernedClaudeAttemptV1; readonly binding: ClaudeProcessReservationV1 }): Promise<{ readonly reservationId: string }>;
  registerProcess(input: { readonly attempt: GovernedClaudeAttemptV1; readonly reservationId: string; readonly processRegistrationId: string }): Promise<ClaudeProcessIdentityV1>;
  releaseProcess(input: { readonly attempt: GovernedClaudeAttemptV1; readonly identity: ClaudeProcessIdentityV1 }): Promise<void>;
  signalProcess(input: { readonly attempt: GovernedClaudeAttemptV1; readonly identity: ClaudeProcessIdentityV1; readonly signal: 'SIGTERM' | 'SIGKILL' }): Promise<void>;
  inventoryProcess(input: { readonly attempt: GovernedClaudeAttemptV1; readonly identity: ClaudeProcessIdentityV1 }): Promise<ClaudeProcessInventoryV1>;
  create(input: Omit<Parameters<AgentAdapterFactory['create']>[0], 'binding' | 'credentialLease' | 'operation'> & { readonly artifact: AttestedClaudeArtifactV1; readonly approval: ClaudeCommercialUseApprovalV1; readonly attempt: GovernedClaudeAttemptV1; readonly protocol: ClaudeSdkProtocolGate; readonly permissions: ClaudePermissionGate; readonly credentials: ClaudeCredentialGrant; readonly process: Pick<ClaudeProcessHostGate, 'phase' | 'reserve' | 'register' | 'release'> }): AgentAdapterSession;
}
export interface ClaudeRuntimeAuthorityProjection extends Partial<QualifiedClaudeRuntimeProjection> { readonly ownerReady: boolean; readonly safeCode: ClaudeSafeCode; }
const SHA256 = /^[0-9a-f]{64}$/u; const BLOCKED: ClaudeRuntimeAuthorityProjection = { ownerReady: false, artifactVerified: false, confinementVerified: false, credentialBrokerReady: false, settingsVerified: false, protocolVerified: false, safeCode: 'CLAUDE_ARTIFACT_MISMATCH' };

@injectable()
export class ClaudeRuntimeAuthorityRegistry implements BackendApplicationContribution {
  private startup: Promise<void> | undefined; private value: ClaudeRuntimeAuthorityProjection = BLOCKED;
  constructor(@inject(ClaudeArtifactRegistry) private readonly artifacts: ClaudeArtifactRegistry, @inject(ClaudeAttemptAuthorityRegistry) private readonly attempts: ClaudeAttemptAuthorityRegistry, @inject(QualifiedClaudeRuntimeAuthority) @optional() private readonly authority?: QualifiedClaudeRuntimeAuthority) {}
  onStart(): Promise<void> { return this.startup ??= this.qualify(); }
  projection(): ClaudeRuntimeAuthorityProjection { return this.value; }
  create(input: Parameters<AgentAdapterFactory['create']>[0]): AgentAdapterSession {
    if (!this.authority || !ready(this.value)) throw new ClaudeRuntimeAuthorityFault(this.value.safeCode);
    const artifact = this.artifacts.attestedArtifact(); const approval = this.artifacts.qualifiedApproval(); const attempt = this.attempts.authorize({ binding: input.binding, artifact, runtime: this.value }); const protocol = new ClaudeSdkProtocolGate(attempt.attemptId, attempt.model, artifact.manifest.bundledCliVersion, delivery => this.authority!.deliverContent({ attempt, delivery })); const permissions = new ClaudePermissionGate(attempt, request => this.authority!.decidePermission({ attempt, request })); const credentials = new ClaudeCredentialGrant(attempt, input.credentialLease, { reserve: binding => this.authority!.reserveCredentials({ attempt, binding }), activate: activation => this.authority!.activateCredentials({ attempt, activation }), revoke: reservationId => this.authority!.revokeCredentials({ attempt, reservationId }) }); const processAuthority: ClaudeProcessAuthority = { reserve: binding => this.authority!.reserveProcess({ attempt, binding }), register: (reservationId, processRegistrationId) => this.authority!.registerProcess({ attempt, reservationId, processRegistrationId }), release: identity => this.authority!.releaseProcess({ attempt, identity }), signal: (identity, signal) => this.authority!.signalProcess({ attempt, identity, signal }), inventory: identity => this.authority!.inventoryProcess({ attempt, identity }) }; const process = new ClaudeProcessHostGate(attempt, input.operation, credentials, processAuthority); claudeLog('session.create.requested', { attemptId: input.binding.attemptId, artifactManifestDigest: artifact.manifestDigest });
    try { const { binding: _binding, credentialLease: _credentialLease, operation: _operation, ...ownerInput } = input; const session = this.authority.create({ ...ownerInput, artifact, approval, attempt, protocol, permissions, credentials, process }); validateSession(session); process.arm(); claudeLog('session.create.completed', { attemptId: input.binding.attemptId, resourceId: session.resourceId }); return lifecycleBound(session, protocol, permissions, process); }
    catch { /* observability-exempt: Closed session creation failure discards owner errors; the unarmed gate cannot register work and cleanup never logs private authority data. */ void process.cleanup().catch(() => undefined); claudeLog('session.create.failed', { attemptId: input.binding.attemptId, safeCode: 'CLAUDE_INTERNAL' }); throw new ClaudeRuntimeAuthorityFault('CLAUDE_INTERNAL'); }
  }
  private async qualify(): Promise<void> {
    await this.artifacts.onStart(); let artifact: AttestedClaudeArtifactV1; let approval: ClaudeCommercialUseApprovalV1; try { artifact = this.artifacts.attestedArtifact(); approval = this.artifacts.qualifiedApproval(); }
    catch { /* observability-exempt: artifact registry already emitted the exact closed verification failure. */ this.value = { ...BLOCKED, safeCode: this.artifacts.projection().safeCode }; return; }
    claudeLog('authority.verify.started', { artifactManifestDigest: artifact.manifestDigest });
    if (!this.authority) { this.value = { ...BLOCKED, artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: artifact.manifest.bundledCliVersion, safeCode: 'CLAUDE_CONFINEMENT_UNAVAILABLE' }; claudeLog('authority.verify.failed', { artifactManifestDigest: artifact.manifestDigest, safeCode: this.value.safeCode }); return; }
    try { const inspected = await this.authority.qualify({ artifact, approval }); validateProjection(inspected, artifact); const safeCode: ClaudeSafeCode = !inspected.artifactVerified ? 'CLAUDE_ARTIFACT_MISMATCH' : !inspected.confinementVerified ? 'CLAUDE_CONFINEMENT_UNAVAILABLE' : !inspected.credentialBrokerReady ? 'CLAUDE_CREDENTIAL_BROKER_UNAVAILABLE' : !inspected.settingsVerified ? 'CLAUDE_INITIALIZATION_MISMATCH' : !inspected.protocolVerified ? 'CLAUDE_PROTOCOL_INVALID' : 'CLAUDE_OK'; this.value = { ...inspected, ownerReady: true, safeCode }; if (safeCode === 'CLAUDE_OK') claudeLog('authority.verify.completed', { artifactManifestDigest: inspected.artifactManifestDigest, executionProfileDigest: inspected.executionProfileDigest }); else claudeLog('authority.verify.failed', { artifactManifestDigest: inspected.artifactManifestDigest, safeCode }); }
    catch { /* observability-exempt: qualification errors and private owner state are discarded behind the closed authority failure. */ this.value = { ...BLOCKED, artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: artifact.manifest.bundledCliVersion, safeCode: 'CLAUDE_CONFINEMENT_UNAVAILABLE' }; claudeLog('authority.verify.failed', { artifactManifestDigest: artifact.manifestDigest, safeCode: this.value.safeCode }); }
  }
}
export class ClaudeRuntimeAuthorityFault extends Error { constructor(readonly code: ClaudeSafeCode) { super(code); } }
function ready(value: ClaudeRuntimeAuthorityProjection): boolean { return value.ownerReady && value.artifactVerified === true && value.confinementVerified === true && value.credentialBrokerReady === true && value.settingsVerified === true && value.protocolVerified === true && value.safeCode === 'CLAUDE_OK'; }
function validateProjection(value: QualifiedClaudeRuntimeProjection, artifact: AttestedClaudeArtifactV1): void { if (!value || Object.keys(value).sort().join(',') !== ['artifactManifestDigest','artifactVerified','bundledCliVersion','confinementVerified','credentialBrokerReady','executionProfileDigest','legalApprovalDigest','protocolVerified','settingsVerified'].sort().join(',') || value.artifactManifestDigest !== artifact.manifestDigest || value.legalApprovalDigest !== artifact.approvalDigest || value.bundledCliVersion !== artifact.manifest.bundledCliVersion || !SHA256.test(value.executionProfileDigest) || ![value.artifactVerified,value.confinementVerified,value.credentialBrokerReady,value.settingsVerified,value.protocolVerified].every(item => typeof item === 'boolean')) throw new Error('Invalid Claude runtime authority projection'); }
function validateSession(value: AgentAdapterSession): void { if (!value || typeof value.resourceId !== 'string' || !value.resourceId || value.resourceId.length > 128 || !['provider-host','provider-request'].includes(value.resourceKind) || value.ownerKind !== 'kogg' || typeof value.start !== 'function' || typeof value.cancel !== 'function' || typeof value.cleanup !== 'function') throw new Error('Invalid Claude adapter session'); }
function lifecycleBound(session: AgentAdapterSession, protocol: ClaudeSdkProtocolGate, permissions: ClaudePermissionGate, process: ClaudeProcessHostGate): AgentAdapterSession { const prepare = () => { permissions.close(); protocol.beginCleanup(); }; const settle = async (owner: () => Promise<unknown>): Promise<unknown> => { prepare(); let ownerFailure: unknown; let result: unknown; try { result = await owner(); } catch (error) { /* observability-exempt: The qualified owner must emit its closed SDK failure; Kogg still completes external and logical process cleanup. */ ownerFailure = error; } try { await process.cleanup(); } catch (error) { /* observability-exempt: Process cleanup emitted its closed failure; an earlier owner failure remains primary. */ if (!ownerFailure) ownerFailure = error; } if (ownerFailure) throw ownerFailure; return result; }; return { resourceId: session.resourceId, resourceKind: session.resourceKind, ownerKind: session.ownerKind, async start() { try { await session.start(); } catch (error) { try { await settle(() => session.cleanup()); } catch { /* observability-exempt: Owner and process cleanup emitted their closed failures; startup failure remains primary. */ } throw error; } }, async cancel(reason) { await settle(() => session.cancel(reason)); }, async cleanup() { return await settle(() => session.cleanup()) as { readonly residualCount: number }; } }; }
