import assert from 'node:assert/strict'; import { createHash } from 'node:crypto'; import test from 'node:test';
import type { AgentAdapterFactory } from '@kogg/agents/lib/common/agents-protocol'; import type { GovernedClaudeAttemptV1 } from '../common/claude-protocol'; import type { AttestedClaudeArtifactV1 } from './claude-artifact-registry'; import { ClaudeAttemptAuthorityFault, ClaudeAttemptAuthorityRegistry, type QualifiedClaudeAttemptAuthority } from './claude-attempt-authority'; import type { ClaudeRuntimeAuthorityProjection } from './claude-runtime-authority';
// diagnostic-coverage: claude.authority, claude.settings, claude.protocol, claude.credentials, claude.confinement, claude.source-maps
const binding = { schemaVersion: '1', attemptId: '20000000-0000-4000-8000-000000000001', taskId: 'task-1', projectId: 'project-1', repositoryId: 'repository-1', repositoryBindingRevision: '1', specificationId: 'specification-1', approvalId: 'approval-1', runId: 'run-1', roleRevisionId: 'role-1', deadlinePolicyId: 'interactive-v1', providerId: 'anthropic', modelId: 'claude-sonnet-4-20250514', worktreeId: '20000000-0000-4000-8000-000000000002' } as Parameters<AgentAdapterFactory['create']>[0]['binding'];
const artifact = { manifestDigest: 'a'.repeat(64), approvalDigest: 'b'.repeat(64) } as AttestedClaudeArtifactV1;
const runtime: ClaudeRuntimeAuthorityProjection = { ownerReady: true, artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, bundledCliVersion: '2.1.0', executionProfileDigest: 'c'.repeat(64), artifactVerified: true, confinementVerified: true, credentialBrokerReady: true, safeCode: 'CLAUDE_OK' };
function attempt(overrides: Record<string, unknown> = {}): GovernedClaudeAttemptV1 { const unsigned = { schemaVersion: '1', attemptId: binding.attemptId, taskRevisionDigest: 'd'.repeat(64), repositoryBindingDigest: 'e'.repeat(64), privateRepoObjectId: binding.worktreeId!, baseCommit: 'f'.repeat(40), role: 'implementation', provider: 'anthropic', model: binding.modelId, artifactManifestDigest: artifact.manifestDigest, legalApprovalDigest: artifact.approvalDigest, permissionProfileDigest: '9'.repeat(64), executionProfileDigest: runtime.executionProfileDigest!, budgets: { inputTokens: '1000', outputTokens: '500', toolCalls: '20', bytesIn: '100000', bytesOut: '100000' }, deadlines: { spawnMs: 10000, initializeMs: 30000, firstProgressMs: 60000, idleMs: 120000, permissionDecisionMs: 60000, interruptReceiptMs: 5000, gracefulExitMs: 10000, terminateMs: 5000, killMs: 5000, closeMs: 5000, cgroupEmptyMs: 10000, absoluteMs: 600000 }, ...overrides }; return { ...unsigned, authorityDigest: createHash('sha256').update(canonical(unsigned)).digest('hex') } as GovernedClaudeAttemptV1; }
function registry(resolve: () => GovernedClaudeAttemptV1 = () => attempt()): ClaudeAttemptAuthorityRegistry { return new ClaudeAttemptAuthorityRegistry({ authorize: resolve } as QualifiedClaudeAttemptAuthority); }
function authorize(value: ClaudeAttemptAuthorityRegistry): GovernedClaudeAttemptV1 { return value.authorize({ binding, artifact, runtime }); }
function rejects(value: GovernedClaudeAttemptV1): void { assert.throws(() => authorize(registry(() => value)), error => error instanceof ClaudeAttemptAuthorityFault && error.code === 'CLAUDE_ATTEMPT_INVALID'); }
test('requires a qualified attempt owner and retains an immutable exact authority', () => { assert.equal(new ClaudeAttemptAuthorityRegistry().projection().ownerReady, false); assert.throws(() => authorize(new ClaudeAttemptAuthorityRegistry()), /CLAUDE_ATTEMPT_INVALID/u); const value = authorize(registry()); assert.deepEqual(value, attempt()); assert.equal(Object.isFrozen(value), true); assert.equal(Object.isFrozen(value.budgets), true); assert.equal(Object.isFrozen(value.deadlines), true); });
test('rejects authority records not bound to the exact artifact, runtime, model, or private repository object', () => { rejects(attempt({ artifactManifestDigest: '0'.repeat(64) })); rejects(attempt({ legalApprovalDigest: '0'.repeat(64) })); rejects(attempt({ executionProfileDigest: '0'.repeat(64) })); rejects(attempt({ model: 'claude-sonnet-latest' })); rejects(attempt({ privateRepoObjectId: '20000000-0000-4000-8000-000000000003' })); });
test('rejects malformed budgets, deadlines, unknown fields, and authority digests', () => { rejects(attempt({ budgets: { inputTokens: '0', outputTokens: '500', toolCalls: '20', bytesIn: '100000', bytesOut: '100000' } })); rejects(attempt({ deadlines: { ...attempt().deadlines, spawnMs: 9999 } })); rejects(attempt({ extra: 'untrusted' })); rejects({ ...attempt(), authorityDigest: '0'.repeat(64) }); });
test('normalizes private authority failures without logging their contents', () => { const canary = `private-attempt-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values)); try { assert.throws(() => authorize(registry(() => { throw new Error(canary); })), /CLAUDE_ATTEMPT_INVALID/u); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; return JSON.stringify(value); }
