import assert from 'node:assert/strict'; import test from 'node:test'; import { CLAUDE_PROTOCOL_LIMITS, ClaudeProtocolFault, ClaudeSdkProtocolGate, type ClaudeContentDelivery } from './claude-sdk-protocol';
// diagnostic-coverage: claude.settings, claude.protocol, claude.cleanup, claude.source-maps
const attemptId = '30000000-0000-4000-8000-000000000001'; const model = 'claude-sonnet-4-20250514'; const cliVersion = '2.1.0';
const initialization = { type: 'system', subtype: 'init', model, permissionMode: 'default', tools: ['Bash','Edit','Glob','Grep','Read','Write'], mcpServers: [], plugins: [], slashCommands: [], agents: [], accountOrganizationPresent: false, cliVersion };
function gate(deliveries: ClaudeContentDelivery[] = []): ClaudeSdkProtocolGate { return new ClaudeSdkProtocolGate(attemptId, model, cliVersion, async delivery => { deliveries.push(delivery); }); }
async function rejects(value: Promise<unknown>, code: ClaudeProtocolFault['code']): Promise<void> { await assert.rejects(value, error => error instanceof ClaudeProtocolFault && error.code === code); }
test('accepts one exact initialization, routes volatile content, and observes one terminal result', async () => { const deliveries: ClaudeContentDelivery[] = []; const protocol = gate(deliveries); assert.deepEqual(await protocol.accept(initialization, 256), { kind: 'initialized' }); assert.deepEqual(await protocol.accept({ type: 'assistant', content: { private: 'not logged' }, contentBytes: 24 }, 128), { kind: 'progress', progressClass: 'assistant' }); assert.deepEqual(await protocol.accept({ type: 'command_lifecycle', state: 'started' }, 64), { kind: 'progress', progressClass: 'command-started' }); assert.deepEqual(await protocol.accept({ type: 'result', outcome: 'success', model }, 64), { kind: 'result', outcome: 'success' }); await protocol.drain(); protocol.end(); assert.deepEqual(deliveries, [{ sequence: 1, content: { private: 'not logged' }, byteCount: 24 }]); assert.equal(protocol.phase(), 'terminal-observed'); });
test('rejects fallback models and every initialization capability expansion', async () => { await rejects(gate().accept({ ...initialization, model: 'claude-sonnet-latest' }, 128), 'CLAUDE_INITIALIZATION_MISMATCH'); for (const mutation of [{ tools: [...initialization.tools, 'Task'] }, { mcpServers: ['server'] }, { plugins: ['plugin'] }, { slashCommands: ['/future'] }, { agents: ['agent'] }, { accountOrganizationPresent: true }, { cliVersion: 'latest' }, { permissionMode: 'bypassPermissions' }]) await rejects(gate().accept({ ...initialization, ...mutation }, 128), 'CLAUDE_INITIALIZATION_MISMATCH'); await rejects(gate().accept({ ...initialization, extra: true }, 128), 'CLAUDE_PROTOCOL_INVALID'); const protocol = gate(); await protocol.accept(initialization, 128); await rejects(protocol.accept({ type: 'result', outcome: 'success', model: 'claude-opus-4-20250514' }, 64), 'CLAUDE_MODEL_MISMATCH'); });
test('rejects unknown, out-of-order, duplicate-terminal, and oversized observations', async () => { await rejects(gate().accept({ type: 'assistant', content: 'private', contentBytes: 7 }, 64), 'CLAUDE_PROTOCOL_INVALID'); await rejects(gate().accept({ type: 'future' }, 64), 'CLAUDE_PROTOCOL_INVALID'); assert.throws(() => gate().accept(initialization, CLAUDE_PROTOCOL_LIMITS.frameBytes + 1), error => error instanceof ClaudeProtocolFault && error.code === 'CLAUDE_PROTOCOL_OVERFLOW'); const duplicate = gate(); await duplicate.accept(initialization, 64); await duplicate.accept({ type: 'result', outcome: 'success', model }, 64); await rejects(duplicate.accept({ type: 'result', outcome: 'success', model }, 64), 'CLAUDE_PROTOCOL_INVALID'); const incomplete = gate(); await incomplete.accept(initialization, 64); assert.throws(() => incomplete.end(), /CLAUDE_PROTOCOL_INVALID/u); });
test('fails closed on volatile content consumer errors without leaking them', async () => { const canary = `private-sdk-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values)); try { const protocol = new ClaudeSdkProtocolGate(attemptId, model, cliVersion, async () => { throw new Error(canary); }); await protocol.accept(initialization, 64); await rejects(protocol.accept({ type: 'assistant', content: canary, contentBytes: canary.length }, 64), 'CLAUDE_PROTOCOL_OVERFLOW'); assert.equal(logs.join('\n').includes(canary), false); } finally { console.error = original; } });
