import { ContainerModule } from '@theia/core/shared/inversify';
import { BackendApplicationContribution } from '@theia/core/lib/node';
import { KoggDiagnosticContribution, KernelBridgeToken } from '@kogg/contracts';
import { KernelBackendContribution } from './kernel-backend-contribution';
import { KernelBridgeImpl } from './kernel-bridge';
import { KernelDiagnosticContributor } from './kernel-diagnostic-contributor';
import { KernelTaskBindingService } from './kernel-task-binding-service';
import { KernelRepositoryStateAuthority } from './kernel-repository-state-authority';
import { KernelEvidenceAdmissionService } from './kernel-evidence-admission-service';
import { KernelGateEvaluationService } from './kernel-gate-evaluation-service';
import { KernelVerdictReadService } from './kernel-verdict-read-service';
import { RanexOperationsOwner } from './ranex-operations-owner';
import { CheckOperationsOwner } from './check-operations-owner';

export default new ContainerModule(bind => {
  bind(KernelBridgeImpl).toSelf().inSingletonScope();
  bind(KernelBridgeToken).toService(KernelBridgeImpl);
  bind(RanexOperationsOwner).toSelf().inSingletonScope();
  bind(BackendApplicationContribution).toService(RanexOperationsOwner);
  bind(CheckOperationsOwner).toSelf().inSingletonScope();
  bind(BackendApplicationContribution).toService(CheckOperationsOwner);
  bind(KernelBackendContribution).toSelf().inSingletonScope();
  bind(BackendApplicationContribution).toService(KernelBackendContribution);
  bind(KernelDiagnosticContributor).toSelf().inSingletonScope();
  bind(KoggDiagnosticContribution).toService(KernelDiagnosticContributor);
  bind(KernelTaskBindingService).toSelf().inSingletonScope();
  bind(KernelRepositoryStateAuthority).toSelf().inSingletonScope();
  bind(KernelEvidenceAdmissionService).toSelf().inSingletonScope();
  bind(KernelGateEvaluationService).toSelf().inSingletonScope();
  bind(KernelVerdictReadService).toSelf().inSingletonScope();
});
