import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';
import type { EditableWorkflowGraphV1, EditableWorkflowNodeV1 } from '../common/workflow-protocol';
import { workflowDigest } from '../common/workflow-canonical';
import { WorkflowCompiler } from './workflow-compiler';
import { WorkflowDiagnosticContributor, WORKFLOW_CHECKS } from './workflow-diagnostic-contributor';
import { WorkflowRegistry } from './workflow-registry';
import { WorkflowNodeCatalog } from './workflow-node-catalog';
import { OperationsReadModel } from '@kogg/operations/lib/node/operations-read-model';
import type { ModeOperationAuthorizer } from '@kogg/interaction-modes/lib/common/interaction-modes-protocol';
import type { AgentBindingAuthorizer, AgentSafeCode, AttemptProjectionV1, KoggAgentsService, StartAttemptRequestV1 } from '@kogg/agents/lib/common/agents-protocol';
import type { TaskAdmissionAuthority, TaskAdmissionSnapshot } from '@kogg/tasks/lib/common/tasks-protocol';
import { WorkflowExecutorRegistry, type WorkflowExternalExecutorAuthority, type WorkflowExternalExecutorContractV1 } from './workflow-executor-registry';

// diagnostic-coverage: workflow.schema, workflow.catalog, workflow.graph, workflow.anchors, workflow.authority, workflow.scheduler, workflow.processes, workflow.cleanup, workflow.recovery, workflow.accessibility, workflow.source-maps

const PROJECT = '10000000-0000-4000-8000-000000000001'; const TEMPLATE = '10000000-0000-4000-8000-000000000002'; const TASK = '10000000-0000-4000-8000-000000000003';
const REPOSITORY = '10000000-0000-4000-8000-000000000004';
const MODE_AUTHORITY: ModeOperationAuthorizer = {
  async authorizeOperation(request) {
    return { schemaVersion: 1, allowed: true, safeCode: 'MODE_OK', projection: { schemaVersion: 1, taskId: request.taskId, projectId: PROJECT, repositoryId: REPOSITORY, taskRevision: '1', selectedMode: 'kogg', effectiveCapabilities: ['workflow.run-governed'], sequence: '1', state: 'ready', activeStage: 'implementation', safeCode: 'MODE_OK' } };
  }
};
const AGENT_BINDING_AUTHORITY: AgentBindingAuthorizer = { async authorizeBinding() { return { allowed: true, code: 'AGENT_OK', registryRevision: '1' }; } };
const TASK_ADMISSION_AUTHORITY: TaskAdmissionAuthority = { async resolveAdmission(taskAdmissionId) { return taskAdmission(taskAdmissionId); } };

test('versions a validated graph immutably and compiles the policy-owned trust spine across restart', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-registry-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await registry.onStart(); const base = validGraph(); const group = { groupId: '20000000-0000-4000-8000-000000000004', memberNodeIds: base.nodes.map(node => node.nodeId), displayOrder: base.nodes.map(node => node.nodeId).reverse() }; const graph = { ...base, groups: [group] };
    const saved = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000001', templateId: TEMPLATE, expectedVersionNumber: 0, graph });
    assert.equal(saved.kind, 'completed'); assert.equal(saved.version?.versionNumber, 1); const firstDigest = saved.version!.graphDigest;
    const compiled = await registry.compile({ requestId: '20000000-0000-4000-8000-000000000002', versionId: saved.version!.versionId });
    assert.equal(compiled.kind, 'completed'); assert.equal(compiled.plan?.injectedAnchorCount, 9); assert.equal(compiled.plan?.graphDigest, firstDigest);
    assert.deepEqual(await registry.listProjectPlans(PROJECT), [{ planId: compiled.plan!.planId, versionId: saved.version!.versionId,
      templateId: TEMPLATE, versionNumber: 1, editableNodeCount: 2, injectedAnchorCount: 9 }]);
    assert.deepEqual(await registry.listProjectPlans('10000000-0000-4000-8000-000000000099'), []);
    await assert.rejects(registry.listProjectPlans('invalid-project-id'));
    const next = { ...graph, nodes: graph.nodes.map((node, index) => { if (index !== 0 || !node.configuration) return node; const configuration = { ...node.configuration, modelId: 'fixture.research-v2' }; return { ...node, configuration, configurationDigest: workflowDigest('node-configuration', configuration) }; }) };
    const savedNext = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000003', templateId: TEMPLATE, expectedVersionNumber: 1, graph: next });
    assert.equal(savedNext.kind, 'completed'); assert.equal(savedNext.version?.versionNumber, 2); assert.notEqual(savedNext.version?.graphDigest, firstDigest); assert.equal(compiled.plan?.graphDigest, firstDigest);
    await registry.onStop(); const durable = new DatabaseSync(database); const stored = durable.prepare('SELECT graph_json FROM template_versions WHERE version_id=?').get(saved.version!.versionId) as { graph_json: string }; assert.deepEqual((JSON.parse(stored.graph_json) as EditableWorkflowGraphV1).groups, [group]); durable.close(); const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await restarted.onStart(); const versions = await restarted.listVersions(TEMPLATE); assert.equal(versions.length, 2); assert.equal(versions[0]?.graphDigest, firstDigest);
    assert.deepEqual(await restarted.listProjectVersions(PROJECT), versions); assert.deepEqual(await restarted.listProjectVersions('10000000-0000-4000-8000-000000000099'), []);
    assert.equal((await restarted.listProjectPlans(PROJECT))[0]?.planId, compiled.plan!.planId);
    const diagnostics = await restarted.diagnostics(); assert.equal(diagnostics.canonicalMismatchCount, 0); assert.equal(diagnostics.catalogMismatchCount, 0); assert.equal(diagnostics.catalogEntryCount, 14); assert.equal(diagnostics.availableExecutorCount, 11); assert.equal(diagnostics.unavailableExecutorCount, 3); assert.equal(diagnostics.planMismatchCount, 0); assert.equal(diagnostics.residualProcessCount, 0);
    const checks = await new WorkflowDiagnosticContributor(restarted).diagnose(); const catalogCheck = checks.find(check => check.id === 'workflow.catalog'); assert.equal(catalogCheck?.status, 'fail'); assert.equal(catalogCheck?.details?.availableExecutorCount, 11); assert.equal(catalogCheck?.details?.unavailableExecutorCount, 3); assert.equal(checks.find(check => check.id === 'workflow.scheduler')?.status, 'pass'); assert.deepEqual(checks.find(check => check.id === 'workflow.accessibility')?.details, { editorViews: 2, sharedSemanticGraph: true }); assert.equal(checks.find(check => check.id === 'workflow.accessibility')?.status, 'pass'); await restarted.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('fails closed on forged anchors, cycles, ambiguous joins, widened authority, retries, and stale version writes', async () => {
  const compiler = workflowCompiler(); const forged = structuredClone(validGraph()) as unknown as { nodes: Array<Record<string, unknown>> }; forged.nodes[0]!.kind = 'anchor.controlled-merge'; assert.equal(compiler.validate(forged).code, 'WORKFLOW_ANCHOR_BYPASS');
  const cyclic = validGraph(); cyclic.edges.push(edge('40000000-0000-4000-8000-000000000003', cyclic.nodes[1]!.nodeId, cyclic.nodes[0]!.nodeId)); assert.equal(compiler.validate(cyclic).code, 'WORKFLOW_CYCLE');
  const base = validGraph(); const widened = { ...base, nodes: base.nodes.map((node, index) => index === 0 ? { ...node, requestedEffects: ['record-approval'] as const } : node) }; assert.equal(compiler.validate(widened).code, 'WORKFLOW_AUTHORITY_EXPANSION');
  const retryBase = validGraph(); const retried = { ...retryBase, nodes: retryBase.nodes.map((node, index) => index === 1 ? { ...node, retry: { maxAttempts: 2, backoffMs: 1000 as const, sideEffectPolicy: 'none' as const } } : node) }; assert.equal(compiler.validate(retried).code, 'WORKFLOW_AUTHORITY_EXPANSION');
  const joinBase = validGraph(); const extra = node('30000000-0000-4000-8000-000000000003', 'tool.build', ['read-repository','run-tool']); const ambiguous = { ...joinBase, nodes: [...joinBase.nodes, extra], edges: [...joinBase.edges, edge('40000000-0000-4000-8000-000000000004', extra.nodeId, joinBase.nodes[1]!.nodeId)] }; assert.equal(compiler.validate(ambiguous).code, 'WORKFLOW_JOIN_AMBIGUOUS');
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-conflict-')); try { const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, path.join(root, 'workflow.sqlite3')); await registry.onStart(); await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000010', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); const conflict = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000011', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); assert.equal(conflict.kind, 'conflict'); assert.equal(conflict.currentVersionNumber, 1); await registry.onStop(); } finally { await rm(root, { recursive: true, force: true }); }
});

test('validates closed node configuration digests, exact agent bindings, deadlines, conditions, and targets', () => {
  const compiler = workflowCompiler(); const base = validGraph(); const configuration = { schemaVersion: '1' as const, roleRevisionId: '60000000-0000-4000-8000-000000000001', providerId: 'kogg.fixture', modelId: 'fixture.echo', adapterKey: 'kogg.fixture', adapterVersion: '1.0.0', deadlinePolicyId: 'interactive-v1', absoluteDeadlineMs: 60_000, target: 'private-worktree' as const, condition: 'always' as const };
  const configured = { ...base, nodes: base.nodes.map((item, index) => index === 1 ? { ...item, configuration, configurationDigest: workflowDigest('node-configuration', configuration) } : item) };
  assert.equal(compiler.validate(configured).code, 'WORKFLOW_OK');
  const tampered = { ...configured, nodes: configured.nodes.map((item, index) => index === 1 ? { ...item, configuration: { ...configuration, modelId: 'fixture.other' } } : item) }; assert.equal(compiler.validate(tampered).code, 'WORKFLOW_SCHEMA_INVALID');
  const deadlineConfiguration = { ...configuration, absoluteDeadlineMs: 1_800_001 }; const deadline = { ...base, nodes: base.nodes.map((item, index) => index === 1 ? { ...item, configuration: deadlineConfiguration, configurationDigest: workflowDigest('node-configuration', deadlineConfiguration) } : item) }; assert.equal(compiler.validate(deadline).code, 'WORKFLOW_DEADLINE');
  const targetConfiguration = { ...configuration, target: 'project-read-only' as const }; const target = { ...base, nodes: base.nodes.map((item, index) => index === 1 ? { ...item, configuration: targetConfiguration, configurationDigest: workflowDigest('node-configuration', targetConfiguration) } : item) }; assert.equal(compiler.validate(target).code, 'WORKFLOW_TARGET_MISMATCH');
  const partial = { schemaVersion: '1' as const, providerId: 'kogg.fixture', absoluteDeadlineMs: 60_000, target: 'private-worktree' as const, condition: 'always' as const }; const partialGraph = { ...base, nodes: base.nodes.map((item, index) => index === 1 ? { ...item, configuration: partial, configurationDigest: workflowDigest('node-configuration', partial) } : item) }; assert.equal(compiler.validate(partialGraph).code, 'WORKFLOW_SCHEMA_INVALID');
  const externalBase = validGraph(); const checkConfiguration = { schemaVersion: '1' as const, checkId: 'suite.required-v1', externalConfigurationDigest: 'b'.repeat(64), absoluteDeadlineMs: 60_000, target: 'project-read-only' as const, condition: 'always' as const }; const checkNode = node('30000000-0000-4000-8000-000000000010', 'check.deterministic', ['read-repository','run-tool','record-check']); const external = { ...externalBase, nodes: [externalBase.nodes[0]!, { ...checkNode, configuration: checkConfiguration, configurationDigest: workflowDigest('node-configuration', checkConfiguration) }], edges: [edge('40000000-0000-4000-8000-000000000010', externalBase.nodes[0]!.nodeId, checkNode.nodeId)] }; assert.equal(compiler.validate(external).code, 'WORKFLOW_OK');
  const { externalConfigurationDigest: _digest, ...missingDigest } = checkConfiguration; const missing = { ...external, nodes: [external.nodes[0]!, { ...external.nodes[1]!, configuration: missingDigest, configurationDigest: workflowDigest('node-configuration', missingDigest) }] }; assert.equal(compiler.validate(missing).code, 'WORKFLOW_SCHEMA_INVALID');
  const { checkId: _checkId, ...checkBase } = checkConfiguration; const wrongBinding = { ...checkBase, operationId: 'build.repository-v1' }; const wrong = { ...external, nodes: [external.nodes[0]!, { ...external.nodes[1]!, configuration: wrongBinding, configurationDigest: workflowDigest('node-configuration', wrongBinding) }] }; assert.equal(compiler.validate(wrong).code, 'WORKFLOW_SCHEMA_INVALID');
});

test('refuses startup after immutable graph corruption and diagnostics fail as a complete catalog', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-integrity-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await registry.onStart(); await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000020', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); await registry.onStop();
    const corrupt = new DatabaseSync(database); corrupt.exec('DROP TRIGGER workflow_immutable_versions_update'); corrupt.prepare('UPDATE template_versions SET graph_json=?').run('{"schemaVersion":"1"}'); corrupt.close();
    const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await assert.rejects(restarted.onStart(), /WORKFLOW_STORE_INTEGRITY/u);
    const contributor = new WorkflowDiagnosticContributor({ diagnostics: async () => { throw new Error('prohibited-content-canary'); } } as unknown as WorkflowRegistry); const checks = await contributor.diagnose(); assert.deepEqual(checks.map(check => check.id), [...WORKFLOW_CHECKS]); assert.equal(checks.every(check => check.status === 'fail'), true); assert.equal(JSON.stringify(checks).includes('prohibited-content-canary'), false);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('binds every closed node kind to one canonical catalog digest while refusing unavailable external executors', () => {
  const catalog = new WorkflowNodeCatalog(new WorkflowExecutorRegistry()); const diagnostics = catalog.diagnostics();
  assert.equal(diagnostics.valid, true); assert.equal(diagnostics.entryCount, 14); assert.equal(diagnostics.availableExecutorCount, 11); assert.equal(diagnostics.unavailableExecutorCount, 3);
  assert.match(catalog.digest, /^[0-9a-f]{64}$/u); assert.deepEqual(catalog.entries.filter(entry => entry.executor.status === 'available').map(entry => entry.kind), ['approval.continue','approval.specification','control.condition','control.finally','control.group','control.join','control.parallel','implementation.agent','probe.agent','pseudocode.agent','research.agent']);
  assert.deepEqual(catalog.entry('implementation.agent').grantCeiling, ['invoke-provider','mutate-private-repository','read-repository','run-tool']);
});

test('refuses startup when an immutable template catalog binding is changed', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-catalog-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await registry.onStart(); await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000030', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); await registry.onStop();
    const corrupt = new DatabaseSync(database); corrupt.exec('DROP TRIGGER workflow_immutable_versions_update'); corrupt.prepare('UPDATE template_versions SET catalog_digest=?').run('f'.repeat(64)); corrupt.close();
    await assert.rejects(new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database).onStart(), /WORKFLOW_STORE_INTEGRITY/u);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('run admission validates the immutable plan and refuses unavailable executors before any run state exists', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-admission-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000040', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() });
    assert.equal(saved.kind, 'completed'); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await registry.compile({ requestId: '20000000-0000-4000-8000-000000000041', versionId: saved.version!.versionId });
    assert.equal(compiled.kind, 'completed'); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan');
    const request = { requestId: '20000000-0000-4000-8000-000000000042', planId: compiled.plan!.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000001' };
    const refused = await registry.admitRun(request); assert.deepEqual(refused, { kind: 'refused', code: 'WORKFLOW_EXECUTOR_INCOMPATIBLE' });
    assert.deepEqual(await registry.admitRun(request), refused);
    const mismatch = await registry.admitRun({ ...request, planId: '20000000-0000-4000-8000-000000000099' }); assert.equal(mismatch.code, 'WORKFLOW_SCHEMA_INVALID');
    const diagnostics = await registry.diagnostics(); assert.equal(diagnostics.versionCount, 1); assert.equal(diagnostics.planCount, 1); assert.equal(diagnostics.activeProcessCount, 0); assert.equal(diagnostics.recoveryBacklogCount, 0);
    await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('dispatches exact external catalog bindings through durable scheduler state', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-external-')); const database = path.join(root, 'workflow.sqlite3'); const calls: string[] = [];
  const authority: WorkflowExternalExecutorAuthority = { readiness: () => ({ ready: true, recoveryComplete: true, residualProcessCount: 0 }), attestations: externalContracts, async execute(request) { calls.push(request.bindingId); return { kind: 'completed', code: 'WORKFLOW_OK', output: 'success', subjectStateDigest: 'd'.repeat(64), factDigest: workflowDigest('run-snapshot', { bindingId: request.bindingId }), ownerSequence: String(calls.length), processCount: 1, residualProcessCount: 0 }; }, async cancel() { return { code: 'WORKFLOW_CANCELLED', processCount: 1, residualProcessCount: 0 }; } };
  const compiler = new WorkflowCompiler(new WorkflowNodeCatalog(new WorkflowExecutorRegistry(authority)));
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '2c000000-0000-4000-8000-000000000001', templateId: '1c000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph: externalGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected external workflow version');
    const compiled = await registry.compile({ requestId: '2c000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected external workflow plan');
    const completed = await registry.admitRun({ requestId: '2c000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000010' }); assert.equal(completed.kind, 'completed'); assert.equal(completed.run?.completedNodeCount, 3); assert.deepEqual(calls, ['git.status-v1','build.repository-v1','suite.required-v1']);
    const stored = new DatabaseSync(database); assert.equal((stored.prepare("SELECT count(*) AS count FROM workflow_outbox WHERE phase='completed'").get() as { count: number }).count, 3); assert.deepEqual((stored.prepare("SELECT subject_state_digest,fact_digest,owner_sequence FROM workflow_node_attempts ORDER BY owner_sequence").all() as Array<Record<string, unknown>>).map(row => ({ ...row })), calls.map((bindingId, index) => ({ subject_state_digest: 'd'.repeat(64), fact_digest: workflowDigest('run-snapshot', { bindingId }), owner_sequence: String(index + 1) }))); stored.close(); const diagnostics = await registry.diagnostics(); assert.equal(diagnostics.availableExecutorCount, 14); assert.equal(diagnostics.unavailableExecutorCount, 0); await registry.onStop();
    const corrupt = new DatabaseSync(database); corrupt.prepare("UPDATE workflow_node_attempts SET fact_digest='invalid' WHERE owner_sequence='3'").run(); corrupt.close(); const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await assert.rejects(restarted.onStart(), /WORKFLOW_STORE_INTEGRITY/u);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('run admission fails closed on missing, stale, or mutated task admission authority without run state', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-task-admission-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); let modeCalls = 0; let admission: TaskAdmissionSnapshot | undefined;
  const modeAuthority: ModeOperationAuthorizer = { async authorizeOperation(request) { modeCalls++; return MODE_AUTHORITY.authorizeOperation(request); } };
  const taskAuthority: TaskAdmissionAuthority = { async resolveAdmission() { return admission; } };
  try {
    const registry = new WorkflowRegistry(compiler, modeAuthority, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(taskAuthority); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '28000000-0000-4000-8000-000000000001', templateId: '18000000-0000-4000-8000-000000000003', expectedVersionNumber: 0, graph: controlGraph('always') }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable control workflow');
    const compiled = await registry.compile({ requestId: '28000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled control plan');
    const missing = await registry.admitRun({ requestId: '28000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000010' }); assert.deepEqual(missing, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' });
    const staleAdmissionId = '29000000-0000-4000-8000-000000000011'; admission = { ...taskAdmission(staleAdmissionId), expiresAt: '2026-08-27T00:00:00.000Z' };
    const stale = await registry.admitRun({ requestId: '28000000-0000-4000-8000-000000000004', planId: compiled.plan.planId, taskAdmissionId: staleAdmissionId }); assert.deepEqual(stale, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' });
    const mismatchedAdmissionId = '29000000-0000-4000-8000-000000000012'; admission = { ...taskAdmission(mismatchedAdmissionId), projectId: '10000000-0000-4000-8000-000000000099' };
    const mismatched = await registry.admitRun({ requestId: '28000000-0000-4000-8000-000000000005', planId: compiled.plan.planId, taskAdmissionId: mismatchedAdmissionId }); assert.deepEqual(mismatched, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' });
    const store = new DatabaseSync(database); assert.equal((store.prepare('SELECT count(*) AS count FROM workflow_runs').get() as { count: number }).count, 0); assert.equal((store.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 0); store.close(); assert.equal(modeCalls, 0); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('durably dispatches and idempotently completes an exact-attested control-only run with zero processes', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-control-run-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const projection = new OperationsReadModel(path.join(root, 'operations.sqlite3')); projection.start(); projection.registerOwner('workflow');
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); registry.setOwnerSink(projection); await registry.onStart(); const graph = controlGraph('always');
    const saved = await registry.saveVersion({ requestId: '24000000-0000-4000-8000-000000000001', templateId: '14000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable control workflow');
    const compiled = await registry.compile({ requestId: '24000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled control plan');
    const taskAdmissionId = '29000000-0000-4000-8000-000000000002'; const request = { requestId: '24000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId }; const completed = await registry.admitRun(request);
    assert.equal(completed.kind, 'completed'); assert.equal(completed.run?.runId, taskAdmissionId); assert.equal(completed.run?.taskAdmissionId, taskAdmissionId); assert.equal(completed.run?.state, 'completed'); assert.equal(completed.run?.completedNodeCount, 2); assert.equal(completed.run?.failedNodeCount, 0); assert.equal(projection.snapshot().runs.find(run => run.runId === completed.run?.runId)?.lifecycle, 'completed'); assert.deepEqual(await registry.admitRun(request), completed);
    const store = new DatabaseSync(database); const attestation = store.prepare('SELECT task_admission_id,task_admission_digest,task_id,repository_id,state,safe_code FROM workflow_runs').get() as { task_admission_id: string; task_admission_digest: string; task_id: string; repository_id: string; state: string; safe_code: string }; assert.deepEqual({ taskAdmissionId: attestation.task_admission_id, taskId: attestation.task_id, repositoryId: attestation.repository_id, state: attestation.state, safeCode: attestation.safe_code }, { taskAdmissionId, taskId: TASK, repositoryId: REPOSITORY, state: 'completed', safeCode: 'WORKFLOW_OK' }); assert.match(attestation.task_admission_digest, /^[0-9a-f]{64}$/u); assert.equal((store.prepare("SELECT count(*) AS count FROM workflow_node_attempts WHERE state='succeeded'").get() as { count: number }).count, 2); assert.equal((store.prepare("SELECT count(*) AS count FROM workflow_outbox WHERE phase='completed'").get() as { count: number }).count, 2); assert.deepEqual((store.prepare('SELECT event_name FROM workflow_scheduler_events ORDER BY sequence').all() as { event_name: string }[]).map(row => row.event_name), ['run.admitted','run.completed']); store.close(); await registry.onStop();
    const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); restarted.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); restarted.setOwnerSink(projection); await restarted.onStart(); assert.deepEqual(await restarted.admitRun(request), completed); const restartedStore = new DatabaseSync(database); assert.equal((restartedStore.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 2); restartedStore.close();
    const failingGraph = controlGraph('prior-success', true); const failedSaved = await restarted.saveVersion({ requestId: '24000000-0000-4000-8000-000000000004', templateId: '14000000-0000-4000-8000-000000000002', expectedVersionNumber: 0, graph: failingGraph }); if (failedSaved.kind !== 'completed' || !failedSaved.version) throw new Error('Expected immutable failing workflow');
    const failedCompiled = await restarted.compile({ requestId: '24000000-0000-4000-8000-000000000005', versionId: failedSaved.version.versionId }); if (failedCompiled.kind !== 'completed' || !failedCompiled.plan) throw new Error('Expected compiled failing plan');
    const failed = await restarted.admitRun({ requestId: '24000000-0000-4000-8000-000000000006', planId: failedCompiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000003' }); assert.equal(failed.kind, 'failed'); assert.equal(failed.code, 'WORKFLOW_CONDITION_INVALID'); assert.equal(failed.run?.state, 'failed'); assert.equal(projection.snapshot().runs.find(run => run.runId === failed.run?.runId)?.lifecycle, 'failed'); assert.equal((await restarted.diagnostics()).recoveryBacklogCount, 0); await restarted.onStop();
  } finally { projection.stop(); await rm(root, { recursive: true, force: true }); }
});

test('durably dispatches exact workflow agent bindings through the supervised agent registry', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-agent-run-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const fixture = agentDispatcher();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); registry.setAgentAttemptDispatcher(fixture.dispatcher); await registry.onStart(); const graph = agentGraph();
    const saved = await registry.saveVersion({ requestId: '2a000000-0000-4000-8000-000000000001', templateId: '1a000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable agent workflow');
    const compiled = await registry.compile({ requestId: '2a000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled agent workflow');
    const taskAdmissionId = '2a000000-0000-4000-8000-000000000003'; const completed = await registry.admitRun({ requestId: '2a000000-0000-4000-8000-000000000004', planId: compiled.plan.planId, taskAdmissionId });
    assert.equal(completed.kind, 'completed'); assert.equal(completed.run?.runId, taskAdmissionId); assert.equal(completed.run?.completedNodeCount, 1); assert.equal(fixture.starts.length, 1); const configuration = graph.nodes[0]!.configuration!; assert.deepEqual(fixture.starts[0], { schemaVersion: '1', requestId: fixture.starts[0]!.requestId, expectedRegistryRevision: '7', taskAdmissionId, workflowPlanDigest: compiled.plan.planDigest, roleRevisionId: configuration.roleRevisionId, providerId: configuration.providerId, modelId: configuration.modelId, adapterKey: configuration.adapterKey, adapterVersion: configuration.adapterVersion, deadlinePolicyId: configuration.deadlinePolicyId });
    const store = new DatabaseSync(database); const attempt = store.prepare('SELECT external_attempt_id,state,safe_code FROM workflow_node_attempts').get() as { external_attempt_id: string; state: string; safe_code: string }; assert.deepEqual({ ...attempt }, { external_attempt_id: fixture.attemptId, state: 'succeeded', safe_code: 'WORKFLOW_OK' }); assert.equal((store.prepare("SELECT count(*) AS count FROM workflow_outbox WHERE operation_kind='research.agent' AND phase='completed'").get() as { count: number }).count, 1); store.close(); assert.deepEqual(await registry.admitRun({ requestId: '2a000000-0000-4000-8000-000000000004', planId: compiled.plan.planId, taskAdmissionId }), completed); assert.equal(fixture.starts.length, 1); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('maps supervised agent refusal and residual cleanup to closed workflow failure state', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-agent-failure-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const fixture = agentDispatcher('CLEANUP_FAILED', 'cleanup_failed');
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); registry.setAgentAttemptDispatcher(fixture.dispatcher); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '2b000000-0000-4000-8000-000000000001', templateId: '1b000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph: agentGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable failing agent workflow'); const compiled = await registry.compile({ requestId: '2b000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled failing agent workflow');
    const failed = await registry.admitRun({ requestId: '2b000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: '2b000000-0000-4000-8000-000000000004' }); assert.equal(failed.kind, 'failed'); assert.equal(failed.code, 'WORKFLOW_CLEANUP_FAILED'); assert.equal(failed.run?.failedNodeCount, 1); const store = new DatabaseSync(database); assert.equal((store.prepare('SELECT state FROM workflow_node_attempts').get() as { state: string }).state, 'failed'); assert.equal((store.prepare('SELECT residual_process_count FROM workflow_runs').get() as { residual_process_count: number }).residual_process_count, 1); store.close(); assert.equal((await registry.diagnostics()).residualProcessCount, 1); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('routes a cleaned node failure through explicit remediation and preserves it across continuation restart', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-failure-route-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const fixture = agentDispatcher('PROVIDER_REFUSED', 'cleaned'); const graph = failureContinuationGraph();
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); first.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); first.setAgentAttemptDispatcher(fixture.dispatcher); await first.onStart();
    const saved = await first.saveVersion({ requestId: '2bb00000-0000-4000-8000-000000000001', templateId: '1bb00000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable failure-route workflow');
    const compiled = await first.compile({ requestId: '2bb00000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled failure-route workflow');
    const runId = '2bb00000-0000-4000-8000-000000000003'; const waiting = await first.admitRun({ requestId: '2bb00000-0000-4000-8000-000000000004', planId: compiled.plan.planId, taskAdmissionId: runId }); assert.equal(waiting.kind, 'waiting'); assert.equal(waiting.run?.failedNodeCount, 1); await first.onStop();
    const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); restarted.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); restarted.setAgentAttemptDispatcher(fixture.dispatcher); await restarted.onStart(); const nodeId = graph.nodes[1]!.nodeId; const sessionId = '2bb00000-0000-4000-8000-000000000005'; const review = await restarted.beginContinuationReview({ requestId: '2bb00000-0000-4000-8000-000000000006', runId, nodeId, sessionId }); if (review.kind !== 'completed') throw new Error('Expected continuation review');
    const completed = await restarted.continueRun({ requestId: '2bb00000-0000-4000-8000-000000000007', runId, nodeId, sessionId, challenge: review.challenge }); assert.equal(completed.kind, 'completed'); assert.equal(completed.run?.failedNodeCount, 1); assert.equal(completed.run?.completedNodeCount, 2); const store = new DatabaseSync(database); assert.deepEqual((store.prepare('SELECT state,output FROM workflow_node_attempts ORDER BY rowid').all() as { state: string; output: string }[]).map(row => [row.state,row.output]), [['failed','failure'],['succeeded','success'],['succeeded','success']]); store.close(); await restarted.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('executes specification approval only from the exact current task-admission witness', async () => {
  for (const mutateAtExecution of [false, true]) {
    const root = await mkdtemp(path.join(os.tmpdir(), `kogg-workflow-spec-approval-${mutateAtExecution}-`)); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); let resolutions = 0;
    const authority: TaskAdmissionAuthority = { async resolveAdmission(taskAdmissionId) { resolutions++; const admission = taskAdmission(taskAdmissionId); return mutateAtExecution && resolutions === 2 ? { ...admission, approvalId: '2e000000-0000-4000-8000-000000000099' } : admission; } };
    try {
      const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(authority); await registry.onStart(); const saved = await registry.saveVersion({ requestId: mutateAtExecution ? '2f000000-0000-4000-8000-000000000001' : '2e000000-0000-4000-8000-000000000001', templateId: mutateAtExecution ? '1f000000-0000-4000-8000-000000000001' : '1e000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph: approvalGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable specification approval workflow'); const compiled = await registry.compile({ requestId: mutateAtExecution ? '2f000000-0000-4000-8000-000000000002' : '2e000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled specification approval workflow');
      const result = await registry.admitRun({ requestId: mutateAtExecution ? '2f000000-0000-4000-8000-000000000003' : '2e000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: mutateAtExecution ? '2f000000-0000-4000-8000-000000000004' : '2e000000-0000-4000-8000-000000000004' }); assert.equal(resolutions, 2); assert.equal(result.kind, mutateAtExecution ? 'failed' : 'completed'); assert.equal(result.code, mutateAtExecution ? 'WORKFLOW_AUTHORITY_EXPANSION' : 'WORKFLOW_OK'); const store = new DatabaseSync(database); assert.equal((store.prepare('SELECT state FROM workflow_node_attempts').get() as { state: string }).state, mutateAtExecution ? 'failed' : 'succeeded'); store.close(); await registry.onStop();
    } finally { await rm(root, { recursive: true, force: true }); }
  }
});

test('durably suspends continuation approval across restart and resumes only from the exact reviewed challenge', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-continuation-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const graph = continuationGraph(); const runId = '2aa00000-0000-4000-8000-000000000004'; const continuationNodeId = graph.nodes[1]!.nodeId;
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); first.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await first.onStart();
    const saved = await first.saveVersion({ requestId: '2aa00000-0000-4000-8000-000000000001', templateId: '1aa00000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable continuation workflow');
    const compiled = await first.compile({ requestId: '2aa00000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled continuation workflow');
    const admissionRequest = { requestId: '2aa00000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: runId }; const waiting = await first.admitRun(admissionRequest);
    assert.equal(waiting.kind, 'waiting'); assert.equal(waiting.code, 'WORKFLOW_APPROVAL_REQUIRED'); assert.equal(waiting.run?.state, 'waiting-approval'); assert.equal(waiting.run?.completedNodeCount, 1); assert.equal(waiting.run?.failedNodeCount, 0);
    const waitingStore = new DatabaseSync(database); assert.deepEqual({ ...(waitingStore.prepare('SELECT state,safe_code FROM workflow_runs WHERE run_id=?').get(runId) as { state: string; safe_code: string }) }, { state: 'stopping', safe_code: 'WORKFLOW_APPROVAL_REQUIRED' }); assert.deepEqual({ ...(waitingStore.prepare('SELECT state,safe_code FROM workflow_node_attempts WHERE run_id=? AND node_id=?').get(runId, continuationNodeId) as { state: string; safe_code: string }) }, { state: 'ready', safe_code: 'WORKFLOW_APPROVAL_REQUIRED' }); assert.equal((waitingStore.prepare('SELECT phase FROM workflow_approval_waits WHERE run_id=? AND node_id=?').get(runId, continuationNodeId) as { phase: string }).phase, 'waiting'); assert.equal((waitingStore.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 1); waitingStore.close(); await first.onStop();

    const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); restarted.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await restarted.onStart(); const diagnostics = await restarted.diagnostics(); assert.equal(diagnostics.schedulerAdmission, 'enabled'); assert.equal(diagnostics.quarantinedRunCount, 0); assert.equal(diagnostics.recoveryBacklogCount, 0);
    const reviewRequest = { requestId: '2aa00000-0000-4000-8000-000000000005', runId, nodeId: continuationNodeId, sessionId: '2aa00000-0000-4000-8000-000000000006' }; const review = await restarted.beginContinuationReview(reviewRequest); assert.equal(review.kind, 'completed'); if (review.kind !== 'completed') throw new Error('Expected continuation review challenge'); assert.match(review.challenge, /^[A-Za-z0-9_-]{43}$/u); assert.equal(Date.parse(review.expiresAt) > Date.now(), true); assert.deepEqual(await restarted.beginContinuationReview(reviewRequest), review);
    const wrong = await restarted.continueRun({ requestId: '2aa00000-0000-4000-8000-000000000007', runId, nodeId: continuationNodeId, sessionId: reviewRequest.sessionId, challenge: 'A'.repeat(43) }); assert.deepEqual(wrong, { kind: 'refused', code: 'WORKFLOW_APPROVAL_INVALID' });
    const reviewedStore = new DatabaseSync(database); assert.equal((reviewedStore.prepare('SELECT phase FROM workflow_approval_waits WHERE run_id=? AND node_id=?').get(runId, continuationNodeId) as { phase: string }).phase, 'reviewed'); reviewedStore.prepare('UPDATE workflow_approval_waits SET expires_at=? WHERE run_id=? AND node_id=?').run('2026-08-27T00:00:00.000Z', runId, continuationNodeId); reviewedStore.close();
    const expired = await restarted.continueRun({ requestId: '2aa00000-0000-4000-8000-000000000008', runId, nodeId: continuationNodeId, sessionId: reviewRequest.sessionId, challenge: review.challenge }); assert.deepEqual(expired, { kind: 'refused', code: 'WORKFLOW_APPROVAL_INVALID' });
    const refreshedRequest = { ...reviewRequest, requestId: '2aa00000-0000-4000-8000-000000000009', sessionId: '2aa00000-0000-4000-8000-000000000010' }; const refreshed = await restarted.beginContinuationReview(refreshedRequest); assert.equal(refreshed.kind, 'completed'); if (refreshed.kind !== 'completed') throw new Error('Expected refreshed continuation challenge'); assert.notEqual(refreshed.challenge, review.challenge);
    const continueRequest = { requestId: '2aa00000-0000-4000-8000-000000000011', runId, nodeId: continuationNodeId, sessionId: refreshedRequest.sessionId, challenge: refreshed.challenge }; const completed = await restarted.continueRun(continueRequest); assert.equal(completed.kind, 'completed'); assert.equal(completed.code, 'WORKFLOW_OK'); assert.equal(completed.run?.state, 'completed'); assert.equal(completed.run?.completedNodeCount, 3); assert.equal(completed.run?.failedNodeCount, 0); assert.deepEqual(await restarted.continueRun(continueRequest), completed);
    const completedStore = new DatabaseSync(database); const wait = completedStore.prepare('SELECT phase,receipt_digest FROM workflow_approval_waits WHERE run_id=? AND node_id=?').get(runId, continuationNodeId) as { phase: string; receipt_digest: string }; assert.equal(wait.phase, 'approved'); assert.match(wait.receipt_digest, /^[0-9a-f]{64}$/u); assert.equal((completedStore.prepare("SELECT count(*) AS count FROM workflow_node_attempts WHERE state='succeeded'").get() as { count: number }).count, 3); assert.equal((completedStore.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 3); assert.equal((completedStore.prepare('SELECT count(*) AS count FROM workflow_outbox WHERE operation_kind=?').get('approval.continue') as { count: number }).count, 1); completedStore.close(); await restarted.onStop();

    const replayed = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); replayed.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await replayed.onStart(); assert.deepEqual(await replayed.continueRun(continueRequest), completed); assert.deepEqual(await replayed.admitRun(admissionRequest), waiting); const replayStore = new DatabaseSync(database); assert.equal((replayStore.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 3); replayStore.close(); await replayed.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('cancels overdue supervised agents and refuses unverified residual processes', async () => {
  for (const cancelTerminates of [true, false]) {
    const root = await mkdtemp(path.join(os.tmpdir(), `kogg-workflow-agent-timeout-${cancelTerminates}-`)); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const fixture = agentDispatcher('AGENT_OK', 'cleaned', { activeUntilCancel: true, cancelTerminates });
    try {
      const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); registry.setAgentAttemptDispatcher(fixture.dispatcher); await registry.onStart();
      const saved = await registry.saveVersion({ requestId: cancelTerminates ? '2c000000-0000-4000-8000-000000000001' : '2d000000-0000-4000-8000-000000000001', templateId: cancelTerminates ? '1c000000-0000-4000-8000-000000000001' : '1d000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph: agentGraph(1_000) }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable overdue agent workflow'); const compiled = await registry.compile({ requestId: cancelTerminates ? '2c000000-0000-4000-8000-000000000002' : '2d000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled overdue agent workflow');
      const failed = await registry.admitRun({ requestId: cancelTerminates ? '2c000000-0000-4000-8000-000000000003' : '2d000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: cancelTerminates ? '2c000000-0000-4000-8000-000000000004' : '2d000000-0000-4000-8000-000000000004' }); assert.equal(failed.kind, 'failed'); assert.equal(failed.code, cancelTerminates ? 'WORKFLOW_DEADLINE' : 'WORKFLOW_RESIDUAL_PROCESS'); assert.equal(fixture.cancels.length, cancelTerminates ? 1 : 2); assert.equal((await registry.diagnostics()).residualProcessCount, cancelTerminates ? 0 : 1); await registry.onStop();
    } finally { await rm(root, { recursive: true, force: true }); }
  }
});

test('durably skips the unselected condition branch and resolves its join without dispatch', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-branch-run-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart(); const graph = branchingControlGraph();
    const saved = await registry.saveVersion({ requestId: '26000000-0000-4000-8000-000000000001', templateId: '16000000-0000-4000-8000-000000000001', expectedVersionNumber: 0, graph }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable branching workflow');
    const compiled = await registry.compile({ requestId: '26000000-0000-4000-8000-000000000002', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled branching plan');
    const completed = await registry.admitRun({ requestId: '26000000-0000-4000-8000-000000000003', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000004' }); assert.equal(completed.kind, 'completed'); assert.equal(completed.run?.completedNodeCount, 5); assert.equal(completed.run?.skippedNodeCount, 1); assert.equal(completed.run?.failedNodeCount, 0);
    const store = new DatabaseSync(database); assert.equal((store.prepare("SELECT count(*) AS count FROM workflow_node_attempts WHERE state='succeeded' AND routing_state='selected'").get() as { count: number }).count, 5); assert.equal((store.prepare("SELECT count(*) AS count FROM workflow_node_attempts WHERE state='cancelled' AND routing_state='skipped' AND safe_code='WORKFLOW_OK'").get() as { count: number }).count, 1); assert.equal((store.prepare('SELECT count(*) AS count FROM workflow_outbox').get() as { count: number }).count, 5); store.close(); assert.equal((await registry.diagnostics()).schedulerIntegrity, true); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('run admission refuses before executor selection when task mode authority or project binding is unavailable', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-mode-authority-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); let calls = 0; let bindingCalls = 0;
  const refusedAuthority: ModeOperationAuthorizer = { async authorizeOperation(request) { calls++; assert.equal(request.operation, 'governed-entry'); assert.equal(request.taskId, TASK); if (request.requestId.endsWith('46')) throw new Error('prohibited-authority-detail'); return { schemaVersion: 1, allowed: true, safeCode: 'MODE_OK', projection: { ...(await MODE_AUTHORITY.authorizeOperation(request)).projection, projectId: '10000000-0000-4000-8000-000000000099' } }; } };
  const bindingAuthority: AgentBindingAuthorizer = { async authorizeBinding() { bindingCalls++; return { allowed: true, code: 'AGENT_OK', registryRevision: '1' }; } };
  try {
    const registry = new WorkflowRegistry(compiler, refusedAuthority, bindingAuthority, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000043', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await registry.compile({ requestId: '20000000-0000-4000-8000-000000000044', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan');
    const result = await registry.admitRun({ requestId: '20000000-0000-4000-8000-000000000045', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000005' });
    assert.deepEqual(result, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' });
    const unavailable = await registry.admitRun({ requestId: '20000000-0000-4000-8000-000000000046', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000006' });
    assert.deepEqual(unavailable, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' }); assert.equal(calls, 2); assert.equal(bindingCalls, 0); assert.equal((await registry.diagnostics()).recoveryBacklogCount, 0); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('run admission resolves every exact agent binding and fails closed before executor selection', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-agent-authority-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler(); const bindings: Parameters<AgentBindingAuthorizer['authorizeBinding']>[0][] = [];
  const bindingAuthority: AgentBindingAuthorizer = { async authorizeBinding(binding) { bindings.push(binding); if (bindings.length === 2) return { allowed: false, code: 'MODEL_MISMATCH', registryRevision: '7' }; if (bindings.length === 3) throw new Error('prohibited-provider-detail'); return { allowed: true, code: 'AGENT_OK', registryRevision: '7' }; } };
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, bindingAuthority, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000047', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await registry.compile({ requestId: '20000000-0000-4000-8000-000000000048', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan');
    const refused = await registry.admitRun({ requestId: '20000000-0000-4000-8000-000000000049', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000007' }); assert.deepEqual(refused, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' });
    assert.deepEqual(bindings.slice(0, 2), validGraph().nodes.map(item => { const configuration = item.configuration!; return { roleRevisionId: configuration.roleRevisionId, providerId: configuration.providerId, modelId: configuration.modelId, adapterKey: configuration.adapterKey, adapterVersion: configuration.adapterVersion, deadlinePolicyId: configuration.deadlinePolicyId }; }));
    const unavailable = await registry.admitRun({ requestId: '20000000-0000-4000-8000-000000000053', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000008' }); assert.deepEqual(unavailable, { kind: 'refused', code: 'WORKFLOW_AUTHORITY_EXPANSION' }); assert.equal(bindings.length, 3);
    const diagnostics = await registry.diagnostics(); assert.equal(diagnostics.activeProcessCount, 0); assert.equal(diagnostics.recoveryBacklogCount, 0); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('run admission rechecks the complete trust-spine plan digest and refuses live store tampering', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-admission-integrity-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const registry = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); registry.setTaskAdmissionAuthority(TASK_ADMISSION_AUTHORITY); await registry.onStart();
    const saved = await registry.saveVersion({ requestId: '20000000-0000-4000-8000-000000000050', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() });
    if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await registry.compile({ requestId: '20000000-0000-4000-8000-000000000051', versionId: saved.version.versionId });
    if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan');
    const corrupt = new DatabaseSync(database); corrupt.exec('DROP TRIGGER workflow_immutable_plans_update'); corrupt.prepare('UPDATE compiled_plans SET plan_digest=? WHERE plan_id=?').run('f'.repeat(64), compiled.plan.planId); corrupt.close();
    const refused = await registry.admitRun({ requestId: '20000000-0000-4000-8000-000000000052', planId: compiled.plan.planId, taskAdmissionId: '29000000-0000-4000-8000-000000000009' });
    assert.deepEqual(refused, { kind: 'refused', code: 'WORKFLOW_STORE_INTEGRITY' }); assert.equal((await registry.diagnostics()).planMismatchCount, 1); await registry.onStop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('restart quarantines durable scheduler and outbox ambiguity without replaying dispatch', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-scheduler-recovery-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await first.onStart();
    const saved = await first.saveVersion({ requestId: '20000000-0000-4000-8000-000000000060', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await first.compile({ requestId: '20000000-0000-4000-8000-000000000061', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan'); await first.onStop();
    const runId = '50000000-0000-4000-8000-000000000001'; const nodeId = validGraph().nodes[0]!.nodeId; const now = new Date().toISOString(); const store = new DatabaseSync(database);
    store.prepare("INSERT INTO workflow_runs(run_id,plan_id,plan_digest,state,revision,owner_epoch_id,safe_code,created_at,updated_at) VALUES(?,?,?,'running',1,?,'WORKFLOW_OK',?,?)").run(runId, compiled.plan.planId, compiled.plan.planDigest, '50000000-0000-4000-8000-000000000002', now, now);
    store.prepare("INSERT INTO workflow_node_attempts(run_id,node_id,attempt,state,fencing_token,safe_code,updated_at) VALUES(?,?,1,'running',?,'WORKFLOW_OK',?)").run(runId, nodeId, '50000000-0000-4000-8000-000000000003', now);
    store.prepare("INSERT INTO workflow_outbox(outbox_id,run_id,node_id,operation_kind,request_digest,fencing_token,phase,safe_code,created_at,updated_at) VALUES(?,?,?,'implementation.agent',?,?, 'claimed','WORKFLOW_OK',?,?)").run('50000000-0000-4000-8000-000000000004', runId, nodeId, 'a'.repeat(64), '50000000-0000-4000-8000-000000000003', now, now); store.close();
    const recovered = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await recovered.onStart(); const diagnostics = await recovered.diagnostics();
    assert.equal(diagnostics.schedulerIntegrity, true); assert.equal(diagnostics.schedulerLeaseActive, true); assert.equal(diagnostics.schedulerAdmission, 'blocked'); assert.equal(diagnostics.pendingOutboxCount, 0); assert.equal(diagnostics.quarantinedRunCount, 1); assert.equal(diagnostics.recoveryBacklogCount, 1);
    const checks = await new WorkflowDiagnosticContributor(recovered).diagnose(); assert.equal(checks.find(check => check.id === 'workflow.scheduler')?.status, 'fail'); assert.equal(checks.find(check => check.id === 'workflow.recovery')?.status, 'fail'); await recovered.onStop();
    const verify = new DatabaseSync(database); assert.equal((verify.prepare('SELECT phase FROM workflow_outbox').get() as { phase: string }).phase, 'quarantined'); assert.equal((verify.prepare('SELECT count(*) AS count FROM workflow_scheduler_events').get() as { count: number }).count, 1); verify.close();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('publishes immutable scheduler recovery facts through a stable workflow owner across restart', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-owner-')); const database = path.join(root, 'workflow.sqlite3'); const projectionPath = path.join(root, 'operations.sqlite3'); const compiler = workflowCompiler();
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await first.onStart();
    const saved = await first.saveVersion({ requestId: '20000000-0000-4000-8000-000000000080', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version');
    const compiled = await first.compile({ requestId: '20000000-0000-4000-8000-000000000081', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan'); await first.onStop();
    const runId = '52000000-0000-4000-8000-000000000001'; const now = new Date().toISOString(); const store = new DatabaseSync(database);
    store.prepare("INSERT INTO workflow_runs(run_id,plan_id,plan_digest,state,revision,owner_epoch_id,safe_code,created_at,updated_at) VALUES(?,?,?,'running',1,?,'WORKFLOW_OK',?,?)").run(runId, compiled.plan.planId, compiled.plan.planDigest, '52000000-0000-4000-8000-000000000002', now, now); store.close();
    const projection = new OperationsReadModel(projectionPath); projection.start(); projection.registerOwner('workflow');
    const recovered = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); recovered.setOwnerSink(projection); await recovered.onStart();
    assert.equal(projection.diagnostics().acceptedEventCount, 1); assert.equal(projection.diagnostics().ownerCount, 1); assert.equal(projection.snapshot().runs[0]?.runId, runId); assert.equal(projection.snapshot().runs[0]?.projectId, PROJECT); assert.equal(projection.snapshot().runs[0]?.lifecycle, 'failed');
    const identityBefore = new DatabaseSync(database); const ownerBefore = identityBefore.prepare('SELECT owner_id,owner_epoch_id FROM workflow_owner_meta').get() as { owner_id: string; owner_epoch_id: string }; identityBefore.close(); await recovered.onStop();
    const restarted = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); restarted.setOwnerSink(projection); await restarted.onStart(); assert.equal(projection.diagnostics().acceptedEventCount, 1);
    const identityAfter = new DatabaseSync(database); const ownerAfter = identityAfter.prepare('SELECT owner_id,owner_epoch_id FROM workflow_owner_meta').get() as { owner_id: string; owner_epoch_id: string }; identityAfter.close(); assert.deepEqual(ownerAfter, ownerBefore);
    assert.equal(JSON.stringify(projection.snapshot()).includes('configurationDigest'), false); assert.equal(JSON.stringify(projection.snapshot()).includes('requestedEffects'), false);
    await restarted.onStop(); projection.stop();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('refuses startup after stable workflow owner identity corruption', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-owner-integrity-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await first.onStart(); await first.onStop();
    const corrupt = new DatabaseSync(database); corrupt.exec('DROP TRIGGER workflow_immutable_owner_meta_update'); corrupt.prepare('UPDATE workflow_owner_meta SET owner_epoch_id=?').run('53000000-0000-4000-8000-000000000001'); corrupt.close();
    await assert.rejects(new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database).onStart(), /WORKFLOW_STORE_INTEGRITY/u);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('refuses startup after immutable scheduler recovery fact corruption', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'kogg-workflow-scheduler-integrity-')); const database = path.join(root, 'workflow.sqlite3'); const compiler = workflowCompiler();
  try {
    const first = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await first.onStart(); const saved = await first.saveVersion({ requestId: '20000000-0000-4000-8000-000000000070', templateId: TEMPLATE, expectedVersionNumber: 0, graph: validGraph() }); if (saved.kind !== 'completed' || !saved.version) throw new Error('Expected immutable workflow version'); const compiled = await first.compile({ requestId: '20000000-0000-4000-8000-000000000071', versionId: saved.version.versionId }); if (compiled.kind !== 'completed' || !compiled.plan) throw new Error('Expected compiled workflow plan'); await first.onStop();
    const now = new Date().toISOString(); const runId = '51000000-0000-4000-8000-000000000001'; const store = new DatabaseSync(database); store.prepare("INSERT INTO workflow_runs(run_id,plan_id,plan_digest,state,revision,owner_epoch_id,safe_code,created_at,updated_at) VALUES(?,?,?,'running',1,?,'WORKFLOW_OK',?,?)").run(runId, compiled.plan.planId, compiled.plan.planDigest, '51000000-0000-4000-8000-000000000002', now, now); store.close();
    const recovered = new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database); await recovered.onStart(); await recovered.onStop(); const corrupt = new DatabaseSync(database); corrupt.exec('DROP TRIGGER workflow_immutable_scheduler_events_update'); corrupt.prepare("UPDATE workflow_scheduler_events SET safe_code='WORKFLOW_OK'").run(); corrupt.close();
    await assert.rejects(new WorkflowRegistry(compiler, MODE_AUTHORITY, AGENT_BINDING_AUTHORITY, database).onStart(), /WORKFLOW_STORE_INTEGRITY/u);
  } finally { await rm(root, { recursive: true, force: true }); }
});

function validGraph(): EditableWorkflowGraphV1 & { nodes: EditableWorkflowNodeV1[]; edges: ReturnType<typeof edge>[] } { const research = node('30000000-0000-4000-8000-000000000001', 'research.agent', ['read-repository','invoke-provider']); const implementation = node('30000000-0000-4000-8000-000000000002', 'implementation.agent', ['read-repository','mutate-private-repository','invoke-provider','run-tool']); return { schemaVersion: '1', projectId: PROJECT, nodes: [research, implementation], edges: [edge('40000000-0000-4000-8000-000000000001', research.nodeId, implementation.nodeId)] }; }
function agentGraph(absoluteDeadlineMs = 60_000): EditableWorkflowGraphV1 & { nodes: EditableWorkflowNodeV1[] } { const agent = node('3a000000-0000-4000-8000-000000000001', 'research.agent', ['read-repository','invoke-provider']); const configuration = { ...agent.configuration!, absoluteDeadlineMs }; return { schemaVersion: '1', projectId: PROJECT, nodes: [{ ...agent, configuration, configurationDigest: workflowDigest('node-configuration', configuration) }], edges: [] }; }
function approvalGraph(): EditableWorkflowGraphV1 & { nodes: EditableWorkflowNodeV1[] } { return { schemaVersion: '1', projectId: PROJECT, nodes: [node('3e000000-0000-4000-8000-000000000001', 'approval.specification', ['record-approval'])], edges: [] }; }
function continuationGraph(): EditableWorkflowGraphV1 & { nodes: EditableWorkflowNodeV1[] } { const start = node('3aa00000-0000-4000-8000-000000000001', 'control.group', []); const continuation = node('3aa00000-0000-4000-8000-000000000002', 'approval.continue', ['record-approval']); const cleanup = node('3aa00000-0000-4000-8000-000000000003', 'control.finally', []); return { schemaVersion: '1', projectId: PROJECT, nodes: [start, continuation, cleanup], edges: [edge('4aa00000-0000-4000-8000-000000000001', start.nodeId, continuation.nodeId), edge('4aa00000-0000-4000-8000-000000000002', continuation.nodeId, cleanup.nodeId)] }; }
function failureContinuationGraph(): EditableWorkflowGraphV1 & { nodes: EditableWorkflowNodeV1[] } { const agent = agentGraph().nodes[0]!; const continuation = node('3bb00000-0000-4000-8000-000000000002', 'approval.continue', ['record-approval']); const cleanup = node('3bb00000-0000-4000-8000-000000000003', 'control.finally', []); return { schemaVersion: '1', projectId: PROJECT, nodes: [agent, continuation, cleanup], edges: [edge('4bb00000-0000-4000-8000-000000000001', agent.nodeId, continuation.nodeId, 'failure'), edge('4bb00000-0000-4000-8000-000000000002', continuation.nodeId, cleanup.nodeId)] }; }
function controlGraph(condition: 'always' | 'prior-success', single = false): EditableWorkflowGraphV1 { const configuration = { schemaVersion: '1' as const, absoluteDeadlineMs: 1_000, target: 'project-read-only' as const, condition }; const first: EditableWorkflowNodeV1 = { nodeId: '34000000-0000-4000-8000-000000000001', kind: condition === 'always' ? 'control.group' : 'control.condition', kindVersion: '1', configuration, configurationDigest: workflowDigest('node-configuration', configuration), requestedEffects: [], retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: 'none' } }; if (single) return { schemaVersion: '1', projectId: PROJECT, nodes: [first], edges: [] }; const second = node('34000000-0000-4000-8000-000000000002', 'control.finally', []); return { schemaVersion: '1', projectId: PROJECT, nodes: [first, second], edges: [edge('44000000-0000-4000-8000-000000000001', first.nodeId, second.nodeId)] }; }
function branchingControlGraph(): EditableWorkflowGraphV1 { const configuration = { schemaVersion: '1' as const, absoluteDeadlineMs: 1_000, target: 'project-read-only' as const, condition: 'prior-success' as const }; const start = node('36000000-0000-4000-8000-000000000001', 'control.group', []); const condition: EditableWorkflowNodeV1 = { nodeId: '36000000-0000-4000-8000-000000000002', kind: 'control.condition', kindVersion: '1', configuration, configurationDigest: workflowDigest('node-configuration', configuration), requestedEffects: [], retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: 'none' } }; const selected = node('36000000-0000-4000-8000-000000000003', 'control.group', []); const skipped = node('36000000-0000-4000-8000-000000000004', 'control.group', []); const join = node('36000000-0000-4000-8000-000000000005', 'control.join', []); const cleanup = node('36000000-0000-4000-8000-000000000006', 'control.finally', []); return { schemaVersion: '1', projectId: PROJECT, nodes: [start, condition, selected, skipped, join, cleanup], edges: [edge('46000000-0000-4000-8000-000000000001', start.nodeId, condition.nodeId), edge('46000000-0000-4000-8000-000000000002', condition.nodeId, selected.nodeId, 'true'), edge('46000000-0000-4000-8000-000000000003', condition.nodeId, skipped.nodeId, 'false'), edge('46000000-0000-4000-8000-000000000004', selected.nodeId, join.nodeId), edge('46000000-0000-4000-8000-000000000005', skipped.nodeId, join.nodeId), edge('46000000-0000-4000-8000-000000000006', join.nodeId, cleanup.nodeId, 'finally')] }; }
function externalGraph(): EditableWorkflowGraphV1 {
  const configured = (nodeId: string, kind: 'tool.git' | 'tool.build' | 'check.deterministic', bindingId: string, target: 'project-read-only' | 'private-worktree', requestedEffects: EditableWorkflowNodeV1['requestedEffects']): EditableWorkflowNodeV1 => { const configuration = { schemaVersion: '1' as const, ...(kind === 'check.deterministic' ? { checkId: bindingId } : { operationId: bindingId }), externalConfigurationDigest: 'b'.repeat(64), absoluteDeadlineMs: 60_000, target, condition: 'always' as const }; return { nodeId, kind, kindVersion: '1', configuration, configurationDigest: workflowDigest('node-configuration', configuration), requestedEffects, retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: kind === 'tool.git' ? 'idempotent-exact-key' : 'none' } }; };
  const git = configured('37000000-0000-4000-8000-000000000001', 'tool.git', 'git.status-v1', 'private-worktree', ['read-repository','mutate-private-repository','run-tool']); const build = configured('37000000-0000-4000-8000-000000000002', 'tool.build', 'build.repository-v1', 'project-read-only', ['read-repository','run-tool']); const check = configured('37000000-0000-4000-8000-000000000003', 'check.deterministic', 'suite.required-v1', 'project-read-only', ['read-repository','run-tool','record-check']); return { schemaVersion: '1', projectId: PROJECT, nodes: [git, build, check], edges: [edge('47000000-0000-4000-8000-000000000001', git.nodeId, build.nodeId), edge('47000000-0000-4000-8000-000000000002', build.nodeId, check.nodeId)] };
}
function externalContracts(): readonly WorkflowExternalExecutorContractV1[] { const execution = { schemaVersion: '1' as const, executorId: 'kogg.execution.catalog' as const, executorVersion: '1.0.0' as const, executionKind: 'external-catalog' as const, ownerKind: 'execution' as const, supportedKinds: ['tool.git','tool.build'] as const, supportedBindingIds: { 'tool.git': ['git.status-v1'], 'tool.build': ['build.repository-v1'] } }; const kernel = { schemaVersion: '1' as const, executorId: 'kogg.kernel.checks' as const, executorVersion: '1.0.0' as const, executionKind: 'external-catalog' as const, ownerKind: 'kernel' as const, supportedKinds: ['check.deterministic'] as const, supportedBindingIds: { 'check.deterministic': ['suite.required-v1'] } }; return [{ ...execution, artifactDigest: workflowDigest('executor-artifact', execution) }, { ...kernel, artifactDigest: workflowDigest('executor-artifact', kernel) }]; }
function node(nodeId: string, kind: EditableWorkflowNodeV1['kind'], requestedEffects: EditableWorkflowNodeV1['requestedEffects']): EditableWorkflowNodeV1 & { requestedEffects: EditableWorkflowNodeV1['requestedEffects']; retry: EditableWorkflowNodeV1['retry']; configurationDigest: string } { const configuration = kind === 'research.agent' ? { schemaVersion: '1' as const, roleRevisionId: '60000000-0000-4000-8000-000000000001', providerId: 'kogg.fixture', modelId: 'fixture.research', adapterKey: 'kogg.fixture', adapterVersion: '1.0.0', deadlinePolicyId: 'research-v1', absoluteDeadlineMs: 60_000, target: 'project-read-only' as const, condition: 'always' as const } : kind === 'implementation.agent' ? { schemaVersion: '1' as const, roleRevisionId: '60000000-0000-4000-8000-000000000002', providerId: 'kogg.fixture', modelId: 'fixture.echo', adapterKey: 'kogg.fixture', adapterVersion: '1.0.0', deadlinePolicyId: 'interactive-v1', absoluteDeadlineMs: 60_000, target: 'private-worktree' as const, condition: 'always' as const } : undefined; return { nodeId, kind, kindVersion: '1', configurationDigest: configuration ? workflowDigest('node-configuration', configuration) : 'a'.repeat(64), ...(configuration ? { configuration } : {}), requestedEffects, retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: 'none' } }; }
function edge(edgeId: string, sourceNodeId: string, targetNodeId: string, sourcePort: 'success' | 'failure' | 'finally' | 'true' | 'false' = 'success') { return { edgeId, sourceNodeId, sourcePort, targetNodeId, targetPort: 'in' as const }; }
function workflowCompiler(): WorkflowCompiler { return new WorkflowCompiler(new WorkflowNodeCatalog(new WorkflowExecutorRegistry())); }
function taskAdmission(taskAdmissionId: string) { return { taskAdmissionId, taskId: TASK, specificationId: '18000000-0000-4000-8000-000000000001', taskRevisionId: '18000000-0000-4000-8000-000000000001', taskRevisionDigest: `sha256:${'1'.repeat(64)}`, approvalId: '18000000-0000-4000-8000-000000000002', approvalDigest: `sha256:${'2'.repeat(64)}`, projectId: PROJECT, repositoryId: REPOSITORY, bindingRevision: '1', registryRevision: '1', taskRevision: '1', runId: taskAdmissionId, authorizedAt: '2026-08-27T00:00:00.000Z', expiresAt: '2099-08-27T00:00:00.000Z' } as const; }
function agentDispatcher(terminalCode: AgentSafeCode = 'AGENT_OK', state: AttemptProjectionV1['state'] = 'cleaned', options: { activeUntilCancel?: boolean; cancelTerminates?: boolean } = {}) {
  const starts: StartAttemptRequestV1[] = []; const cancels: unknown[] = []; const attemptId = '3a000000-0000-4000-8000-000000000002'; let cancelled = false;
  const attempt = (): AttemptProjectionV1 => { const active = options.activeUntilCancel && !cancelled; const projectedState = active ? 'active' : state; return { schemaVersion: '1', attemptId, rootAttemptId: attemptId, attemptRevision: active ? '8' : '9', registryRevision: '8', taskId: TASK, projectId: PROJECT, repositoryId: REPOSITORY, specificationId: '18000000-0000-4000-8000-000000000001', approvalId: '18000000-0000-4000-8000-000000000002', runId: starts.at(-1)?.taskAdmissionId, authorityMode: 'kogg', authoritySequence: '1', authorityOperation: 'research', roleRevisionId: agentGraph().nodes[0]!.configuration!.roleRevisionId!, deadlinePolicyId: 'research-v1', deadlines: [], adapterKey: 'kogg.fixture', adapterVersion: '1.0.0', providerId: 'kogg.fixture', requestedModelId: 'fixture.research', observedModelId: 'fixture.research', state: projectedState, terminalCode: active ? undefined : terminalCode, activityCount: '1', childCount: '0', ownedResourceCount: projectedState === 'cleanup_failed' ? '1' : '0', usage: { status: 'complete', source: 'provider-cumulative', totalTokens: '1' }, requestedAt: '2026-08-27T00:00:00.000Z', stateChangedAt: '2026-08-27T00:00:01.000Z' }; };
  const dispatcher = { async snapshot() { return { schemaVersion: '1', registryRevision: '7', admission: 'enabled', roles: [], attempts: [], adapters: [] } as const; }, async startAttempt(request: StartAttemptRequestV1) { starts.push(request); return { kind: 'completed', code: 'AGENT_OK', registryRevision: '8', attempt: attempt() } as const; }, async getAttempt() { return attempt(); }, async cancelAttempt(request: unknown) { cancels.push(request); if (options.cancelTerminates !== false) cancelled = true; return options.cancelTerminates === false ? { kind: 'conflict', code: 'REGISTRY_REVISION_CONFLICT', registryRevision: '8' } as const : { kind: 'completed', code: terminalCode, registryRevision: '8', attempt: attempt() } as const; } } as unknown as KoggAgentsService;
  return { dispatcher, starts, cancels, attemptId };
}
