import assert from 'node:assert/strict'; import test from 'node:test'; import { createHash } from 'node:crypto'; import { PassThrough } from 'node:stream';
import { AdapterRegistry } from '@kogg/agents/lib/node/adapter-registry';
import type { AgentAdapterFactory, AgentAdapterSession } from '@kogg/agents/lib/common/agents-protocol';
import { CodexAdapterFactory } from './codex-adapter-factory';
import { CodexAttemptAuthorityRegistry, type QualifiedCodexAttemptAuthority } from './codex-attempt-authority';
import type { QualifiedCodexRuntimeV1 } from './codex-release-registry';
import { CodexReleaseRegistry } from './codex-release-registry';
import { CodexRecoveryRegistry } from './codex-recovery-registry';
import { CodexRuntimeAuthorityFault, CodexRuntimeAuthorityRegistry, type QualifiedCodexRuntimeAuthority } from './codex-runtime-authority';

// diagnostic-coverage: codex.release, codex.confinement, codex.protocol, codex.credentials, codex.processes, codex.cleanup, codex.recovery, codex.source-maps
const release = { manifestVersion: '1', releaseId: 'codex-release-1', codexVersion: '1.2.3', codexCommit: 'a'.repeat(40), target: 'x86_64-unknown-linux-musl', binarySha256: 'b'.repeat(64), binarySize: '10', appServerSchemaVersion: 'v2', appServerSchemaSha256: 'c'.repeat(64), acceptedMethodsSha256: 'd'.repeat(64), linuxHelperSha256: 'e'.repeat(64), adapterVersion: '1.0.0', qualificationProfileId: 'kogg-writable-agent-v1', signedAt: '2026-01-01T00:00:00.000Z', signatureKeyId: 'release-key-1', signature: 'signed' } as const;
const runtime: QualifiedCodexRuntimeV1 = Object.freeze({ release: Object.freeze(release), binary: '/private/release/codex', linuxHelper: '/private/release/helper', acceptedMethods: Object.freeze({ inboundSet: Object.freeze({ size: 1, has: (method: string) => method === 'turn/started' }), responses: Object.freeze([]), inbound: Object.freeze([]), errorDefinition: 'JSONRPCErrorError' }), frameSchema: { validate: () => undefined } });
const releaseRegistry = { onStart: async () => undefined, qualifiedRuntime: () => runtime, projection: () => ({ qualified: true, safeCode: 'CODEX_OK', adapterVersion: '1.0.0', target: release.target, releasePresent: true, assetsVerified: true, protocolVerified: true, confinementVerified: false, credentialBrokerReady: false, sourceMapsPresent: true }) } as CodexReleaseRegistry;
const input = { binding: { schemaVersion: '1', attemptId: '10000000-0000-4000-8000-000000000001', taskId: 'task-1', projectId: 'project-1', repositoryId: 'repository-1', repositoryBindingRevision: '1', specificationId: 'specification-1', approvalId: 'approval-1', runId: 'run-1', roleRevisionId: 'role-1', deadlinePolicyId: 'interactive-v1', providerId: 'openai', modelId: 'gpt-5', worktreeId: '20000000-0000-4000-8000-000000000001' }, operation: { id: 'operation-1' }, credentialLease: { leaseId: 'lease-1', expiresAt: '2099-01-01T00:00:00.000Z', consume() {}, dispose() {} }, onObservation: () => undefined } as unknown as Parameters<AgentAdapterFactory['create']>[0];
const session: AgentAdapterSession = { resourceId: 'resource-1', resourceKind: 'provider-host', ownerKind: 'kogg', start: async () => undefined, cancel: async () => undefined, cleanup: async () => ({ residualCount: 0 }) };
function authority(overrides: Partial<QualifiedCodexRuntimeAuthority> = {}): QualifiedCodexRuntimeAuthority { return { qualify: async () => ({ releaseId: release.releaseId, target: release.target, qualificationProfileId: release.qualificationProfileId, confinementVerified: true, credentialBrokerReady: true }), reserveCredentials: async () => ({ reservationId: 'reservation-1' }), activateCredentials: async () => undefined, revokeCredentials: async () => undefined, prepareProcess: async ({ processRegistrationId }) => ({ processRegistrationId, cgroupIdentityDigest: '7'.repeat(64) }), spawnProcess: async () => { throw new Error('not started by fixture'); }, terminateProcess: async () => undefined, enumerateProcessResiduals: async () => 0, create: () => session, ...overrides }; }
function attemptAuthority(overrides: Partial<QualifiedCodexAttemptAuthority> = {}): CodexAttemptAuthorityRegistry { const owner: QualifiedCodexAttemptAuthority = { authorize: ({ binding }) => { const unsigned = { schemaVersion: '1' as const, attemptId: binding.attemptId, taskRevisionDigest: '1'.repeat(64), repositoryBindingDigest: '2'.repeat(64), privateRepoObjectId: binding.worktreeId!, baseCommit: '3'.repeat(40), worktreePolicy: 'private-writable' as const, roleRevisionId: binding.roleRevisionId, provider: 'openai' as const, model: binding.modelId, releaseId: release.releaseId, target: release.target, qualificationProfileId: release.qualificationProfileId, deadlinePolicyId: binding.deadlinePolicyId, budgets: { inputTokens: '1000', outputTokens: '1000', toolCalls: '10', bytesIn: '100000', bytesOut: '100000' }, deadlines: { spawnMs: 20000 as const, initializeMs: 30000 as const, threadStartMs: 30000 as const, firstActivityMs: 60000 as const, idleMs: 120000 as const, providerRequestMs: 120000 as const, interruptMs: 10000 as const, cleanupMs: 10000 as const, absoluteMs: 600000 } }; return { ...unsigned, authorityDigest: createHash('sha256').update(canonical(unsigned)).digest('hex') }; }, ...overrides }; return new CodexAttemptAuthorityRegistry(owner); }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; return JSON.stringify(value); }

test('fails closed without an installed runtime authority and never creates a session', async () => {
  const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority()); await registry.onStart(); assert.equal(registry.projection().ownerReady, false); assert.equal(registry.projection().safeCode, 'CODEX_CONFINEMENT_UNVERIFIED'); assert.throws(() => registry.create(input), error => error instanceof CodexRuntimeAuthorityFault && error.code === 'CODEX_CONFINEMENT_UNVERIFIED');
});
test('rejects an authority projection that does not attest the exact retained release', async () => {
  let creates = 0; const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), authority({ qualify: async () => ({ releaseId: 'different-release', target: release.target, qualificationProfileId: release.qualificationProfileId, confinementVerified: true, credentialBrokerReady: true }), create: () => { creates++; return session; } })); await registry.onStart(); assert.equal(registry.projection().ownerReady, false); assert.equal(creates, 0); assert.throws(() => registry.create(input), /CODEX_CONFINEMENT_UNVERIFIED/u);
});
test('retains an exact partial authority projection but refuses session creation until the broker is ready', async () => {
  const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), authority({ qualify: async () => ({ releaseId: release.releaseId, target: release.target, qualificationProfileId: release.qualificationProfileId, confinementVerified: true, credentialBrokerReady: false }) })); await registry.onStart(); assert.equal(registry.projection().ownerReady, true); assert.equal(registry.projection().safeCode, 'CODEX_CREDENTIAL_LEASE_REFUSED'); assert.throws(() => registry.create(input), /CODEX_CREDENTIAL_LEASE_REFUSED/u);
});
test('keeps the adapter disabled when the exact attempt authority is absent', async () => {
  let creates = 0; const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, new CodexAttemptAuthorityRegistry(), authority({ create: () => { creates++; return session; } })); const recovery = new CodexRecoveryRegistry({ reconcileStartup: async () => ({ processCount: 0, residualCount: 0, cleanupFailureCount: 0, recoveryBacklog: 0, recoveryComplete: true }) }); const factory = new CodexAdapterFactory(new AdapterRegistry(), releaseRegistry, recovery, registry); await factory.onStart(); assert.equal(factory.descriptor.enabled, false); assert.throws(() => factory.create(input), /CODEX_ATTEMPT_INVALID/u); assert.equal(creates, 0);
});
test('enables the factory only after exact authority and recovery qualification, then delegates immutable gates without raw authority inputs', async () => {
  let qualified = 0; let captured: QualifiedCodexRuntimeV1 | undefined; let rawBindingVisible = false; let rawLeaseVisible = false; let rawOperationVisible = false; let rawCredentialsVisible = false; const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), authority({ qualify: async () => { qualified++; return { releaseId: release.releaseId, target: release.target, qualificationProfileId: release.qualificationProfileId, confinementVerified: true, credentialBrokerReady: true }; }, create: value => { captured = value.runtime; rawBindingVisible = 'binding' in value; rawLeaseVisible = 'credentialLease' in value; rawOperationVisible = 'operation' in value; rawCredentialsVisible = 'credentials' in value; assert.equal(Object.isFrozen(value.attempt), true); assert.throws(() => value.processes.register(), /CODEX_PROCESS_REGISTRATION_FAILED/u); return session; } }));
  const recovery = new CodexRecoveryRegistry({ reconcileStartup: async () => ({ processCount: 0, residualCount: 0, cleanupFailureCount: 0, recoveryBacklog: 0, recoveryComplete: true }) }); const adapters = new AdapterRegistry(); const factory = new CodexAdapterFactory(adapters, releaseRegistry, recovery, registry); await Promise.all([factory.onStart(), factory.onStart()]);
  assert.equal(qualified, 1); assert.equal(factory.descriptor.enabled, true); assert.equal(adapters.descriptors().length, 1); const created = factory.create(input); assert.equal(created.resourceId, session.resourceId); assert.notEqual(created, session); assert.equal(captured, runtime); assert.equal(rawBindingVisible, false); assert.equal(rawLeaseVisible, false); assert.equal(rawOperationVisible, false); assert.equal(rawCredentialsVisible, false);
});
test('keeps the shared credential lease behind the process gate and abandons it when no process registers', async () => {
  const events: string[] = []; const localInput = { ...input, credentialLease: { leaseId: 'lease-2', expiresAt: '2099-01-01T00:00:00.000Z', consume: () => events.push('lease.consumed'), dispose: () => events.push('lease.disposed') } }; const owner = authority({ reserveCredentials: async () => { events.push('broker.reserved'); return { reservationId: 'reservation-2' }; }, activateCredentials: async () => { events.push('broker.activated'); }, revokeCredentials: async () => { events.push('broker.revoked'); }, create: value => { assert.equal('credentials' in value, false); return { ...session, async start() { events.push('owner.started'); }, async cleanup() { events.push('owner.cleaned'); return { residualCount: 0 }; } }; } }); const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), owner); await registry.onStart(); const created = registry.create(localInput); await created.start(); assert.deepEqual(await created.cleanup(), { residualCount: 0 }); assert.deepEqual(events, ['owner.started','owner.cleaned','lease.disposed']);
});
test('composes logical registration, cgroup preparation, credentials, spawn, and zero-residual cleanup through one gate', async () => {
  const events: string[] = []; let close!: (value: { exitClass: 'signal' }) => void; const closed = new Promise<{ exitClass: 'signal' }>(resolve => { close = resolve; }); const processLease = { id: 'process-9', spawning: () => events.push('process.spawning'), started: () => events.push('process.started'), ready: () => events.push('process.ready'), activity: () => undefined, failed: () => events.push('process.failed'), exited: () => events.push('process.exited'), cleanup: () => events.push('process.cleaned') }; const operation = { id: 'operation-9', registerProcess: () => { events.push('process.registered'); return processLease; } }; const localInput = { ...input, operation, credentialLease: { leaseId: 'lease-9', expiresAt: '2099-01-01T00:00:00.000Z', consume: () => events.push('lease.consumed'), dispose: () => events.push('lease.disposed') } } as unknown as typeof input;
  const owner = authority({ reserveCredentials: async () => { events.push('broker.reserved'); return { reservationId: 'reservation-9' }; }, activateCredentials: async ({ activation }) => { events.push(`broker.activated.${activation.processRegistrationId}`); }, revokeCredentials: async () => { events.push('broker.revoked'); }, prepareProcess: async ({ binding, processRegistrationId }) => { events.push(`owner.prepared.${processRegistrationId}`); assert.equal(binding.authorityDigest.length, 64); assert.equal(binding.releaseId, release.releaseId); return { processRegistrationId, cgroupIdentityDigest: '9'.repeat(64) }; }, spawnProcess: async ({ identity }) => { events.push(`owner.spawned.${identity.processRegistrationId}`); return { pid: 99, processRegistrationId: identity.processRegistrationId, cgroupIdentityDigest: identity.cgroupIdentityDigest, startTimeTokenDigest: '8'.repeat(64), identityVerified: true, stdin: new PassThrough(), stdout: new PassThrough(), stderr: new PassThrough(), closed }; }, terminateProcess: async ({ processRegistrationId }) => { events.push(`owner.terminated.${processRegistrationId}`); close({ exitClass: 'signal' }); }, enumerateProcessResiduals: async ({ processRegistrationId }) => { events.push(`owner.enumerated.${processRegistrationId}`); return 0; }, create: value => { let host: ReturnType<typeof value.processes.register>; return { ...session, async start() { host = value.processes.register(); await host.start(() => undefined); events.push('owner.started'); }, async cleanup() { events.push('owner.cleaned'); return { residualCount: 0 }; } }; } }); const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), owner); await registry.onStart(); const created = registry.create(localInput); await created.start(); assert.deepEqual(await created.cleanup(), { residualCount: 0 }); for (const expected of ['process.registered','owner.prepared.process-9','broker.reserved','lease.consumed','broker.activated.process-9','owner.spawned.process-9','process.started','process.ready','owner.cleaned','broker.revoked','lease.disposed','owner.terminated.process-9','process.exited','owner.enumerated.process-9','process.cleaned']) assert.equal(events.filter(value => value === expected).length, 1); assert.ok(events.indexOf('process.registered') < events.indexOf('owner.prepared.process-9')); assert.ok(events.indexOf('broker.activated.process-9') < events.indexOf('owner.spawned.process-9')); assert.ok(events.indexOf('broker.revoked') < events.indexOf('owner.terminated.process-9')); assert.ok(events.indexOf('owner.enumerated.process-9') < events.indexOf('process.cleaned'));
});
test('revokes and disposes the credential grant when owner startup fails', async () => {
  const events: string[] = []; const localInput = { ...input, credentialLease: { leaseId: 'lease-3', expiresAt: '2099-01-01T00:00:00.000Z', consume: () => events.push('lease.consumed'), dispose: () => events.push('lease.disposed') } }; const owner = authority({ reserveCredentials: async () => { events.push('broker.reserved'); return { reservationId: 'reservation-3' }; }, activateCredentials: async () => { events.push('broker.activated'); }, revokeCredentials: async () => { events.push('broker.revoked'); }, create: value => { assert.equal('credentials' in value, false); return { ...session, async start() { events.push('owner.failed'); throw new Error('startup failed'); }, async cleanup() { events.push('owner.cleaned'); return { residualCount: 0 }; } }; } }); const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), owner); await registry.onStart(); const created = registry.create(localInput); await assert.rejects(created.start(), /startup failed/u); assert.deepEqual(events, ['owner.failed','owner.cleaned','lease.disposed']);
});
test('normalizes malformed authority sessions without leaking private authority errors', async () => {
  const canary = `private-authority-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values));
  try { const registry = new CodexRuntimeAuthorityRegistry(releaseRegistry, attemptAuthority(), authority({ create: () => { throw new Error(canary); } })); await registry.onStart(); assert.throws(() => registry.create(input), error => error instanceof CodexRuntimeAuthorityFault && error.code === 'CODEX_INTERNAL_FAILURE'); assert.equal(logs.join('\n').includes(canary), false); }
  finally { console.error = original; }
});
