import assert from 'node:assert/strict'; import { PassThrough } from 'node:stream'; import test from 'node:test';
import type { OperationLease, ProcessLease } from '@kogg/operations/lib/common/operations-protocol';
import type { GovernedCodexAttemptV1 } from '../common/codex-protocol';
import { CodexCredentialReservation } from './codex-credential-reservation';
import { CodexProcessHost, CodexProcessHostFault, type CodexOwnedHost, type CodexProcessIdentityV1, type QualifiedCodexExecutionOwner } from './codex-process-host';
import type { QualifiedCodexRuntimeV1 } from './codex-release-registry';

// diagnostic-coverage: codex.confinement, codex.credentials, codex.processes, codex.cleanup, codex.recovery, codex.source-maps
const attempt = Object.freeze({ schemaVersion: '1', attemptId: '10000000-0000-4000-8000-000000000001', authorityDigest: '0'.repeat(64), taskRevisionDigest: '1'.repeat(64), repositoryBindingDigest: '2'.repeat(64), privateRepoObjectId: '20000000-0000-4000-8000-000000000001', baseCommit: '3'.repeat(40), worktreePolicy: 'private-writable', roleRevisionId: 'role-1', provider: 'openai', model: 'gpt-5', releaseId: 'codex-release-1', target: 'x86_64-unknown-linux-musl', qualificationProfileId: 'kogg-writable-agent-v1', deadlinePolicyId: 'interactive-v1', budgets: { inputTokens: '1000', outputTokens: '1000', toolCalls: '10', bytesIn: '100000', bytesOut: '100000' }, deadlines: { spawnMs: 20000, initializeMs: 30000, threadStartMs: 30000, firstActivityMs: 60000, idleMs: 120000, providerRequestMs: 120000, interruptMs: 10000, cleanupMs: 10000, absoluteMs: 600000 } }) as GovernedCodexAttemptV1;
const runtime = { release: { releaseId: attempt.releaseId, target: attempt.target, qualificationProfileId: attempt.qualificationProfileId, binarySha256: '4'.repeat(64), linuxHelperSha256: '5'.repeat(64) } } as QualifiedCodexRuntimeV1;
const identity: CodexProcessIdentityV1 = { processRegistrationId: 'process-1', cgroupIdentityDigest: '6'.repeat(64) };
function harness(options: { registrationFails?: boolean; prepare?: Partial<CodexProcessIdentityV1>; prepareFails?: boolean; prepareError?: Error; host?: Partial<CodexOwnedHost>; logicalFault?: 'spawning' | 'started' | 'ready' | 'failed' | 'exited' | 'cleanup'; residuals?: number; spawnFails?: boolean; spawnStalls?: boolean } = {}) {
  const events: string[] = []; let close!: (value: { exitClass: 'zero' | 'nonzero' | 'signal' }) => void; const closed = new Promise<{ exitClass: 'zero' | 'nonzero' | 'signal' }>(resolve => { close = resolve; }); let cancelProcess!: () => Promise<void>;
  const logical = (name: NonNullable<typeof options.logicalFault>, event: string): void => { events.push(event); if (options.logicalFault === name) throw new Error(`private logical ${name}`); }; const process: ProcessLease = { id: 'process-1', spawning: () => logical('spawning', 'process.spawning'), started: () => logical('started', 'process.started'), ready: () => logical('ready', 'process.ready'), activity: () => undefined, failed: () => logical('failed', 'process.failed'), exited: value => logical('exited', `process.exited.${value}`), cleanup: () => logical('cleanup', 'process.cleaned') };
  const operation = { id: 'operation-1', registerProcess: (input: { cancel: () => Promise<void> }) => { events.push('process.registered'); if (options.registrationFails) throw new Error('private registry failure'); cancelProcess = input.cancel; return process; } } as unknown as OperationLease;
  const credentials = new CodexCredentialReservation(attempt, { leaseId: 'lease-1', expiresAt: '2099-01-01T00:00:00.000Z', consume: () => events.push('lease.consumed'), dispose: () => events.push('lease.disposed') }, { reserve: async () => { events.push('broker.reserved'); return { reservationId: 'credential-reservation-1' }; }, activate: async value => { events.push(`broker.activated.${value.processRegistrationId}`); }, revoke: async () => { events.push('broker.revoked'); } }, () => 1_000);
  const base: CodexOwnedHost = { pid: 42, processRegistrationId: identity.processRegistrationId, cgroupIdentityDigest: identity.cgroupIdentityDigest, startTimeTokenDigest: '7'.repeat(64), identityVerified: true, stdin: new PassThrough(), stdout: new PassThrough(), stderr: new PassThrough(), closed };
  const owner: QualifiedCodexExecutionOwner = { prepare: async input => { events.push(`owner.prepare.${input.processRegistrationId}`); if (options.prepareError) throw options.prepareError; if (options.prepareFails) throw new Error('private prepare failure'); return { ...identity, ...options.prepare }; }, spawn: async input => { events.push(`owner.spawn.${input.processRegistrationId}`); if (options.spawnFails) throw new Error('private spawn failure'); if (options.spawnStalls) return new Promise<CodexOwnedHost>(() => undefined); return { ...base, ...options.host }; }, terminate: async input => { events.push(`owner.terminate.${input.processRegistrationId}`); }, enumerateResiduals: async input => { events.push(`owner.enumerate.${input.processRegistrationId}`); return options.residuals ?? 0; } };
  const faults: string[] = []; return { events, close, faults, credentials, cancelProcess: () => cancelProcess(), register: () => CodexProcessHost.register({ attempt, runtime, operation, credentials, owner, spawnTimeoutMs: 20, cleanupTimeoutMs: 20 }) };
}
test('binds the immutable governed attempt and release before register, prepare, credential activation, and spawn', async () => {
  const value = harness(); const host = value.register(); assert.equal(Object.isFrozen(host.binding), true); assert.deepEqual(host.binding, { schemaVersion: '1', attemptId: attempt.attemptId, authorityDigest: attempt.authorityDigest, taskRevisionDigest: attempt.taskRevisionDigest, repositoryBindingDigest: attempt.repositoryBindingDigest, privateRepoObjectId: attempt.privateRepoObjectId, worktreePolicy: attempt.worktreePolicy, releaseId: attempt.releaseId, target: attempt.target, binarySha256: runtime.release.binarySha256, linuxHelperSha256: runtime.release.linuxHelperSha256, qualificationProfileId: attempt.qualificationProfileId, spawnDeadlineMs: attempt.deadlines.spawnMs, cleanupDeadlineMs: attempt.deadlines.cleanupMs }); const stdio = await host.start(code => { value.faults.push(code); }); assert.ok(stdio.stdin); assert.deepEqual(value.events.slice(0, 9), ['process.registered','process.spawning','owner.prepare.process-1','broker.reserved','lease.consumed','broker.activated.process-1','owner.spawn.process-1','process.started','process.ready']);
  const terminate = host.terminateOwnedHost(); value.close({ exitClass: 'signal' }); await terminate; assert.equal(await host.enumerateResiduals(), 0); assert.deepEqual(value.faults, []); for (const event of ['broker.revoked','lease.disposed','owner.terminate.process-1','process.exited.signal','owner.enumerate.process-1','process.cleaned']) assert.equal(value.events.filter(item => item === event).length, 1); assert.ok(value.events.indexOf('broker.revoked') < value.events.indexOf('owner.terminate.process-1')); assert.ok(value.events.indexOf('owner.enumerate.process-1') < value.events.indexOf('process.cleaned'));
});
test('refuses registration and every substituted scope or spawned identity before accepting stdio', async () => {
  const registration = harness({ registrationFails: true }); assert.throws(() => registration.register(), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_PROCESS_REGISTRATION_FAILED'); assert.equal(registration.events.includes('owner.prepare.process-1'), false); assert.equal(registration.events.includes('lease.disposed'), true);
  for (const options of [{ prepare: { processRegistrationId: 'process-2' } }, { prepare: { cgroupIdentityDigest: 'bad' } }, { host: { processRegistrationId: 'process-2' } }, { host: { cgroupIdentityDigest: '8'.repeat(64) } }, { host: { startTimeTokenDigest: 'bad' } }, { host: { identityVerified: false } }]) { const value = harness(options); await assert.rejects(value.register().start(() => undefined), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_CONFINEMENT_UNVERIFIED'); assert.equal(value.events.includes('process.cleaned'), true); assert.ok(value.events.indexOf('lease.disposed') < value.events.indexOf('owner.terminate.process-1')); }
});
test('cleans preparation, spawn, and timeout failures without leaving a credential or process reservation', async () => {
  const prepared = harness({ prepareFails: true }); await assert.rejects(prepared.register().start(() => undefined), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_PROCESS_START_FAILED'); assert.deepEqual(prepared.events.slice(-4), ['lease.disposed','owner.terminate.process-1','owner.enumerate.process-1','process.cleaned']);
  const failed = harness({ spawnFails: true }); await assert.rejects(failed.register().start(() => undefined), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_PROCESS_START_FAILED'); assert.equal(failed.events.includes('broker.revoked'), true); assert.equal(failed.events.includes('process.cleaned'), true);
  const timeout = harness({ spawnStalls: true }); await assert.rejects(timeout.register().start(() => undefined), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_SPAWN_TIMEOUT'); assert.equal(timeout.events.includes('process.cleaned'), true);
});
test('routes unexpected close and leaves residual cleanup externally provable', async () => {
  const unexpected = harness({ residuals: 2 }); const host = unexpected.register(); await host.start(code => { unexpected.faults.push(code); }); unexpected.close({ exitClass: 'zero' }); await new Promise(resolve => setImmediate(resolve)); assert.deepEqual(unexpected.faults, ['CODEX_HOST_EXITED']); assert.equal(await host.enumerateResiduals(), 2); assert.equal(unexpected.events.includes('process.cleaned'), false);
});
test('registered operation cancellation owns credential revocation and process termination', async () => {
  const value = harness(); const host = value.register(); await host.start(() => undefined); const cancelled = value.cancelProcess(); value.close({ exitClass: 'signal' }); await cancelled; assert.ok(value.events.indexOf('broker.revoked') < value.events.indexOf('owner.terminate.process-1'));
});
test('normalizes every hostile logical process transition and still proves external cleanup', async () => {
  for (const logicalFault of ['spawning','started','ready'] as const) { const value = harness({ logicalFault }); await assert.rejects(value.register().start(() => undefined), error => error instanceof CodexProcessHostFault && ['CODEX_PROCESS_START_FAILED','CODEX_CLEANUP_FAILED'].includes(error.code)); assert.equal(value.events.includes('owner.terminate.process-1'), true); assert.equal(value.events.includes('owner.enumerate.process-1'), true); }
  const failed = harness({ logicalFault: 'failed', spawnFails: true }); await assert.rejects(failed.register().start(() => undefined), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_PROCESS_START_FAILED'); assert.equal(failed.events.includes('process.failed'), true); assert.equal(failed.events.includes('owner.terminate.process-1'), true); assert.equal(failed.events.includes('owner.enumerate.process-1'), true);
  const exited = harness({ logicalFault: 'exited' }); const exitedHost = exited.register(); await exitedHost.start(() => undefined); const terminating = exitedHost.terminateOwnedHost(); exited.close({ exitClass: 'signal' }); await terminating; await assert.rejects(exitedHost.enumerateResiduals(), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_CLEANUP_FAILED'); assert.equal(exited.events.includes('owner.enumerate.process-1'), true);
  const cleanup = harness({ logicalFault: 'cleanup' }); const cleanupHost = cleanup.register(); await cleanupHost.start(() => undefined); const cleanupTermination = cleanupHost.terminateOwnedHost(); cleanup.close({ exitClass: 'signal' }); await cleanupTermination; await assert.rejects(cleanupHost.enumerateResiduals(), error => error instanceof CodexProcessHostFault && error.code === 'CODEX_CLEANUP_FAILED'); assert.equal(cleanup.events.includes('owner.enumerate.process-1'), true); assert.equal(cleanup.events.includes('process.failed'), true);
});
test('does not expose private owner failures in supervision logs', async () => {
  const canary = `codex-host-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values));
  try { const value = harness({ prepareError: new Error(canary) }); await assert.rejects(value.register().start(() => undefined)); assert.equal(logs.join('\n').includes(canary), false); }
  finally { console.error = original; }
});
