import assert from 'node:assert/strict'; import test from 'node:test';
import type { OpaqueCredentialLease } from '@kogg/agents/lib/common/agents-protocol'; import type { GovernedCodexAttemptV1 } from '../common/codex-protocol';
import { CodexCredentialFault, CodexCredentialReservation, type CodexCredentialActivation, type CodexCredentialBinding, type CodexCredentialBrokerAuthority } from './codex-credential-reservation';

// diagnostic-coverage: codex.credentials, codex.processes, codex.cleanup, codex.recovery, codex.source-maps
const attempt: GovernedCodexAttemptV1 = { schemaVersion: '1', attemptId: '10000000-0000-4000-8000-000000000001', taskRevisionDigest: '1'.repeat(64), repositoryBindingDigest: '2'.repeat(64), privateRepoObjectId: '20000000-0000-4000-8000-000000000001', baseCommit: '3'.repeat(40), worktreePolicy: 'private-writable', roleRevisionId: 'role-1', provider: 'openai', model: 'gpt-5', releaseId: 'codex-release-1', target: 'x86_64-unknown-linux-musl', qualificationProfileId: 'kogg-writable-agent-v1', deadlinePolicyId: 'interactive-v1', budgets: { inputTokens: '1000', outputTokens: '2000', toolCalls: '10', bytesIn: '100000', bytesOut: '200000' }, deadlines: { spawnMs: 20000, initializeMs: 30000, threadStartMs: 30000, firstActivityMs: 60000, idleMs: 120000, providerRequestMs: 120000, interruptMs: 10000, cleanupMs: 10000, absoluteMs: 600000 }, authorityDigest: '4'.repeat(64) };
function fixture(overrides: Partial<CodexCredentialBrokerAuthority> = {}, leaseOverrides: Partial<OpaqueCredentialLease> = {}, now = { value: 1_000 }) {
  const events: string[] = []; let capturedBinding: CodexCredentialBinding | undefined; let capturedActivation: CodexCredentialActivation | undefined;
  const lease: OpaqueCredentialLease = { leaseId: 'lease-1', expiresAt: new Date(1_000_000).toISOString(), consume: () => events.push('lease.consumed'), dispose: () => events.push('lease.disposed'), ...leaseOverrides };
  const authority: CodexCredentialBrokerAuthority = { reserve: async value => { events.push('broker.reserved'); capturedBinding = value; return { reservationId: 'reservation-1' }; }, activate: async value => { events.push('broker.activated'); capturedActivation = value; }, revoke: async reservationId => { events.push(`broker.revoked.${reservationId}`); }, ...overrides };
  return { events, binding: () => capturedBinding, activation: () => capturedActivation, reservation: () => new CodexCredentialReservation(attempt, lease, authority, () => now.value), now };
}
test('binds the complete governed attempt without a bearer, activates one registered cgroup, and revokes once', async () => {
  const value = fixture(); const reservation = value.reservation(); await reservation.reserve(); await reservation.reserve(); const expectedExpiry = new Date(601_000).toISOString(); assert.deepEqual(value.binding(), { schemaVersion: '1', attemptId: attempt.attemptId, authorityDigest: attempt.authorityDigest, taskRevisionDigest: attempt.taskRevisionDigest, repositoryBindingDigest: attempt.repositoryBindingDigest, privateRepoObjectId: attempt.privateRepoObjectId, worktreePolicy: attempt.worktreePolicy, releaseId: attempt.releaseId, target: attempt.target, qualificationProfileId: attempt.qualificationProfileId, provider: 'openai', model: attempt.model, requestDirection: 'openai-outbound', credentialLeaseId: 'lease-1', maximumRequestCount: 64, inputTokenCeiling: '1000', outputTokenCeiling: '2000', toolCallCeiling: '10', bytesInCeiling: '100000', bytesOutCeiling: '200000', expiresAt: expectedExpiry }); assert.equal(Object.isFrozen(reservation.binding), true); assert.equal(JSON.stringify(reservation).includes('bearer'), false);
  await reservation.activate('process-1', '5'.repeat(64)); assert.deepEqual(value.activation(), { reservationId: 'reservation-1', processRegistrationId: 'process-1', cgroupIdentityDigest: '5'.repeat(64) }); await reservation.revoke(); await reservation.revoke(); assert.deepEqual(value.events, ['broker.reserved','lease.consumed','broker.activated','broker.revoked.reservation-1','lease.disposed']); assert.deepEqual(reservation.diagnostics(), { reserved: true, active: false, revoked: true, failed: false });
});
test('refuses activation before reservation and invalid or expired process identities while disposing exactly once', async () => {
  const before = fixture(); const first = before.reservation(); await assert.rejects(first.activate('process-1', '5'.repeat(64)), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(before.events, ['lease.disposed']);
  for (const [processId, cgroup] of [['INVALID SPACE','5'.repeat(64)], ['process-1','invalid']] as const) { const value = fixture(); const reservation = value.reservation(); await reservation.reserve(); await assert.rejects(reservation.activate(processId, cgroup), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(value.events, ['broker.reserved','broker.revoked.reservation-1','lease.disposed']); }
  const expired = fixture({}, {}, { value: 1_000 }); const reservation = expired.reservation(); await reservation.reserve(); expired.now.value = 700_000; await assert.rejects(reservation.activate('process-1', '5'.repeat(64)), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(expired.events, ['broker.reserved','broker.revoked.reservation-1','lease.disposed']);
});
test('reserve, activation, and revoke failures stay closed and always dispose the shared lease', async () => {
  const canary = `codex-broker-${Date.now()}`; const logs: string[] = []; const original = console.error; console.error = (...values: unknown[]) => logs.push(JSON.stringify(values));
  try {
    const refused = fixture({ reserve: async () => { throw new Error(canary); } }); await assert.rejects(refused.reservation().reserve(), error => error instanceof CodexCredentialFault && error.code === 'CODEX_CREDENTIAL_LEASE_REFUSED'); assert.deepEqual(refused.events, ['lease.disposed']);
    const malformed = fixture({ reserve: async () => ({ reservationId: 'reservation-1', extra: canary } as never) }); await assert.rejects(malformed.reservation().reserve(), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(malformed.events, ['lease.disposed']);
    const activation = fixture({ activate: async () => { throw new Error(canary); } }); const active = activation.reservation(); await active.reserve(); await assert.rejects(active.activate('process-1', '5'.repeat(64)), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(activation.events, ['broker.reserved','lease.consumed','broker.revoked.reservation-1','lease.disposed']);
    const revoke = fixture({ revoke: async () => { throw new Error(canary); } }); const revoking = revoke.reservation(); await revoking.reserve(); await assert.rejects(revoking.revoke(), error => error instanceof CodexCredentialFault && error.code === 'CODEX_CREDENTIAL_REVOKED'); assert.deepEqual(revoke.events, ['broker.reserved','lease.disposed']); assert.equal(logs.join('\n').includes(canary), false);
  } finally { console.error = original; }
});
test('invalid leases and abandoned unreserved grants dispose once without calling the broker', () => {
  for (const lease of [{ leaseId: 'INVALID SPACE' }, { expiresAt: 'invalid' }, { expiresAt: new Date(999).toISOString() }]) { const value = fixture({}, lease); assert.throws(() => value.reservation(), /CODEX_CREDENTIAL_LEASE_REFUSED/u); assert.deepEqual(value.events, ['lease.disposed']); }
  const value = fixture(); const reservation = value.reservation(); reservation.abandon(); reservation.abandon(); assert.deepEqual(value.events, ['lease.disposed']); assert.deepEqual(reservation.diagnostics(), { reserved: false, active: false, revoked: true, failed: false });
});
