import { existsSync, promises as fs } from 'node:fs';
import path from 'node:path';
import { DatabaseSync, type SQLOutputValue } from 'node:sqlite';
import { BackendApplicationContribution } from '@theia/core/lib/node';
import { inject, injectable, unmanaged } from '@theia/core/shared/inversify';
import type { KoggVerdictMergeService, VerdictExplanationResultV1, VerdictExplanationV1, VerdictMergeSafeCode } from '../common/verdict-merge-protocol';
import { canonicalJson, decodeVerdictQuery, validateExplanation, VerdictMergeProtocolError, verdictMergeDigest } from '../common/verdict-merge-canonical';
import { VerdictProjectionAuthority } from './verdict-projection-authority';

// Persists only closed safe query/explanation projections. Raw Ranex evidence, journal bodies, paths, refs, object ids, and identities never enter logs.
// diagnostic-coverage: verdict.provenance, verdict.bindings, verdict.currentness, verdict.explanation, merge.authorization, merge.preflight, merge.processes, merge.atomicity, merge.recovery, merge.source-maps
type Row = Record<string, SQLOutputValue>;
@injectable()
export class VerdictMergeService implements KoggVerdictMergeService, BackendApplicationContribution {
  private database: DatabaseSync | undefined;
  constructor(@inject(VerdictProjectionAuthority) private readonly authority: VerdictProjectionAuthority, @unmanaged() private readonly databasePath = path.join(stateRoot(), 'verdict-merge', 'registry.sqlite3')) {}
  async onStart(): Promise<void> { console.info('[kogg:verdict:service] recovery.started'); try { await fs.mkdir(path.dirname(this.databasePath), { recursive: true, mode: 0o700 }); this.database = new DatabaseSync(this.databasePath, { enableForeignKeyConstraints: true, enableDoubleQuotedStringLiterals: false, allowExtension: false }); this.database.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA trusted_schema=OFF; PRAGMA busy_timeout=5000;'); this.migrate(); this.assertIntegrity(); if (process.platform !== 'win32') await fs.chmod(this.databasePath, 0o600); console.info('[kogg:verdict:service] recovery.completed', { explanationCount: this.count() }); } catch (error) { this.database?.close(); this.database = undefined; console.error('[kogg:verdict:service] recovery.failed', { errorType: error instanceof Error ? error.name : 'UnknownError', safeCode: 'STORE_INTEGRITY_FAILED' }); throw new Error('STORE_INTEGRITY_FAILED'); } }
  onStop(): void { console.info('[kogg:verdict:service] shutdown.started'); this.database?.close(); this.database = undefined; console.info('[kogg:verdict:service] shutdown.completed'); }
  async explain(input: unknown): Promise<VerdictExplanationResultV1> {
    let requestId = 'invalid'; let queryId = 'invalid';
    try { const query = decodeVerdictQuery(input); requestId = query.requestId; queryId = query.queryId; const queryDigest = verdictMergeDigest('query', query); console.info('[kogg:verdict:service] explanation.requested', { requestId, queryId });
      const replay = this.db().prepare('SELECT query_digest,result_json FROM requests WHERE request_id=?').get(requestId) as Row | undefined; if (replay) { if (text(replay,'query_digest') !== queryDigest) return this.refused(requestId, queryId, 'REQUEST_CONFLICT'); const result = JSON.parse(text(replay,'result_json')) as VerdictExplanationResultV1; return result.kind === 'completed' ? { ...result, replay: true } : result; }
      console.info('[kogg:verdict:service] verification.started', { requestId, queryId }); const projection = await this.authority.explain(query, queryDigest);
      if (!projection) { const result = this.refused(requestId, queryId, 'VERDICT_UNKNOWN'); this.storeRequest(requestId, queryDigest, canonicalJson(query), result); return result; }
      const explanation = validateExplanation(projection, query, queryDigest); const safeCode = outcome(explanation); const result: VerdictExplanationResultV1 = { kind: 'completed', safeCode, explanation, replay: false };
      this.transaction(() => { this.db().prepare('INSERT INTO explanations(explanation_id,query_digest,explanation_digest,explanation_json,created_at) VALUES(?,?,?,?,?)').run(explanation.explanationId, queryDigest, explanation.explanationDigest, canonicalJson(explanation), explanation.verifiedAt); this.db().prepare('INSERT INTO requests(request_id,query_digest,query_json,result_json) VALUES(?,?,?,?)').run(requestId, queryDigest, canonicalJson(query), JSON.stringify(result)); });
      console.info('[kogg:verdict:currentness]', explanation.currentness, { requestId, queryId, safeCode }); console.info('[kogg:verdict:service] explanation.completed', { requestId, queryId, safeCode, gateCount: explanation.gateRows.length }); return result;
    } catch (error) { /* observability-exempt: refused logs the closed failure code and safe request identifiers for this path. */ const safeCode: VerdictMergeSafeCode = error instanceof VerdictMergeProtocolError ? 'PROTOCOL_INVALID' : error instanceof Error && error.message === 'STORE_INTEGRITY_FAILED' ? 'STORE_INTEGRITY_FAILED' : 'INTERNAL_FAILURE'; return this.refused(requestId, queryId, safeCode); }
  }
  diagnostics() { this.assertIntegrity(); const explanationCount = this.count(); const sourceMapsPresent = existsSync(`${__filename}.map`) && existsSync(path.join(__dirname, 'verdict-projection-authority.js.map')); return { integrity: true, explanationCount, provenanceReady: explanationCount > 0, bindingsReady: explanationCount > 0, currentnessReady: explanationCount > 0, explanationReady: explanationCount > 0, authorizationReady: false, preflightReady: false, processCount: 0, residualProcessCount: 0, atomicityReady: false, recoveryReady: true, sourceMapsPresent }; }
  private refused(requestId: string, queryId: string, safeCode: VerdictMergeSafeCode): VerdictExplanationResultV1 { console.warn('[kogg:verdict:currentness] unknown', { requestId, queryId, safeCode }); console.warn('[kogg:verdict:service] explanation.refused', { requestId, queryId, safeCode }); return { kind: 'refused', safeCode }; }
  private storeRequest(requestId: string, queryDigest: string, queryJson: string, result: VerdictExplanationResultV1): void { this.db().prepare('INSERT INTO requests(request_id,query_digest,query_json,result_json) VALUES(?,?,?,?)').run(requestId, queryDigest, queryJson, JSON.stringify(result)); }
  private migrate(): void { this.db().exec('CREATE TABLE IF NOT EXISTS requests(request_id TEXT PRIMARY KEY,query_digest TEXT NOT NULL,query_json TEXT NOT NULL,result_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS explanations(explanation_id TEXT PRIMARY KEY,query_digest TEXT NOT NULL UNIQUE,explanation_digest TEXT NOT NULL UNIQUE,explanation_json TEXT NOT NULL,created_at TEXT NOT NULL);'); const requestColumns = new Set((this.db().prepare('PRAGMA table_info(requests)').all() as Row[]).map(row => text(row, 'name'))); if (!requestColumns.has('query_json')) this.db().exec("ALTER TABLE requests ADD COLUMN query_json TEXT NOT NULL DEFAULT ''"); this.db().exec(`CREATE TRIGGER IF NOT EXISTS verdict_requests_update BEFORE UPDATE ON requests BEGIN SELECT RAISE(ABORT,'immutable'); END; CREATE TRIGGER IF NOT EXISTS verdict_requests_delete BEFORE DELETE ON requests BEGIN SELECT RAISE(ABORT,'immutable'); END; CREATE TRIGGER IF NOT EXISTS verdict_explanations_update BEFORE UPDATE ON explanations BEGIN SELECT RAISE(ABORT,'immutable'); END; CREATE TRIGGER IF NOT EXISTS verdict_explanations_delete BEFORE DELETE ON explanations BEGIN SELECT RAISE(ABORT,'immutable'); END;`); }
  private assertIntegrity(): void { try { this.verifyIntegrity(); } catch { /* observability-exempt: Normalize closed parser and storage failures; startup and request callers log the safe refusal. */ throw new Error('STORE_INTEGRITY_FAILED'); } }
  private verifyIntegrity(): void {
    if (text(this.db().prepare('PRAGMA quick_check').get() as Row,'quick_check') !== 'ok' || Number((this.db().prepare("SELECT count(*) AS count FROM sqlite_master WHERE type='trigger' AND name LIKE 'verdict_%'").get() as Row).count) !== 4) throw new Error('integrity');
    const queries = new Map<string, ReturnType<typeof decodeVerdictQuery>>(); const results = new Map<string, VerdictExplanationResultV1>();
    for (const row of this.db().prepare('SELECT * FROM requests').all() as Row[]) { const query = decodeVerdictQuery(JSON.parse(text(row,'query_json')) as unknown); const digest = verdictMergeDigest('query', query); if (digest !== text(row,'query_digest') || query.requestId !== text(row,'request_id')) throw new Error('query'); queries.set(digest, query); results.set(digest, decodeStoredResult(JSON.parse(text(row, 'result_json')) as unknown)); }
    const explanations = new Map<string, VerdictExplanationV1>();
    for (const row of this.db().prepare('SELECT * FROM explanations').all() as Row[]) { const stored = JSON.parse(text(row,'explanation_json')) as VerdictExplanationV1; const digest = text(row,'query_digest'); const query = queries.get(digest); if (!query) throw new Error('orphan'); const { explanationDigest: _storedDigest, ...body } = stored; const validated = validateExplanation(body, query, digest); if (validated.explanationDigest !== text(row,'explanation_digest') || validated.explanationId !== text(row,'explanation_id') || canonicalJson(validated) !== canonicalJson(stored)) throw new Error('explanation'); explanations.set(digest, validated); }
    for (const [digest, result] of results) { if (result.kind === 'completed') { const explanation = explanations.get(digest); if (!explanation || result.replay || result.safeCode !== outcome(explanation) || canonicalJson(result.explanation) !== canonicalJson(explanation)) throw new Error('result'); } else if (result.kind !== 'refused' || result.safeCode !== 'VERDICT_UNKNOWN') throw new Error('refusal'); }
    if (explanations.size !== [...results.values()].filter(result => result.kind === 'completed').length) throw new Error('unreferenced');
  }
  private transaction(action: () => void): void { this.db().exec('BEGIN IMMEDIATE'); try { action(); this.db().exec('COMMIT'); } catch (error) { try { this.db().exec('ROLLBACK'); } catch { /* observability-exempt: original closed refusal remains authoritative. */ } throw error; } }
  private count(): number { return Number((this.db().prepare('SELECT count(*) AS count FROM explanations').get() as Row).count); }
  private db(): DatabaseSync { if (!this.database) throw new Error('STORE_INTEGRITY_FAILED'); return this.database; }
}
function text(row: Row, key: string): string { const value = row[key]; if (typeof value !== 'string') throw new Error('STORE_INTEGRITY_FAILED'); return value; }
function decodeStoredResult(input: unknown): VerdictExplanationResultV1 { if (!input || typeof input !== 'object') throw new Error('result'); const value = input as Record<string, unknown>; const keys = Object.keys(value).sort().join(','); if (value.kind === 'refused' && keys === 'kind,safeCode' && value.safeCode === 'VERDICT_UNKNOWN') return value as unknown as VerdictExplanationResultV1; if (value.kind === 'completed' && keys === 'explanation,kind,replay,safeCode' && value.replay === false && ['VERDICT_OK','VERDICT_FAIL','VERDICT_BLOCKED','VERDICT_STALE','VERDICT_UNKNOWN'].includes(String(value.safeCode))) return value as unknown as VerdictExplanationResultV1; throw new Error('result'); }
function outcome(value: VerdictExplanationV1): 'VERDICT_OK'|'VERDICT_FAIL'|'VERDICT_BLOCKED'|'VERDICT_STALE'|'VERDICT_UNKNOWN' { if (value.currentness === 'stale') return 'VERDICT_STALE'; if (value.currentness === 'unknown') return 'VERDICT_UNKNOWN'; return value.ranexDecision === 'pass' ? 'VERDICT_OK' : value.ranexDecision === 'fail' ? 'VERDICT_FAIL' : 'VERDICT_BLOCKED'; }
function stateRoot(): string { return path.resolve(process.env.KOGG_STATE_DIR ?? path.join(process.cwd(), '.kogg', 'state')); }
