import { MessageService } from '@theia/core';
import { BaseWidget } from '@theia/core/lib/browser/widgets/widget';
import { inject, injectable, postConstruct } from '@theia/core/shared/inversify';
import { KoggAgentsService, type AgentMutationResult, type AgentRegistrySnapshot, type AttemptProjectionV1, type KoggAgentsService as AgentsService } from '../common/agents-protocol';
import { AgentsClient } from './agents-client';

// diagnostic-coverage: agents.adapters, agents.attempts, agents.processes, agents.recovery, agents.logging, agents.source-maps

@injectable()
export class AgentsWidget extends BaseWidget {
  static readonly ID = 'kogg-agents'; static readonly LABEL = 'Kogg Agents';
  private snapshotValue: AgentRegistrySnapshot = { schemaVersion: '1', registryRevision: '0', admission: 'recovering', roles: [], attempts: [], adapters: [] };
  private status = 'Loading agent registry…'; private busy = false; private editBuffer: Record<string, string> = {};
  constructor(@inject(KoggAgentsService) private readonly service: AgentsService,
    @inject(AgentsClient) client: AgentsClient, @inject(MessageService) private readonly messages: MessageService) {
    super(); client.listen(snapshot => { this.snapshotValue = snapshot; this.status = 'Agent registry updated.'; this.render(); });
  }
  @postConstruct() protected init(): void { this.id = AgentsWidget.ID; this.title.label = AgentsWidget.LABEL; this.title.caption = 'Governed role revisions and agent attempts'; this.title.closable = true; this.addClass('kogg-agents-widget'); this.render(); void this.refresh(); }

  private render(): void {
    const roles = this.snapshotValue.roles.map(role => `<option value="${html(role.roleRevisionId)}">${html(role.roleKey)} · r${html(role.roleRevision)}</option>`).join('');
    const adapters = this.snapshotValue.adapters.map(adapter => `<option value="${html(adapter.adapterKey)}@${html(adapter.adapterVersion)}">${html(adapter.adapterKey)} @ ${html(adapter.adapterVersion)}</option>`).join('');
    const attempts = this.snapshotValue.attempts.map(attempt => this.attempt(attempt)).join('');
    this.node.innerHTML = `<div class="kogg-panel"><header><h2>Kogg Agents</h2><p>Immutable roles and backend-owned provider attempts.</p></header>
      <p role="status" aria-live="polite"><strong>Status:</strong> ${html(this.status)}</p><p>Admission: ${html(this.snapshotValue.admission)} · registry r${html(this.snapshotValue.registryRevision)}</p>
      <section><h3>Role Revisions</h3><form data-role class="kogg-form-grid"><label>Role key<input name="roleKey" required value="${html(this.editBuffer.roleKey ?? 'implementer')}"></label><label>Display name<input name="displayName" required value="${html(this.editBuffer.displayName ?? 'Implementer')}"></label><label>Capabilities<input name="capabilities" value="${html(this.editBuffer.capabilities ?? 'provider-turn')}"></label><label>Tool policies<input name="tools" value="${html(this.editBuffer.tools ?? 'read-only')}"></label><label>Provider IDs<input name="providers" required value="${html(this.editBuffer.providers ?? 'kogg.fixture')}"></label><label>Model IDs<input name="models" required value="${html(this.editBuffer.models ?? 'fixture.echo')}"></label><label>Adapter capabilities<input name="adapterCapabilities" value="${html(this.editBuffer.adapterCapabilities ?? 'provider-turn')}"></label><label>Budget policy<input name="budget" required value="${html(this.editBuffer.budget ?? 'fixture-budget')}"></label><button${this.busy ? ' disabled' : ''}>Save immutable revision</button></form><ul>${this.snapshotValue.roles.map(role => `<li>${html(role.roleKey)} · ${html(role.roleRevisionId)}</li>`).join('') || '<li>None</li>'}</ul></section>
      <section><h3>Start Attempt</h3><form data-start class="kogg-form-grid"><label>Task admission ID<input name="admissionId" required></label><label>Role revision<select name="roleRevisionId">${roles}</select></label><label>Exact adapter and version<input name="adapter" list="kogg-agent-adapters" required value="${this.snapshotValue.adapters[0] ? html(`${this.snapshotValue.adapters[0].adapterKey}@${this.snapshotValue.adapters[0].adapterVersion}`) : ''}"><datalist id="kogg-agent-adapters">${adapters}</datalist></label><label>Provider<input name="providerId" required value="kogg.fixture"></label><label>Model<input name="modelId" required value="fixture.echo"></label><label>Deadline policy<input name="deadlinePolicyId" required value="interactive-v1"></label><button${this.busy || !roles || !adapters || this.snapshotValue.admission !== 'enabled' ? ' disabled' : ''}>Confirm and start exact attempt</button></form></section>
      <section><h3>Attempts</h3><button data-refresh>Refresh</button><ul>${attempts || '<li>None</li>'}</ul></section></div>`;
    this.node.querySelector<HTMLFormElement>('[data-role]')?.addEventListener('submit', event => { event.preventDefault(); void this.createRole(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLFormElement>('[data-start]')?.addEventListener('submit', event => { event.preventDefault(); void this.start(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector('[data-refresh]')?.addEventListener('click', () => void this.refresh());
    this.node.querySelectorAll<HTMLElement>('[data-cancel]').forEach(button => button.addEventListener('click', () => void this.cancel(button.dataset.cancel!)));
  }
  private attempt(value: AttemptProjectionV1): string { const terminal = value.terminalCode ? ` · ${html(value.terminalCode)}` : ''; const cancellable = !['cleaned', 'cleanup_failed', 'recovered_terminal', 'unverified_residual'].includes(value.state); return `<li data-attempt="${html(value.attemptId)}">${html(value.attemptId.slice(0, 8))} · ${html(value.state)}${terminal} · ${html(value.adapterKey)}@${html(value.adapterVersion)} · resources ${html(value.ownedResourceCount)}${cancellable ? ` <button data-cancel="${html(value.attemptId)}">Cancel</button>` : ''}</li>`; }
  private async refresh(): Promise<void> { await this.run(async () => { this.snapshotValue = await this.service.subscribe(); this.status = 'Agent registry ready.'; }); }
  private async createRole(data: FormData): Promise<void> { for (const key of ['roleKey', 'displayName', 'capabilities', 'tools', 'providers', 'models', 'adapterCapabilities', 'budget']) this.editBuffer[key] = String(data.get(key) ?? ''); await this.run(async () => { const result = await this.service.createRoleRevision({ schemaVersion: '1', requestId: crypto.randomUUID(), expectedRegistryRevision: this.snapshotValue.registryRevision, roleKey: String(data.get('roleKey')), displayName: String(data.get('displayName')), authority: { capabilityIds: list(data.get('capabilities')), toolPolicyIds: list(data.get('tools')), mayCreateChildren: false, permittedChildRoleKeys: [], maxChildDepth: '0', maxDirectChildren: '0' }, providerPolicy: { permittedProviderIds: list(data.get('providers')), permittedModelIds: list(data.get('models')), requiredAdapterCapabilities: list(data.get('adapterCapabilities')) }, budgetPolicyId: String(data.get('budget')) }); this.accept(result, 'Immutable role revision saved.'); if (result.kind === 'completed') this.editBuffer = {}; this.snapshotValue = await this.service.snapshot(); }); }
  private async start(data: FormData): Promise<void> { const [adapterKey, adapterVersion] = String(data.get('adapter')).split('@'); await this.run(async () => { const result = await this.service.startAttempt({ schemaVersion: '1', requestId: crypto.randomUUID(), expectedRegistryRevision: this.snapshotValue.registryRevision, taskAdmissionId: String(data.get('admissionId')), roleRevisionId: String(data.get('roleRevisionId')), providerId: String(data.get('providerId')), modelId: String(data.get('modelId')), adapterKey: adapterKey!, adapterVersion: adapterVersion!, deadlinePolicyId: String(data.get('deadlinePolicyId')) }); this.accept(result, 'Attempt registered and starting.'); this.snapshotValue = await this.service.snapshot(); }); }
  private async cancel(attemptId: string): Promise<void> { const attempt = this.snapshotValue.attempts.find(value => value.attemptId === attemptId); if (!attempt) return; await this.run(async () => { const result = await this.service.cancelAttempt({ schemaVersion: '1', requestId: crypto.randomUUID(), expectedRegistryRevision: this.snapshotValue.registryRevision, expectedAttemptRevision: attempt.attemptRevision, attemptId, reason: 'user' }); this.accept(result, 'Cancel requested.'); this.snapshotValue = await this.service.snapshot(); }); }
  private accept(result: AgentMutationResult, success: string): void { if (result.kind !== 'completed') throw new UiError(result.code); this.status = success; }
  private async run(action: () => Promise<void>): Promise<void> { this.busy = true; this.render(); try { await action(); } catch (error) { const code = error instanceof UiError ? error.code : 'AGENT_INTERNAL_FAILURE'; this.status = message(code); console.error('[kogg:agents:registry] frontend.operation.failed', { safeCode: code, errorType: error instanceof Error ? error.name : 'UnknownError' }); void this.messages.error(this.status); } finally { this.busy = false; this.render(); } }
}
class UiError extends Error { constructor(readonly code: string) { super(code); } }
function list(value: FormDataEntryValue | null): string[] { return String(value ?? '').split(',').map(item => item.trim()).filter(Boolean); }
function html(value: string): string { return value.replace(/[&<>'"]/gu, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]!); }
function message(code: string): string { const messages: Record<string, string> = { REGISTRY_REVISION_CONFLICT: 'The agent registry changed elsewhere. Your role edits remain available.', ATTEMPT_REVISION_CONFLICT: 'The attempt changed elsewhere. Refresh before cancelling.', REQUEST_ID_REUSED: 'This request identity was reused for a different action.', ADAPTER_UNAVAILABLE: 'The exact adapter is unavailable; no fallback was used.', ADAPTER_RESOLUTION_AMBIGUOUS: 'More than one exact adapter mapping exists.', TASK_AUTHORITY_STALE: 'The approved task admission is stale or missing.', RECOVERY_REQUIRED: 'Agent recovery must complete before a new attempt starts.' }; return messages[code] ?? `The agent operation failed safely (${code}).`; }
