import { MessageService } from '@theia/core';
import { BaseWidget } from '@theia/core/lib/browser/widgets/widget';
import { inject, injectable, postConstruct } from '@theia/core/shared/inversify';
import { KoggProjectsService, type KoggProjectsService as ProjectsService } from '@kogg/projects/lib/common/projects-protocol';
import { EDITABLE_NODE_KINDS, KoggWorkflowService, type EditableNodeKind, type EditableWorkflowGraphV1, type EditableWorkflowNodeV1, type KoggWorkflowService as WorkflowService, type WorkflowAuthorityEffect, type WorkflowNodeConfigurationV1, type WorkflowTemplateVersionProjection } from '../common/workflow-protocol';
import { buildLinearGraph, moveOutlineNode } from '../common/workflow-outline';

// diagnostic-coverage: workflow.schema, workflow.graph, workflow.authority, workflow.accessibility, workflow.source-maps

const PENDING_CONFIGURATION_DIGEST = '0'.repeat(64);
const GRANTS: Readonly<Record<EditableNodeKind, readonly WorkflowAuthorityEffect[]>> = {
  'research.agent': ['read-repository','invoke-provider'], 'pseudocode.agent': ['read-repository','mutate-private-repository','invoke-provider'],
  'probe.agent': ['read-repository','mutate-private-repository','invoke-provider','run-tool'], 'implementation.agent': ['read-repository','mutate-private-repository','invoke-provider','run-tool'],
  'tool.git': ['read-repository','mutate-private-repository','run-tool'], 'tool.build': ['read-repository','run-tool'],
  'check.deterministic': ['read-repository','run-tool','record-check'], 'approval.specification': ['record-approval'], 'approval.continue': ['record-approval'],
  'control.condition': [], 'control.parallel': [], 'control.join': [], 'control.group': [], 'control.finally': []
};

@injectable()
export class WorkflowEditorWidget extends BaseWidget {
  static readonly ID = 'kogg-workflow-editor'; static readonly LABEL = 'Kogg Workflow Editor';
  private projectId: string | undefined; private templateId: string = crypto.randomUUID();
  private nodes: EditableWorkflowNodeV1[] = [node('research.agent'), node('implementation.agent')]; private edgeIds = [crypto.randomUUID()];
  private versions: readonly WorkflowTemplateVersionProjection[] = []; private status = 'Loading workflow editor…'; private busy = false; private view: 'outline' | 'canvas' = 'outline'; private selectedNodeId = this.nodes[0]!.nodeId;

  constructor(@inject(KoggWorkflowService) private readonly service: WorkflowService,
    @inject(KoggProjectsService) private readonly projects: ProjectsService,
    @inject(MessageService) private readonly messages: MessageService) { super(); }

  @postConstruct() protected init(): void {
    this.id = WorkflowEditorWidget.ID; this.title.label = WorkflowEditorWidget.LABEL; this.title.caption = 'Accessible governed workflow outline';
    this.title.closable = true; this.addClass('kogg-workflow-editor-widget'); this.render(); void this.load();
  }

  private async load(): Promise<void> {
    await this.run('editor.load', async () => {
      const projects = await this.projects.snapshot(); this.projectId = projects.activeProjectId;
      if (!this.projectId) { this.status = 'Open an active Kogg project before editing a workflow.'; return; }
      const projectVersions = await this.service.listProjectVersions(this.projectId); this.templateId = projectVersions.at(-1)?.templateId ?? crypto.randomUUID();
      this.versions = projectVersions.filter(version => version.templateId === this.templateId);
      this.status = this.versions.length ? `Workflow version ${this.versions.at(-1)!.versionNumber} is current.` : 'Structured workflow outline ready.';
    }, false);
  }

  private render(): void {
    const options = EDITABLE_NODE_KINDS.map(kind => `<option value="${kind}">${kind}</option>`).join('');
    const rows = this.nodes.map((item, index) => `<li data-workflow-node="${html(item.nodeId)}"><strong>${index + 1}. ${html(item.kind)}</strong><span> · ${item.requestedEffects.length} bounded effects · retry ${item.retry.maxAttempts}</span><div class="kogg-package-actions"><button data-select="${index}" aria-pressed="${item.nodeId === this.selectedNodeId}" ${this.busy ? 'disabled' : ''} aria-label="Configure ${html(item.kind)}">Configure</button><button data-up="${index}" ${this.busy || index === 0 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} up">Up</button><button data-down="${index}" ${this.busy || index === this.nodes.length - 1 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} down">Down</button><button data-remove="${index}" ${this.busy || this.nodes.length === 1 ? 'disabled' : ''} aria-label="Remove ${html(item.kind)}">Remove</button></div></li>`).join('');
    const canvas = this.nodes.map((item, index) => `<article role="listitem" tabindex="0" data-workflow-canvas-node="${html(item.nodeId)}"><span>Step ${index + 1}</span><strong>${html(item.kind)}</strong><p>${item.requestedEffects.length} bounded effects · retry ${item.retry.maxAttempts}</p><div class="kogg-package-actions"><button data-canvas-select="${index}" aria-pressed="${item.nodeId === this.selectedNodeId}" ${this.busy ? 'disabled' : ''} aria-label="Configure ${html(item.kind)} on canvas">Configure</button><button data-canvas-up="${index}" ${this.busy || index === 0 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} earlier on canvas">Earlier</button><button data-canvas-down="${index}" ${this.busy || index === this.nodes.length - 1 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} later on canvas">Later</button><button data-canvas-remove="${index}" ${this.busy || this.nodes.length === 1 ? 'disabled' : ''} aria-label="Remove ${html(item.kind)} from canvas">Remove</button></div></article>`).join('');
    const versions = this.versions.map(version => `<li data-workflow-version="${version.versionNumber}">Version ${version.versionNumber} · ${html(version.versionId.slice(0, 8))} · immutable</li>`).join('');
    const editor = this.view === 'outline' ? `<ol aria-label="Workflow node outline">${rows}</ol>` : `<div class="kogg-workflow-canvas" role="list" aria-label="Workflow spatial canvas">${canvas}</div>`;
    const selected = this.nodes.find(item => item.nodeId === this.selectedNodeId) ?? this.nodes[0]!; const configuration = selected.configuration ?? defaultConfiguration(selected.kind);
    const configurationForm = `<form data-config class="kogg-form-grid"><h3>Configure ${html(selected.kind)}</h3><label>Role revision ID<input name="roleRevisionId" value="${html(configuration.roleRevisionId ?? '')}"></label><label>Provider ID<input name="providerId" value="${html(configuration.providerId ?? '')}"></label><label>Model ID<input name="modelId" value="${html(configuration.modelId ?? '')}"></label><label>Adapter key<input name="adapterKey" value="${html(configuration.adapterKey ?? '')}"></label><label>Adapter version<input name="adapterVersion" value="${html(configuration.adapterVersion ?? '')}"></label><label>Deadline policy<input name="deadlinePolicyId" value="${html(configuration.deadlinePolicyId ?? '')}"></label><label>Absolute deadline (ms)<input name="absoluteDeadlineMs" inputmode="numeric" required value="${configuration.absoluteDeadlineMs}"></label><label>Target<select name="target"><option value="project-read-only"${configuration.target === 'project-read-only' ? ' selected' : ''}>Project read-only</option><option value="private-worktree"${configuration.target === 'private-worktree' ? ' selected' : ''}>Private worktree</option></select></label><label>Condition<select name="condition"><option value="always"${configuration.condition === 'always' ? ' selected' : ''}>Always</option><option value="prior-success"${configuration.condition === 'prior-success' ? ' selected' : ''}>Prior success</option><option value="prior-failure"${configuration.condition === 'prior-failure' ? ' selected' : ''}>Prior failure</option></select></label><button ${this.busy ? 'disabled' : ''}>Apply exact configuration</button></form>`;
    this.node.innerHTML = `<div class="kogg-panel"><header><h2>Kogg Workflow Editor</h2><p>The spatial canvas and structured outline edit one semantic graph. Execution remains unavailable until every selected production executor and authority grant is attested.</p></header><p role="status" aria-live="polite"><strong>Status:</strong> ${html(this.status)}</p>${this.projectId ? `<section><h3>Editable node order</h3><div class="kogg-workflow-view-switch" role="group" aria-label="Workflow editor view"><button data-view="outline" aria-pressed="${this.view === 'outline'}" ${this.busy ? 'disabled' : ''}>Show structured outline</button><button data-view="canvas" aria-pressed="${this.view === 'canvas'}" ${this.busy ? 'disabled' : ''}>Show spatial canvas</button></div>${editor}${configurationForm}<form data-add class="kogg-form-grid"><label>Node kind<select name="kind">${options}</select></label><button ${this.busy ? 'disabled' : ''}>Add node</button></form><div class="kogg-package-actions"><button data-validate ${this.busy ? 'disabled' : ''}>Validate workflow</button><button data-save ${this.busy ? 'disabled' : ''}>Save immutable version</button><button data-compile ${this.busy || !this.versions.length ? 'disabled' : ''}>Compile current version</button></div><section><h3>Saved versions</h3><ol aria-label="Immutable workflow versions">${versions || '<li>None</li>'}</ol></section></section>` : '<p class="kogg-blocked">No active project.</p>'}</div>`;
    this.bindEvents();
  }

  private bindEvents(): void {
    this.node.querySelectorAll<HTMLElement>('[data-view]').forEach(button => button.addEventListener('click', () => { this.view = button.dataset.view as 'outline' | 'canvas'; this.status = `${this.view === 'outline' ? 'Structured outline' : 'Spatial canvas'} active.`; this.render(); }));
    this.node.querySelector<HTMLFormElement>('[data-config]')?.addEventListener('submit', event => { event.preventDefault(); this.configure(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLFormElement>('[data-add]')?.addEventListener('submit', event => { event.preventDefault(); const kind = new FormData(event.currentTarget as HTMLFormElement).get('kind') as EditableNodeKind; const added = node(kind); this.nodes.push(added); this.selectedNodeId = added.nodeId; this.resetEdges(); this.status = `${kind} added.`; this.render(); });
    this.node.querySelectorAll<HTMLElement>('[data-select]').forEach(button => button.addEventListener('click', () => this.select(Number(button.dataset.select))));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-select]').forEach(button => button.addEventListener('click', () => this.select(Number(button.dataset.canvasSelect))));
    this.node.querySelectorAll<HTMLElement>('[data-up]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.up), -1)));
    this.node.querySelectorAll<HTMLElement>('[data-down]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.down), 1)));
    this.node.querySelectorAll<HTMLElement>('[data-remove]').forEach(button => button.addEventListener('click', () => this.remove(Number(button.dataset.remove))));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-up]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.canvasUp), -1)));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-down]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.canvasDown), 1)));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-remove]').forEach(button => button.addEventListener('click', () => this.remove(Number(button.dataset.canvasRemove))));
    this.node.querySelector<HTMLElement>('[data-validate]')?.addEventListener('click', () => void this.validate());
    this.node.querySelector<HTMLElement>('[data-save]')?.addEventListener('click', () => void this.save());
    this.node.querySelector<HTMLElement>('[data-compile]')?.addEventListener('click', () => void this.compile());
  }

  private move(index: number, offset: -1 | 1): void { this.nodes = [...moveOutlineNode(this.nodes, index, offset)]; this.resetEdges(); this.status = 'Node order changed.'; this.render(); }
  private remove(index: number): void { const removed = this.nodes[index]; this.nodes.splice(index, 1); if (removed?.nodeId === this.selectedNodeId) this.selectedNodeId = this.nodes[Math.min(index, this.nodes.length - 1)]!.nodeId; this.resetEdges(); this.status = 'Node removed.'; this.render(); }
  private select(index: number): void { this.selectedNodeId = this.nodes[index]!.nodeId; this.status = `${this.nodes[index]!.kind} selected for configuration.`; this.render(); }
  private configure(data: FormData): void { const index = this.nodes.findIndex(item => item.nodeId === this.selectedNodeId); if (index < 0) return; const prior = this.nodes[index]!; const optional = ['roleRevisionId','providerId','modelId','adapterKey','adapterVersion','deadlinePolicyId'] as const; const binding = Object.fromEntries(optional.flatMap(key => { const value = String(data.get(key) ?? '').trim(); return value ? [[key, value]] : []; })); const configuration: WorkflowNodeConfigurationV1 = { schemaVersion: '1', ...binding, absoluteDeadlineMs: Number(data.get('absoluteDeadlineMs')), target: String(data.get('target')) as WorkflowNodeConfigurationV1['target'], condition: String(data.get('condition')) as WorkflowNodeConfigurationV1['condition'] }; this.nodes[index] = { ...prior, configuration, configurationDigest: PENDING_CONFIGURATION_DIGEST }; this.status = `${prior.kind} configuration applied; validate before saving.`; this.render(); }
  private resetEdges(): void { this.edgeIds = this.nodes.slice(1).map(() => crypto.randomUUID()); }
  private async graph(): Promise<EditableWorkflowGraphV1> { const nodes = await Promise.all(this.nodes.map(async item => item.configuration ? { ...item, configurationDigest: await configurationDigest(item.configuration) } : item)); return buildLinearGraph(this.projectId!, nodes, this.edgeIds); }
  private async validate(): Promise<void> { await this.run('draft.validate', async () => { const result = await this.service.validate(await this.graph()); this.status = result.valid ? `Workflow valid: ${result.nodeCount} nodes and ${result.edgeCount} edges.` : `Workflow refused: ${result.code}.`; if (!result.valid) throw new UiResult(result.code); }); }
  private async save(): Promise<void> { await this.run('version.save', async () => { const result = await this.service.saveVersion({ requestId: crypto.randomUUID(), templateId: this.templateId, expectedVersionNumber: this.versions.at(-1)?.versionNumber ?? 0, graph: await this.graph() }); if (result.kind !== 'completed') throw new UiResult(result.code); this.versions = (await this.service.listProjectVersions(this.projectId!)).filter(version => version.templateId === this.templateId); this.status = `Workflow version ${result.version!.versionNumber} saved immutably.`; }); }
  private async compile(): Promise<void> { const current = this.versions.at(-1); if (!current) return; await this.run('compile', async () => { const result = await this.service.compile({ requestId: crypto.randomUUID(), versionId: current.versionId }); if (result.kind !== 'completed') throw new UiResult(result.code); this.status = `Compiled plan ${result.plan!.planId.slice(0, 8)} with ${result.plan!.injectedAnchorCount} mandatory anchors.`; }); }
  private async run(operation: string, action: () => Promise<void>, notify = true): Promise<void> { this.busy = true; this.render(); console.info('[kogg:workflow:editor] ui.operation.started', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable' }); try { await action(); console.info('[kogg:workflow:editor] ui.operation.completed', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable' }); } catch (error) { const safeCode = error instanceof UiResult ? error.code : 'WORKFLOW_INTERNAL'; console.error('[kogg:workflow:editor] ui.operation.failed', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode, errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = `Workflow operation failed safely: ${safeCode}.`; if (notify) void this.messages.error(this.status); } finally { this.busy = false; this.render(); } }
}

class UiResult extends Error { constructor(readonly code: string) { super(code); } }
function node(kind: EditableNodeKind): EditableWorkflowNodeV1 { return { nodeId: crypto.randomUUID(), kind, kindVersion: '1', configurationDigest: PENDING_CONFIGURATION_DIGEST, configuration: defaultConfiguration(kind), requestedEffects: GRANTS[kind], retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: 'none' } }; }
function defaultConfiguration(kind: EditableNodeKind): WorkflowNodeConfigurationV1 { const mutation = GRANTS[kind].includes('mutate-private-repository'); return { schemaVersion: '1', absoluteDeadlineMs: kind.startsWith('control.') ? 1_000 : kind.startsWith('approval.') ? 3_600_000 : 60_000, target: mutation ? 'private-worktree' : 'project-read-only', condition: kind === 'control.condition' ? 'prior-success' : 'always' }; }
async function configurationDigest(configuration: WorkflowNodeConfigurationV1): Promise<string> { const canonical = canonicalJson(configuration); const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(`kogg:workflow:node-configuration:v1\n${canonical}`)); return [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join(''); }
function canonicalJson(value: unknown): string { if (value === null) return 'null'; if (typeof value === 'string') return JSON.stringify(value.normalize('NFC')); if (typeof value === 'boolean') return value ? 'true' : 'false'; if (typeof value === 'number') return String(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`; const item = value as Record<string, unknown>; return `{${Object.keys(item).sort().map(key => `${JSON.stringify(key)}:${canonicalJson(item[key])}`).join(',')}}`; }
function html(value: string): string { return value.replace(/[&<>'"]/gu, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]!); }
