import { MessageService } from '@theia/core';
import { BaseWidget } from '@theia/core/lib/browser/widgets/widget';
import { inject, injectable, postConstruct } from '@theia/core/shared/inversify';
import { KoggProjectsService, type KoggProjectsService as ProjectsService } from '@kogg/projects/lib/common/projects-protocol';
import { KoggTasksService, type KoggTasksService as TasksService, type TaskAdmissionSummary } from '@kogg/tasks/lib/common/tasks-protocol';
import { EDITABLE_NODE_KINDS, KoggWorkflowService, type EdgeOutcome, type EditableNodeKind, type EditableWorkflowEdgeV1, type EditableWorkflowGraphV1, type EditableWorkflowNodeV1, type KoggWorkflowService as WorkflowService, type WorkflowAuthorityEffect, type WorkflowGroupV1, type WorkflowNodeConfigurationV1, type WorkflowPlanSummary, type WorkflowTemplateVersionProjection } from '../common/workflow-protocol';
import { allowedSourceOutcomes, connectWorkflowNodes, detachWorkflowNode, disconnectWorkflowEdge } from '../common/workflow-graph-edit';
import { createWorkflowGroup, detachNodeFromGroups, removeWorkflowGroup, reorderWorkflowGroupDisplay } from '../common/workflow-group-edit';
import { moveOutlineNode } from '../common/workflow-outline';

// diagnostic-coverage: workflow.schema, workflow.graph, workflow.authority, workflow.accessibility, workflow.source-maps

const PENDING_CONFIGURATION_DIGEST = '0'.repeat(64);
const GRANTS: Readonly<Record<EditableNodeKind, readonly WorkflowAuthorityEffect[]>> = {
  'research.agent': ['read-repository','invoke-provider'], 'pseudocode.agent': ['read-repository','mutate-private-repository','invoke-provider'],
  'probe.agent': ['read-repository','mutate-private-repository','invoke-provider','run-tool'], 'implementation.agent': ['read-repository','mutate-private-repository','invoke-provider','run-tool'],
  'tool.git': ['read-repository','mutate-private-repository','run-tool'], 'tool.build': ['read-repository','run-tool'],
  'check.deterministic': ['read-repository','run-tool','record-check'], 'approval.specification': ['record-approval'], 'approval.continue': ['record-approval'],
  'control.condition': [], 'control.parallel': [], 'control.join': [], 'control.group': [], 'control.finally': []
};

@injectable()
export class WorkflowEditorWidget extends BaseWidget {
  static readonly ID = 'kogg-workflow-editor'; static readonly LABEL = 'Kogg Workflow Editor';
  private projectId: string | undefined; private templateId: string = crypto.randomUUID();
  private nodes: EditableWorkflowNodeV1[] = [node('research.agent'), node('implementation.agent')];
  private edges: EditableWorkflowEdgeV1[] = [{ edgeId: crypto.randomUUID(), sourceNodeId: this.nodes[0]!.nodeId, sourcePort: 'success', targetNodeId: this.nodes[1]!.nodeId, targetPort: 'in' }];
  private groups: WorkflowGroupV1[] = [];
  private versions: readonly WorkflowTemplateVersionProjection[] = []; private plans: readonly WorkflowPlanSummary[] = []; private admissions: readonly TaskAdmissionSummary[] = [];
  private selectedPlanId = ''; private selectedAdmissionId = ''; private status = 'Loading workflow editor…'; private busy = false; private view: 'outline' | 'canvas' = 'outline'; private selectedNodeId = this.nodes[0]!.nodeId;

  constructor(@inject(KoggWorkflowService) private readonly service: WorkflowService,
    @inject(KoggProjectsService) private readonly projects: ProjectsService,
    @inject(KoggTasksService) private readonly tasks: TasksService,
    @inject(MessageService) private readonly messages: MessageService) { super(); }

  @postConstruct() protected init(): void {
    this.id = WorkflowEditorWidget.ID; this.title.label = WorkflowEditorWidget.LABEL; this.title.caption = 'Accessible governed workflow outline';
    this.title.closable = true; this.addClass('kogg-workflow-editor-widget'); this.render(); void this.load();
  }

  private async load(): Promise<void> {
    await this.run('editor.load', async () => {
      const projects = await this.projects.snapshot(); this.projectId = projects.activeProjectId;
      if (!this.projectId) { this.status = 'Open an active Kogg project before editing a workflow.'; return; }
      const projectVersions = await this.service.listProjectVersions(this.projectId); this.templateId = projectVersions.at(-1)?.templateId ?? crypto.randomUUID();
      this.versions = projectVersions.filter(version => version.templateId === this.templateId);
      await this.refreshRunInputs();
      this.status = this.versions.length ? `Workflow version ${this.versions.at(-1)!.versionNumber} is current.` : 'Structured workflow outline ready.';
    }, false);
  }

  private render(): void {
    const options = EDITABLE_NODE_KINDS.map(kind => `<option value="${kind}">${kind}</option>`).join('');
    const rows = this.nodes.map((item, index) => `<li data-workflow-node="${html(item.nodeId)}"><strong>${index + 1}. ${html(item.kind)}</strong><span> · ${item.requestedEffects.length} bounded effects · retry ${item.retry.maxAttempts}</span><div class="kogg-package-actions"><button data-select="${index}" aria-pressed="${item.nodeId === this.selectedNodeId}" ${this.busy ? 'disabled' : ''} aria-label="Configure ${html(item.kind)}">Configure</button><button data-up="${index}" ${this.busy || index === 0 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} up">Up</button><button data-down="${index}" ${this.busy || index === this.nodes.length - 1 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} down">Down</button><button data-remove="${index}" ${this.busy || this.nodes.length === 1 ? 'disabled' : ''} aria-label="Remove ${html(item.kind)}">Remove</button></div></li>`).join('');
    const canvas = this.nodes.map((item, index) => `<article role="listitem" tabindex="0" data-workflow-canvas-node="${html(item.nodeId)}"><span>Step ${index + 1}</span><strong>${html(item.kind)}</strong><p>${item.requestedEffects.length} bounded effects · retry ${item.retry.maxAttempts}</p><div class="kogg-package-actions"><button data-canvas-select="${index}" aria-pressed="${item.nodeId === this.selectedNodeId}" ${this.busy ? 'disabled' : ''} aria-label="Configure ${html(item.kind)} on canvas">Configure</button><button data-canvas-up="${index}" ${this.busy || index === 0 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} earlier on canvas">Earlier</button><button data-canvas-down="${index}" ${this.busy || index === this.nodes.length - 1 ? 'disabled' : ''} aria-label="Move ${html(item.kind)} later on canvas">Later</button><button data-canvas-remove="${index}" ${this.busy || this.nodes.length === 1 ? 'disabled' : ''} aria-label="Remove ${html(item.kind)} from canvas">Remove</button></div></article>`).join('');
    const versions = this.versions.map(version => `<li data-workflow-version="${version.versionNumber}">Version ${version.versionNumber} · ${html(version.versionId.slice(0, 8))} · immutable</li>`).join('');
    const planOptions = this.plans.map(plan => `<option value="${html(plan.planId)}"${plan.planId === this.selectedPlanId ? ' selected' : ''}>Version ${plan.versionNumber} · ${html(plan.planId.slice(0, 8))} · ${plan.injectedAnchorCount} anchors</option>`).join('');
    const admissionOptions = this.admissions.map(admission => `<option value="${html(admission.taskAdmissionId)}"${admission.taskAdmissionId === this.selectedAdmissionId ? ' selected' : ''}>Task ${html(admission.taskId.slice(0, 8))} · run ${html(admission.runId.slice(0, 8))}${Date.parse(admission.expiresAt) <= Date.now() ? ' · expired' : ''}</option>`).join('');
    const runForm = `<form data-run class="kogg-form-grid"><h3>Governed run admission</h3><p>Select exact immutable backend artifacts. Start remains fail-closed unless current mode, task, executor, and authority checks all pass.</p><label>Compiled plan<select name="planId" required><option value="">Select compiled plan</option>${planOptions}</select></label><label>Task admission<select name="taskAdmissionId" required><option value="">Select task admission</option>${admissionOptions}</select></label><button ${this.busy || !this.plans.length || !this.admissions.length ? 'disabled' : ''}>Start governed workflow</button><button type="button" data-refresh-run ${this.busy ? 'disabled' : ''}>Refresh admission artifacts</button></form>`;
    const nodeOptions = this.nodes.map((item, index) => `<option value="${html(item.nodeId)}">${index + 1}. ${html(item.kind)}</option>`).join('');
    const routeRows = this.edges.map((edge, index) => { const sourceIndex = this.nodes.findIndex(item => item.nodeId === edge.sourceNodeId); const targetIndex = this.nodes.findIndex(item => item.nodeId === edge.targetNodeId); const source = this.nodes[sourceIndex]!; const target = this.nodes[targetIndex]!; return `<label>Route ${sourceIndex + 1}. ${html(source.kind)} to ${targetIndex + 1}. ${html(target.kind)}<select name="route-${index}">${allowedSourceOutcomes(source.kind).map(outcome => `<option value="${outcome}"${edge.sourcePort === outcome ? ' selected' : ''}>${outcome}</option>`).join('')}</select></label>`; }).join('');
    const connections = this.edges.map((edge, index) => { const sourceIndex = this.nodes.findIndex(item => item.nodeId === edge.sourceNodeId); const targetIndex = this.nodes.findIndex(item => item.nodeId === edge.targetNodeId); return `<li>${sourceIndex + 1}. ${html(this.nodes[sourceIndex]!.kind)} · ${edge.sourcePort} → ${targetIndex + 1}. ${html(this.nodes[targetIndex]!.kind)} <button data-disconnect="${html(edge.edgeId)}" aria-label="Disconnect connection ${index + 1}" ${this.busy ? 'disabled' : ''}>Disconnect</button></li>`; }).join('');
    const connectionForm = `<form data-connect class="kogg-form-grid"><h3>Connect nodes</h3><p>Add an exact directed connection. The backend independently rejects cycles, unreachable nodes, invalid ports, and ambiguous joins.</p><label>Source node<select name="sourceNodeId">${nodeOptions}</select></label><label>Source outcome<select name="sourcePort"><option value="success">success</option><option value="failure">failure</option><option value="finally">finally</option><option value="true">true</option><option value="false">false</option></select></label><label>Target node<select name="targetNodeId">${nodeOptions}</select></label><button ${this.busy || this.nodes.length < 2 ? 'disabled' : ''}>Connect nodes</button></form><h3>Current connections</h3><ol aria-label="Workflow connections">${connections || '<li>None</li>'}</ol>`;
    const routeForm = `<form data-routes class="kogg-form-grid"><h3>Connection outcomes</h3><p>Choose the exact source outcome that activates each connection. Failure and finally routes run only after the node owner proves cleanup.</p>${routeRows || '<p>No connections.</p>'}<button ${this.busy || !this.edges.length ? 'disabled' : ''}>Apply connection outcomes</button></form>`;
    const editor = this.view === 'outline' ? `<ol aria-label="Workflow node outline">${rows}</ol>` : `<div class="kogg-workflow-canvas" role="list" aria-label="Workflow spatial canvas">${canvas}</div>`;
    const selected = this.nodes.find(item => item.nodeId === this.selectedNodeId) ?? this.nodes[0]!; const configuration = selected.configuration ?? defaultConfiguration(selected.kind);
    const configurationForm = `<form data-config class="kogg-form-grid"><h3>Configure ${html(selected.kind)}</h3><label>Role revision ID<input name="roleRevisionId" value="${html(configuration.roleRevisionId ?? '')}"></label><label>Provider ID<input name="providerId" value="${html(configuration.providerId ?? '')}"></label><label>Model ID<input name="modelId" value="${html(configuration.modelId ?? '')}"></label><label>Adapter key<input name="adapterKey" value="${html(configuration.adapterKey ?? '')}"></label><label>Adapter version<input name="adapterVersion" value="${html(configuration.adapterVersion ?? '')}"></label><label>Deadline policy<input name="deadlinePolicyId" value="${html(configuration.deadlinePolicyId ?? '')}"></label><label>Absolute deadline (ms)<input name="absoluteDeadlineMs" inputmode="numeric" required value="${configuration.absoluteDeadlineMs}"></label><label>Target<select name="target"><option value="project-read-only"${configuration.target === 'project-read-only' ? ' selected' : ''}>Project read-only</option><option value="private-worktree"${configuration.target === 'private-worktree' ? ' selected' : ''}>Private worktree</option></select></label><label>Condition<select name="condition"><option value="always"${configuration.condition === 'always' ? ' selected' : ''}>Always</option><option value="prior-success"${configuration.condition === 'prior-success' ? ' selected' : ''}>Prior success</option><option value="prior-failure"${configuration.condition === 'prior-failure' ? ' selected' : ''}>Prior failure</option></select></label><label>Maximum attempts<select name="maxAttempts">${[1,2,3].map(value => `<option value="${value}"${selected.retry.maxAttempts === value ? ' selected' : ''}>${value}</option>`).join('')}</select></label><label>Retry backoff<select name="backoffMs">${[0,1000,5000,15000].map(value => `<option value="${value}"${selected.retry.backoffMs === value ? ' selected' : ''}>${value} ms</option>`).join('')}</select></label><label>Retry side-effect policy<select name="sideEffectPolicy"><option value="none"${selected.retry.sideEffectPolicy === 'none' ? ' selected' : ''}>None</option><option value="idempotent-exact-key"${selected.retry.sideEffectPolicy === 'idempotent-exact-key' ? ' selected' : ''}>Idempotent exact key</option><option value="fresh-authority"${selected.retry.sideEffectPolicy === 'fresh-authority' ? ' selected' : ''}>Fresh authority</option></select></label><button ${this.busy ? 'disabled' : ''}>Apply exact configuration</button></form>`;
    const groups = this.groups.map((group, index) => `<li>Group ${index + 1}: ${group.memberNodeIds.length} visible members <button data-remove-group="${group.groupId}" ${this.busy ? 'disabled' : ''}>Ungroup</button></li>`).join('');
    this.node.innerHTML = `<div class="kogg-panel"><header><h2>Kogg Workflow Editor</h2><p>The spatial canvas and structured outline edit one semantic graph. Execution remains unavailable until every selected production executor and authority grant is attested.</p></header><p role="status" aria-live="polite"><strong>Status:</strong> ${html(this.status)}</p>${this.projectId ? `<section><h3>Editable node order</h3><div class="kogg-workflow-view-switch" role="group" aria-label="Workflow editor view"><button data-view="outline" aria-pressed="${this.view === 'outline'}" ${this.busy ? 'disabled' : ''}>Show structured outline</button><button data-view="canvas" aria-pressed="${this.view === 'canvas'}" ${this.busy ? 'disabled' : ''}>Show spatial canvas</button></div>${editor}${configurationForm}<form data-add class="kogg-form-grid"><label>Node kind<select name="kind">${options}</select></label><button ${this.busy ? 'disabled' : ''}>Add node</button><button type="button" data-add-parallel ${this.busy ? 'disabled' : ''}>Add parallel fork and join</button><button type="button" data-create-group ${this.busy ? 'disabled' : ''}>Group selected with previous node</button></form><section><h3>Visual groups</h3><ol aria-label="Workflow visual groups">${groups || '<li>None</li>'}</ol></section>${connectionForm}${routeForm}<div class="kogg-package-actions"><button data-validate ${this.busy ? 'disabled' : ''}>Validate workflow</button><button data-save ${this.busy ? 'disabled' : ''}>Save immutable version</button><button data-compile ${this.busy || !this.versions.length ? 'disabled' : ''}>Compile current version</button></div><section><h3>Saved versions</h3><ol aria-label="Immutable workflow versions">${versions || '<li>None</li>'}</ol></section>${runForm}</section>` : '<p class="kogg-blocked">No active project.</p>'}</div>`;
    this.bindEvents();
  }

  private bindEvents(): void {
    this.node.querySelectorAll<HTMLElement>('[data-view]').forEach(button => button.addEventListener('click', () => { this.view = button.dataset.view as 'outline' | 'canvas'; this.status = `${this.view === 'outline' ? 'Structured outline' : 'Spatial canvas'} active.`; this.render(); }));
    this.node.querySelector<HTMLFormElement>('[data-config]')?.addEventListener('submit', event => { event.preventDefault(); this.configure(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLFormElement>('[data-connect]')?.addEventListener('submit', event => { event.preventDefault(); this.connect(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLFormElement>('[data-routes]')?.addEventListener('submit', event => { event.preventDefault(); this.configureRoutes(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLFormElement>('[data-add]')?.addEventListener('submit', event => { event.preventDefault(); const kind = new FormData(event.currentTarget as HTMLFormElement).get('kind') as EditableNodeKind; const added = node(kind); const prior = this.nodes.at(-1); this.nodes.push(added); if (prior) this.edges = [...connectWorkflowNodes(this.nodes, this.edges, crypto.randomUUID(), prior.nodeId, 'success', added.nodeId)]; this.selectedNodeId = added.nodeId; this.status = `${kind} added.`; this.render(); });
    this.node.querySelector<HTMLElement>('[data-add-parallel]')?.addEventListener('click', () => this.addParallel());
    this.node.querySelector<HTMLElement>('[data-create-group]')?.addEventListener('click', () => this.createGroup());
    this.node.querySelectorAll<HTMLElement>('[data-remove-group]').forEach(button => button.addEventListener('click', () => this.removeGroup(button.dataset.removeGroup!)));
    this.node.querySelectorAll<HTMLElement>('[data-select]').forEach(button => button.addEventListener('click', () => this.select(Number(button.dataset.select))));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-select]').forEach(button => button.addEventListener('click', () => this.select(Number(button.dataset.canvasSelect))));
    this.node.querySelectorAll<HTMLElement>('[data-up]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.up), -1)));
    this.node.querySelectorAll<HTMLElement>('[data-down]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.down), 1)));
    this.node.querySelectorAll<HTMLElement>('[data-remove]').forEach(button => button.addEventListener('click', () => this.remove(Number(button.dataset.remove))));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-up]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.canvasUp), -1)));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-down]').forEach(button => button.addEventListener('click', () => this.move(Number(button.dataset.canvasDown), 1)));
    this.node.querySelectorAll<HTMLElement>('[data-canvas-remove]').forEach(button => button.addEventListener('click', () => this.remove(Number(button.dataset.canvasRemove))));
    this.node.querySelectorAll<HTMLElement>('[data-disconnect]').forEach(button => button.addEventListener('click', () => this.disconnect(button.dataset.disconnect!)));
    this.node.querySelector<HTMLElement>('[data-validate]')?.addEventListener('click', () => void this.validate());
    this.node.querySelector<HTMLElement>('[data-save]')?.addEventListener('click', () => void this.save());
    this.node.querySelector<HTMLElement>('[data-compile]')?.addEventListener('click', () => void this.compile());
    this.node.querySelector<HTMLFormElement>('[data-run]')?.addEventListener('submit', event => { event.preventDefault(); void this.admit(new FormData(event.currentTarget as HTMLFormElement)); });
    this.node.querySelector<HTMLElement>('[data-refresh-run]')?.addEventListener('click', () => void this.run('admission.refresh', async () => { await this.refreshRunInputs(); this.status = 'Governed run artifacts refreshed.'; }));
  }

  private move(index: number, offset: -1 | 1): void { this.nodes = [...moveOutlineNode(this.nodes, index, offset)]; this.groups = [...reorderWorkflowGroupDisplay(this.groups, this.nodes.map(node => node.nodeId))]; this.status = 'Node display order changed; semantic connections preserved.'; this.render(); }
  private addParallel(): void { const prior = this.nodes.at(-1); const fork = node('control.parallel'); const left = node('control.group'); const right = node('control.group'); const join = node('control.join'); this.nodes.push(fork, left, right, join); let edges = this.edges as readonly EditableWorkflowEdgeV1[]; if (prior) edges = connectWorkflowNodes(this.nodes, edges, crypto.randomUUID(), prior.nodeId, 'success', fork.nodeId); edges = connectWorkflowNodes(this.nodes, edges, crypto.randomUUID(), fork.nodeId, 'success', left.nodeId); edges = connectWorkflowNodes(this.nodes, edges, crypto.randomUUID(), fork.nodeId, 'success', right.nodeId); edges = connectWorkflowNodes(this.nodes, edges, crypto.randomUUID(), left.nodeId, 'success', join.nodeId); edges = connectWorkflowNodes(this.nodes, edges, crypto.randomUUID(), right.nodeId, 'success', join.nodeId); this.edges = [...edges]; this.selectedNodeId = join.nodeId; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'parallel.scaffold', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', branchCount: 2, nodeCount: this.nodes.length, edgeCount: this.edges.length }); this.status = 'Two-branch parallel fork and exact join added; configure branches and validate before saving.'; this.render(); }
  private remove(index: number): void { const removed = this.nodes[index]; if (!removed) return; const priorCount = this.edges.length; this.nodes.splice(index, 1); this.edges = [...detachWorkflowNode(this.edges, removed.nodeId)]; this.groups = [...detachNodeFromGroups(this.groups, removed.nodeId)]; if (removed.nodeId === this.selectedNodeId) this.selectedNodeId = this.nodes[Math.min(index, this.nodes.length - 1)]!.nodeId; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'node.remove', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', detachedEdgeCount: priorCount - this.edges.length }); this.status = `Node removed with ${priorCount - this.edges.length} dependent connection(s); reconnect and validate before saving.`; this.render(); }
  private createGroup(): void { const index = this.nodes.findIndex(node => node.nodeId === this.selectedNodeId); const prior = this.nodes[index - 1]; if (index < 1 || !prior) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'group.create', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_GRAPH_INVALID', errorType: 'MissingPriorNode' }); this.status = 'Workflow operation failed safely: WORKFLOW_GRAPH_INVALID.'; this.render(); return; } try { this.groups = [...createWorkflowGroup(this.groups, crypto.randomUUID(), [prior.nodeId, this.selectedNodeId])]; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'group.create', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', groupCount: this.groups.length }); this.status = 'Visual group created with two explicit members; execution graph is unchanged.'; } catch (error) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'group.create', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_GRAPH_INVALID', errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = 'Workflow operation failed safely: WORKFLOW_GRAPH_INVALID.'; } this.render(); }
  private removeGroup(groupId: string): void { try { this.groups = [...removeWorkflowGroup(this.groups, groupId)]; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'group.remove', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', groupCount: this.groups.length }); this.status = 'Visual group removed; member nodes and connections were preserved.'; } catch (error) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'group.remove', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_GRAPH_INVALID', errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = 'Workflow operation failed safely: WORKFLOW_GRAPH_INVALID.'; } this.render(); }
  private select(index: number): void { this.selectedNodeId = this.nodes[index]!.nodeId; this.status = `${this.nodes[index]!.kind} selected for configuration.`; this.render(); }
  private configure(data: FormData): void { const index = this.nodes.findIndex(item => item.nodeId === this.selectedNodeId); if (index < 0) return; const prior = this.nodes[index]!; const optional = ['roleRevisionId','providerId','modelId','adapterKey','adapterVersion','deadlinePolicyId'] as const; const binding = Object.fromEntries(optional.flatMap(key => { const value = String(data.get(key) ?? '').trim(); return value ? [[key, value]] : []; })); const configuration: WorkflowNodeConfigurationV1 = { schemaVersion: '1', ...binding, absoluteDeadlineMs: Number(data.get('absoluteDeadlineMs')), target: String(data.get('target')) as WorkflowNodeConfigurationV1['target'], condition: String(data.get('condition')) as WorkflowNodeConfigurationV1['condition'] }; const retry: EditableWorkflowNodeV1['retry'] = { maxAttempts: Number(data.get('maxAttempts')), backoffMs: Number(data.get('backoffMs')) as EditableWorkflowNodeV1['retry']['backoffMs'], sideEffectPolicy: String(data.get('sideEffectPolicy')) as EditableWorkflowNodeV1['retry']['sideEffectPolicy'] }; this.nodes[index] = { ...prior, configuration, configurationDigest: PENDING_CONFIGURATION_DIGEST, retry }; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'node.configure', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', nodeKind: prior.kind, maxAttempts: retry.maxAttempts, backoffMs: retry.backoffMs, sideEffectPolicy: retry.sideEffectPolicy }); this.status = `${prior.kind} configuration applied; validate before saving.`; this.render(); }
  private connect(data: FormData): void { try { this.edges = [...connectWorkflowNodes(this.nodes, this.edges, crypto.randomUUID(), String(data.get('sourceNodeId')), String(data.get('sourcePort')) as EdgeOutcome, String(data.get('targetNodeId')))]; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'edge.connect', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', edgeCount: this.edges.length }); this.status = 'Connection added; validate before saving.'; } catch (error) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'edge.connect', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_PORT_INVALID', errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = 'Workflow operation failed safely: WORKFLOW_PORT_INVALID.'; } this.render(); }
  private disconnect(edgeId: string): void { try { this.edges = [...disconnectWorkflowEdge(this.edges, edgeId)]; console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'edge.disconnect', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', edgeCount: this.edges.length }); this.status = 'Connection removed; reconnect and validate before saving.'; } catch (error) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'edge.disconnect', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_PORT_INVALID', errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = 'Workflow operation failed safely: WORKFLOW_PORT_INVALID.'; } this.render(); }
  private configureRoutes(data: FormData): void { const outcomes = this.edges.map((_, index) => String(data.get(`route-${index}`)) as EdgeOutcome); const invalid = outcomes.findIndex((outcome, index) => { const source = this.nodes.find(node => node.nodeId === this.edges[index]!.sourceNodeId); return !source || !allowedSourceOutcomes(source.kind).includes(outcome); }); if (invalid >= 0) { console.warn('[kogg:workflow:editor] ui.operation.failed', { operation: 'route.configure', templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode: 'WORKFLOW_PORT_INVALID', errorType: 'InvalidRouteOutcome' }); this.status = 'Workflow operation failed safely: WORKFLOW_PORT_INVALID.'; this.render(); return; } this.edges = this.edges.map((edge, index) => ({ ...edge, sourcePort: outcomes[index]! })); console.info('[kogg:workflow:editor] ui.operation.completed', { operation: 'route.configure', templateId: this.templateId, projectId: this.projectId ?? 'unavailable' }); this.status = 'Connection outcomes applied; validate before saving.'; this.render(); }
  private async graph(): Promise<EditableWorkflowGraphV1> { const nodes = await Promise.all(this.nodes.map(async item => item.configuration ? { ...item, configurationDigest: await configurationDigest(item.configuration) } : item)); return { schemaVersion: '1', projectId: this.projectId!, nodes, edges: this.edges, groups: this.groups }; }
  private async validate(): Promise<void> { await this.run('draft.validate', async () => { const result = await this.service.validate(await this.graph()); this.status = result.valid ? `Workflow valid: ${result.nodeCount} nodes and ${result.edgeCount} edges.` : `Workflow refused: ${result.code}.`; if (!result.valid) throw new UiResult(result.code); }); }
  private async save(): Promise<void> { await this.run('version.save', async () => { const result = await this.service.saveVersion({ requestId: crypto.randomUUID(), templateId: this.templateId, expectedVersionNumber: this.versions.at(-1)?.versionNumber ?? 0, graph: await this.graph() }); if (result.kind !== 'completed') throw new UiResult(result.code); this.versions = (await this.service.listProjectVersions(this.projectId!)).filter(version => version.templateId === this.templateId); this.status = `Workflow version ${result.version!.versionNumber} saved immutably.`; }); }
  private async compile(): Promise<void> { const current = this.versions.at(-1); if (!current) return; await this.run('compile', async () => { const result = await this.service.compile({ requestId: crypto.randomUUID(), versionId: current.versionId }); if (result.kind !== 'completed') throw new UiResult(result.code); await this.refreshRunInputs(); this.selectedPlanId = result.plan!.planId; this.status = `Compiled plan ${result.plan!.planId.slice(0, 8)} with ${result.plan!.injectedAnchorCount} mandatory anchors.`; }); }
  private async refreshRunInputs(): Promise<void> { if (!this.projectId) return; [this.plans, this.admissions] = await Promise.all([this.service.listProjectPlans(this.projectId), this.tasks.listAdmissions(this.projectId)]); if (!this.plans.some(plan => plan.planId === this.selectedPlanId)) this.selectedPlanId = this.plans.at(-1)?.planId ?? ''; if (!this.admissions.some(admission => admission.taskAdmissionId === this.selectedAdmissionId)) this.selectedAdmissionId = this.admissions.find(admission => Date.parse(admission.expiresAt) > Date.now())?.taskAdmissionId ?? this.admissions[0]?.taskAdmissionId ?? ''; }
  private async admit(data: FormData): Promise<void> { const planId = String(data.get('planId') ?? ''); const taskAdmissionId = String(data.get('taskAdmissionId') ?? ''); this.selectedPlanId = planId; this.selectedAdmissionId = taskAdmissionId; await this.run('run.admit', async () => { const result = await this.service.admitRun({ requestId: crypto.randomUUID(), planId, taskAdmissionId }); if (result.kind !== 'completed' && result.kind !== 'waiting') throw new UiResult(result.code); this.status = result.kind === 'waiting' ? `Workflow ${result.run.runId.slice(0, 8)} is waiting for continuation approval.` : `Workflow ${result.run?.runId.slice(0, 8)} completed.`; }); }
  private async run(operation: string, action: () => Promise<void>, notify = true): Promise<void> { this.busy = true; this.render(); console.info('[kogg:workflow:editor] ui.operation.started', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable' }); try { await action(); console.info('[kogg:workflow:editor] ui.operation.completed', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable' }); } catch (error) { const safeCode = error instanceof UiResult ? error.code : 'WORKFLOW_INTERNAL'; console.error('[kogg:workflow:editor] ui.operation.failed', { operation, templateId: this.templateId, projectId: this.projectId ?? 'unavailable', safeCode, errorType: error instanceof Error ? error.name : 'UnknownError' }); this.status = `Workflow operation failed safely: ${safeCode}.`; if (notify) void this.messages.error(this.status); } finally { this.busy = false; this.render(); } }
}

class UiResult extends Error { constructor(readonly code: string) { super(code); } }
function node(kind: EditableNodeKind): EditableWorkflowNodeV1 { return { nodeId: crypto.randomUUID(), kind, kindVersion: '1', configurationDigest: PENDING_CONFIGURATION_DIGEST, configuration: defaultConfiguration(kind), requestedEffects: GRANTS[kind], retry: { maxAttempts: 1, backoffMs: 0, sideEffectPolicy: 'none' } }; }
function defaultConfiguration(kind: EditableNodeKind): WorkflowNodeConfigurationV1 { const mutation = GRANTS[kind].includes('mutate-private-repository'); return { schemaVersion: '1', absoluteDeadlineMs: kind.startsWith('control.') ? 1_000 : kind.startsWith('approval.') ? 3_600_000 : 60_000, target: mutation ? 'private-worktree' : 'project-read-only', condition: kind === 'control.condition' ? 'prior-success' : 'always' }; }
async function configurationDigest(configuration: WorkflowNodeConfigurationV1): Promise<string> { const canonical = canonicalJson(configuration); const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(`kogg:workflow:node-configuration:v1\n${canonical}`)); return [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join(''); }
function canonicalJson(value: unknown): string { if (value === null) return 'null'; if (typeof value === 'string') return JSON.stringify(value.normalize('NFC')); if (typeof value === 'boolean') return value ? 'true' : 'false'; if (typeof value === 'number') return String(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`; const item = value as Record<string, unknown>; return `{${Object.keys(item).sort().map(key => `${JSON.stringify(key)}:${canonicalJson(item[key])}`).join(',')}}`; }
function html(value: string): string { return value.replace(/[&<>'"]/gu, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]!); }
